import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest'
const source=readFileSync('supabase/functions/complaint-generate-report/index.ts','utf8');const assets=['baghdad-municipality.png','alliance.png','akaram.png'].map(name=>readFileSync(`supabase/functions/complaint-generate-report/assets/${name}`))
describe('عقد الهوية الاحترافية لتقرير PowerPoint',()=>{
 it('يحزم الشعارات الثلاثة كصور PNG سليمة داخل وظيفة التقرير',()=>{expect(assets).toHaveLength(3);for(const bytes of assets)expect([...bytes.subarray(0,8)]).toEqual([137,80,78,71,13,10,26,10]);expect(source).toContain("'./assets/baghdad-municipality.png'");expect(source).toContain("'./assets/alliance.png'");expect(source).toContain("'./assets/akaram.png'")})
 it('يبني غلافاً بإطار دائري وهوية قابلة للتعديل',()=>{expect(source).toContain('roundRect(.55,.4,12.2,6.65');expect(source).toContain('layout.authorityLine');expect(source).toContain('layout.contractorLine');expect(source).toContain("'تقرير بريد مستقل'");expect(source).toContain("'تقرير يومي جامع'")})
 it('يرسم جدول البيانات مطابقاً للمعاينة من اليمين دون تسمية قاعدة بيانات',()=>{expect(source).toContain("['الزقاق','المحلة','المركز','نوع التلكؤ','مسؤول القسم','ت']");expect(source).toContain("textBox('جدول بيانات التلكؤات'");expect(source).toContain("'F8FAFC'");expect(source).toContain('موقع في الصفحات التالية');expect(source).not.toContain("textBox('قاعدة بيانات الشكاوى')")})
 it('يجمع النتائج حسب البريد والمسؤول ويضيف فاصلاً واضحاً لكل مجموعة',()=>{expect(source).toContain("const groups=new Map<string,{subject:string;manager:string;items:Row[]}>");expect(source).toContain("'مجموعة البريد والمسؤول'");expect(source).toContain('groupInfo.subject');expect(source).toContain('groupInfo.manager')})
 it('يحافظ على صور قبل وبعد وعلى PPTX قابل للفتح دون تمديد أبعاد الصور',()=>{expect(source).toContain("v.media_kind==='before'");expect(source).toContain("v.media_kind==='after'");expect(source).toContain("compression:'DEFLATE'");expect(source).toContain('validMagic(bytes,mime)');expect(source).toContain('fitInside(');expect(source).toContain('loaded.width,loaded.height')})
 it('ينشئ مساراً فريداً لكل نسخة ويمنع إعادة ملف قديم من الذاكرة المؤقتة',()=>{expect(source).toContain('crypto.randomUUID()');expect(source).toContain('${generationId}.pptx');expect(source).toContain("upsert:false,cacheControl:'no-cache'");expect(source).toContain('reviewed_pptx_path:null')})
 it('يطابق الغلاف المحرر ويختار البلدية الصحيحة بحسب القاطع',()=>{expect(source).toContain("layout.title??report.title");expect(source).toContain("report.sector==='karrada'?'الكرادة':'الزعفرانية'");expect(source).toContain('textBox(coverTitle');expect(source).toContain('coverFontSize,true,accent,fontFamily')})
})
