import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest'
const sql=readFileSync('supabase/migrations/00057_complaints_analytics_reports.sql','utf8');const dashboard=readFileSync('src/portals/complaints/pages/Dashboard/DashboardPage.tsx','utf8');const manager=readFileSync('src/portals/manager/pages/Complaints/ComplaintTicketPage.tsx','utf8');const inbox=readFileSync('src/portals/complaints/pages/Inbox/InboxPage.tsx','utf8');const printCss=readFileSync('src/styles/print.css','utf8');const analyticsReport=readFileSync('src/features/complaints/lib/analytics-report.ts','utf8')
describe('التحليلات وتجربة الاستخدام',()=>{
 it('تحليلات الفترات محمية وتستخدم توقيت بغداد',()=>{expect(sql).toContain('COMPLAINT_ANALYTICS_FORBIDDEN');expect(sql).toContain("timezone('Asia/Baghdad'");expect(sql).toContain('p_to-p_from>731');expect(sql).toContain('revoke all on function public.complaint_analytics')})
 it('الرئيسية تدعم الفترات الخمس والطباعة والحفظ بتوقيت بغداد دون وصول مباشر للبيانات',()=>{for(const value of ['daily','weekly','monthly','semiannual','annual'])expect(dashboard).toContain(value);expect(dashboard).toContain('printComplaintAnalytics');expect(dashboard).toContain('downloadComplaintAnalytics');expect(dashboard).toContain('baghdadDateKey');expect(dashboard).not.toContain('toISOString().slice');expect(dashboard).not.toMatch(/supabase\.(from|rpc)/)})
 it('الطباعة تخفي تنقل التطبيق وتحرر ارتفاع وتمرير المحتوى',()=>{for(const marker of ['app-sidebar','app-header','mobile-bottom-nav'])expect(printCss).toContain(marker);expect(printCss).toContain('height: auto !important');expect(printCss).toContain('overflow: visible !important');expect(analyticsReport).toContain("timeZone:'Asia/Baghdad'");expect(analyticsReport).toContain('thead{display:table-header-group}')})
 it('صفحة المسؤول تفصل الكاميرا والجهاز وتمنع GPS وتفرض التطابق العددي',()=>{expect(manager).toContain('CameraCapture');expect(manager).toContain('صور دفعة واحدة');expect(manager).not.toContain('getCurrentPosition');expect(manager).toContain('files.length!==activeItems.length')})
 it('تحويل PDF بلا حد عددي تطبيقي ويعرض نتيجة واضحة',()=>{expect(readFileSync('src/features/complaints/lib/pdf-pages.ts','utf8')).not.toContain('PDF_TOO_MANY_PAGES');expect(inbox).toContain('تم تحويل ملف PDF كاملاً إلى')})
})
