import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest'
const source=readFileSync('supabase/functions/complaint-generate-report/index.ts','utf8');const assets=['baghdad-municipality.png','alliance.png','akaram.png'].map(name=>readFileSync(`supabase/functions/complaint-generate-report/assets/${name}`))
describe('عقد الهوية الاحترافية لتقرير PowerPoint',()=>{
 it('يحزم الشعارات الثلاثة كصور PNG سليمة داخل وظيفة التقرير',()=>{expect(assets).toHaveLength(3);for(const bytes of assets)expect([...bytes.subarray(0,8)]).toEqual([137,80,78,71,13,10,26,10]);expect(source).toContain("'./assets/baghdad-municipality.png'");expect(source).toContain("'./assets/alliance.png'");expect(source).toContain("'./assets/akaram.png'")})
 it('يبني غلافاً بإطار دائري وهوية قابلة للتعديل',()=>{expect(source).toContain('roundRect(.55,.4,12.2,6.65');expect(source).toContain('layout.authorityLine');expect(source).toContain('layout.contractorLine');expect(source).toContain("'تقرير بريد مستقل'");expect(source).toContain("'تقرير يومي جامع'")})
 it('يرتب جدول البيانات من اليمين وفق النموذج دون تسمية قاعدة بيانات',()=>{expect(source).toContain("['وقت وصول الشكوى','نوع التلكؤ','المركز البلدي','رقم الزقاق','رقم المحلة','التاريخ','ت']");expect(source).toContain('arrivalAr(p?.received_at)');expect(source).not.toContain("textBox('قاعدة بيانات الشكاوى'")})
 it('يحافظ على صور قبل وبعد وعلى PPTX قابل للفتح',()=>{expect(source).toContain("v.media_kind==='before'");expect(source).toContain("v.media_kind==='after'");expect(source).toContain("compression:'DEFLATE'");expect(source).toContain('validMagic(bytes,mime)')})
 it('ينشئ مساراً فريداً لكل نسخة ويمنع إعادة ملف قديم من الذاكرة المؤقتة',()=>{expect(source).toContain('crypto.randomUUID()');expect(source).toContain('${generationId}.pptx');expect(source).toContain("upsert:false,cacheControl:'no-cache'");expect(source).toContain('reviewed_pptx_path:null')})
 it('يطابق الغلاف المحرر ويختار البلدية الصحيحة بحسب القاطع',()=>{expect(source).toContain("layout.title??report.title");expect(source).toContain("report.sector==='karrada'?'الكرادة':'الزعفرانية'");expect(source).toContain('textBox(coverTitle');expect(source).toContain('coverFontSize,true,accent,fontFamily')})
})
