do $$ declare u uuid='74000000-0000-0000-0000-000000000001';v public.garage_vehicles;n int;begin
perform set_config('role','authenticated',false);perform set_config('request.jwt.claim.sub',u::text,false);
v:=public.garage_add_vehicle('تنكر مؤجر','DB-RENT-1','بغداد RENT','CHASSIS-RENT-1',u::text||'/rent.webp','morning','سائق مؤجر',1::smallint,'tanker','rented','شركة التأجير','C-2026-9','2026-09-01'::date,'2027-09-01'::date,2025::smallint,'أبيض','سعة 10000 لتر');
if v.vehicle_category<>'tanker' or v.ownership_type<>'rented' or v.lessor_name<>'شركة التأجير' or v.model_year<>2025 then raise exception 'GARAGE_RENTED_DETAILS_FAIL';end if;
select count(*) into n from public.garage_search_vehicles('شركة التأجير',null,null,10,0,false) where id=v.id;if n<>1 then raise exception 'GARAGE_LESSOR_SEARCH_FAIL';end if;
begin perform public.garage_add_vehicle('مؤجر بلا جهة','DB-RENT-X','PX','CH-RENT-X',u::text||'/x.webp','morning','سائق',1::smallint,'truck','rented',null,null,null::date,null::date,null::smallint,null,null);raise exception 'RENTED_WITHOUT_LESSOR_ACCEPTED';exception when others then if sqlerrm='RENTED_WITHOUT_LESSOR_ACCEPTED' then raise;end if;if sqlerrm not like '%GARAGE_LESSOR_REQUIRED%' then raise;end if;end;
begin perform public.garage_add_vehicle('عقد خاطئ','DB-RENT-Y','PY','CH-RENT-Y',u::text||'/y.webp','morning','سائق',1::smallint,'truck','rented','مؤجر',null,'2026-09-09'::date,'2026-09-01'::date,null::smallint,null,null);raise exception 'INVALID_RENTAL_DATES_ACCEPTED';exception when others then if sqlerrm='INVALID_RENTAL_DATES_ACCEPTED' then raise;end if;if sqlerrm not like '%GARAGE_RENTAL_DATES_INVALID%' then raise;end if;end;
v:=public.garage_update_vehicle(v.id,'تنكر مؤجر محدث','DB-RENT-1','بغداد RENT','CHASSIS-RENT-1',null,'tanker','owned',null,null,null::date,null::date,2025::smallint,'أبيض','تحولت إلى ملك الشركة');if v.ownership_type<>'owned' or v.lessor_name is not null or v.rental_start_date is not null then raise exception 'OWNED_RENTAL_FIELDS_NOT_CLEARED';end if;
execute 'reset role';raise notice '✅ تصنيف الآليات والملكية الذاتية/المؤجرة والعقد والبحث ناجحة';end $$;
