begin;
do $$declare officer uuid:='10000000-0000-0000-0000-000000000081';superuser uuid:='10000000-0000-0000-0000-000000000082';manager uuid:='10000000-0000-0000-0000-000000000083';ituser uuid:='10000000-0000-0000-0000-000000000084';msg uuid;folder uuid;req uuid;begin
 insert into auth.users(id,email)values(officer,'archive-officer@test.iq'),(superuser,'archive-super@test.iq'),(manager,'archive-manager@test.iq'),(ituser,'archive-it@test.iq');
 insert into public.user_roles(user_id,role)values(officer,'complaints_officer'),(superuser,'super_admin'),(manager,'department_manager'),(ituser,'it_admin');
 insert into public.complaint_inbox_messages(internet_message_id,sender_email,subject,source_sector,received_at,import_status)values('archive@test','sender@test.iq','مجلد اختبار الأرشفة','karrada',now(),'ready')returning id into msg;
 perform set_config('request.jwt.claims',json_build_object('sub',officer,'role','authenticated')::text,true);set local role authenticated;
 folder:=public.complaint_archive_email(msg,'انتهاء الحاجة التشغيلية');
 if not exists(select 1 from public.complaint_inbox_messages where id=msg and archived_at is not null)then raise exception 'ARCHIVE_DID_NOT_HIDE_EMAIL';end if;
 req:=public.complaint_request_permanent_deletion(folder,'طلب حذف اختباري موثق');
 reset role;if not exists(select 1 from public.notifications where user_id=ituser and link='/it/archive')then raise exception 'IT_NOTIFICATION_MISSING';end if;
 perform set_config('request.jwt.claims',json_build_object('sub',manager,'role','authenticated')::text,true);set local role authenticated;
 if(select count(*)from public.complaint_archive_folders)>0 then raise exception 'MANAGER_RLS_LEAK';end if;
 begin perform public.complaint_decide_deletion(req,true,'غير مسموح');raise exception 'MANAGER_APPROVAL_NOT_BLOCKED';exception when others then if sqlerrm='MANAGER_APPROVAL_NOT_BLOCKED'then raise;end if;end;
 reset role;perform set_config('request.jwt.claims',json_build_object('sub',superuser,'role','authenticated')::text,true);set local role authenticated;perform public.complaint_decide_deletion(req,true,'توقيع مدير النظام');
 begin perform public.complaint_finalize_permanent_deletion(req);raise exception 'USER_FINALIZE_NOT_BLOCKED';exception when others then if sqlerrm='USER_FINALIZE_NOT_BLOCKED'then raise;end if;end;
 reset role;perform set_config('request.jwt.claims',json_build_object('role','service_role')::text,true);set local role service_role;
 begin perform public.complaint_finalize_permanent_deletion(req);raise exception 'UNCLAIMED_FINALIZE_NOT_BLOCKED';exception when others then if sqlerrm='UNCLAIMED_FINALIZE_NOT_BLOCKED'then raise;end if;end;
 perform public.complaint_claim_permanent_deletion(req);
 update public.complaint_deletion_requests set status='failed',error_message='STORAGE_TEMPORARY_FAILURE' where id=req and status='executing';
 reset role;perform set_config('request.jwt.claims',json_build_object('sub',manager,'role','authenticated')::text,true);set local role authenticated;
 begin perform public.complaint_retry_permanent_deletion(req,'محاولة غير مسموحة');raise exception 'MANAGER_RETRY_NOT_BLOCKED';exception when others then if sqlerrm='MANAGER_RETRY_NOT_BLOCKED'then raise;end if;end;
 reset role;perform set_config('request.jwt.claims',json_build_object('sub',superuser,'role','authenticated')::text,true);set local role authenticated;
 perform public.complaint_retry_permanent_deletion(req,'إعادة محاولة موقعة');
 reset role;perform set_config('request.jwt.claims',json_build_object('role','service_role')::text,true);set local role service_role;
 perform public.complaint_claim_permanent_deletion(req);perform public.complaint_finalize_permanent_deletion(req);
 if exists(select 1 from public.complaint_inbox_messages where id=msg)or not exists(select 1 from public.complaint_deletion_requests where id=req and status='executed' and attempt_count=2)then raise exception 'FINAL_DELETE_INCOMPLETE';end if;
 raise notice '✅ الأرشفة والحذف: مجلد كامل + عزل + تنبيه IT + توقيع مدير النظام + تنفيذ service_role';
end$$;
rollback;
