do $$declare ops uuid:='92000000-0000-0000-0000-000000000001';emp uuid:='92000000-0000-0000-0000-000000000002';pid uuid;gid uuid;vid uuid;n bigint;runid uuid;j jsonb;begin
 insert into auth.users(id,email)values(ops,'gps-ops@x.iq'),(emp,'gps-employee@x.iq');insert into public.user_roles(user_id,role)values(ops,'ops_room'),(emp,'employee');select id into pid from public.gps_providers where type='vendor_api' and base_url='https://track.gpslvn.iq/api' limit 1;
 perform set_config('role','service_role',false);perform public.lvn_apply_devices(pid,'[{"id":101,"name":"كابسة GPS","online":"online","timestamp":1789000000,"speed":"24.5","lat":"33.31","lng":"44.36","course":"90","power":"12.4","address":"الرياض","driver":"أحمد","distance_unit_hour":"kph","sensors":[{"name":"ACC","value":"ON"}],"services":"[{\"name\":\"Oil\",\"value\":\"100 h\"}]","device_data":{"imei":"IMEI-101","vin":"VIN-101","plate_number":"بغداد 101","object_owner":"البلدية","device_model":"LVN-X","active":"1"}},{"id":102,"name":"قلاب GPS","online":"offline","timestamp":1789000010,"speed":0,"lat":33.30,"lng":44.35,"device_data":{"imei":"IMEI-102","active":"1"}}]'::jsonb,'5000','2.5.1','full');
 select id into gid from public.gps_devices where provider_id=pid and external_id='101';if gid is null then raise exception'LVN_DEVICE_INSERT_FAIL';end if;select count(*)into n from public.gps_device_position_history where device_id=gid;if n<>1 then raise exception'LVN_HISTORY_INSERT_FAIL';end if;
 -- القراءة القديمة لا تستبدل أحدث موقع.
 perform public.lvn_apply_devices(pid,'[{"id":101,"name":"كابسة GPS","online":"online","timestamp":1788990000,"speed":99,"lat":30,"lng":40,"device_data":{"active":"1"}}]'::jsonb,'5001','2.5.1','incremental');select jsonb_build_object('speed',p.speed,'sensors',d.sensors)into j from public.gps_devices d join public.gps_device_positions p on p.device_id=d.id where d.id=gid;if(j->>'speed')::numeric<>24.5 then raise exception'LVN_OLD_POSITION_OVERWROTE_LATEST';end if;if jsonb_array_length(j->'sensors')<>1 then raise exception'LVN_INCREMENTAL_SENSOR_NORMALIZATION_FAIL';end if;insert into public.gps_vendor_events(provider_id,device_id,external_event_id,event_type,payload)values(pid,gid,'event-1','alarm','{"name":"SOS"}') ;insert into public.gps_sync_runs(provider_id,sync_type)values(pid,'full')returning id into runid;begin insert into public.gps_sync_runs(provider_id,sync_type)values(pid,'incremental');raise exception'LVN_CONCURRENT_SYNC_ACCEPTED';exception when unique_violation then null;end;update public.gps_sync_runs set status='failed',finished_at=now()where id=runid;
 execute'reset role';insert into public.garage_vehicles(vehicle_name,db_number,plate_number,chassis_number,image_path,shift,driver_name,sector_id,created_by)values('آلية GPS','DB-GPS-101','بغداد 101','CH-GPS-101',ops::text||'/gps.webp','morning','أحمد علي',1,ops)returning id into vid;
 perform set_config('role','authenticated',false);perform set_config('request.jwt.claim.sub',ops::text,false);select count(*)into n from public.gps_lvn_devices('كابسة','online','moving','unbound','',null,null,50,0);if n<>1 then raise exception'LVN_FILTERS_FAIL';end if;perform public.gps_lvn_bind_vehicle(gid,vid,'اختبار الربط');select count(*)into n from public.gps_lvn_devices(null,null,null,'bound',null,null,null,50,0)where id=gid and garage_db_number='DB-GPS-101';if n<>1 then raise exception'LVN_BINDING_FAIL';end if;select public.gps_lvn_dashboard()into j;if(j->>'total')::int<>2 or(j->>'online')::int<>1 or(j->>'bound')::int<>1 then raise exception'LVN_DASHBOARD_FAIL';end if;
 perform set_config('request.jwt.claim.sub',emp::text,false);select count(*)into n from public.gps_devices;if n<>0 then raise exception'LVN_RLS_LEAK';end if;select count(*)into n from public.gps_vendor_events;if n<>0 then raise exception'LVN_EVENT_RLS_LEAK';end if;begin perform public.gps_lvn_dashboard();raise exception'LVN_EMPLOYEE_RPC_ACCEPTED';exception when others then if sqlerrm='LVN_EMPLOYEE_RPC_ACCEPTED'then raise;end if;if sqlerrm not like'%GPS_FORBIDDEN%'then raise;end if;end;
 raise notice'✅ LVN GPS: التطبيع/المزامنة/منع القديم/الفلاتر/الربط/لوحة المؤشرات/RLS ناجحة';end$$;
