do $$declare it_u uuid:='98000000-0000-0000-0000-000000000001';other_u uuid:='99000000-0000-0000-0000-000000000001';sid uuid;nid uuid;did uuid;n bigint;begin
 perform set_config('role','authenticated',false);perform set_config('request.jwt.claim.sub',it_u::text,false);
 sid:=public.notification_register_push('https://push.example.test/admin-action/1234567890',repeat('e',65),repeat('f',24),null,'Admin Browser','windows','جهاز الإدارة');
 execute'reset role';insert into public.notifications(user_id,title,body,type,category,priority,link,dedupe_key)values(it_u,'اختبار إجراء مدقق','عملية إدارية','warning','system','high','/it/notifications','push-admin-test')returning id into nid;select id into did from public.notification_push_deliveries where notification_id=nid and subscription_id=sid;if did is null then raise exception'PUSH_ADMIN_DELIVERY_FIXTURE_FAIL';end if;
 perform set_config('role','authenticated',false);perform set_config('request.jwt.claim.sub',it_u::text,false);
 if not public.notification_push_admin_action('cancel_delivery',did,null,'إلغاء لاختبار التشغيل')then raise exception'PUSH_ADMIN_CANCEL_FAIL';end if;
 if not public.notification_push_admin_action('retry_delivery',did,null,'إعادة المحاولة بعد الفحص')then raise exception'PUSH_ADMIN_RETRY_FAIL';end if;
 if not public.notification_push_admin_action('disable_device',null,sid,'تعطيل جهاز الاختبار المتعثر')then raise exception'PUSH_ADMIN_DISABLE_FAIL';end if;
 execute'reset role';select count(*)into n from public.notification_push_admin_actions where actor_id=it_u and delivery_id=did;if n<>2 then raise exception'PUSH_ADMIN_ACTION_LOG_FAIL';end if;select count(*)into n from public.notification_push_admin_actions where actor_id=it_u and subscription_id=sid;if n<>3 then raise exception'PUSH_ADMIN_DEVICE_ACTION_LOG_FAIL';end if;select count(*)into n from public.audit_logs where table_name='notification_push_admin_actions'and actor_id=it_u;if n<3 then raise exception'PUSH_ADMIN_AUDIT_FAIL';end if;select count(*)into n from public.notification_push_subscriptions where id=sid and not is_active;if n<>1 then raise exception'PUSH_ADMIN_DEVICE_NOT_DISABLED';end if;select count(*)into n from public.notification_push_deliveries where id=did and status='cancelled';if n<>1 then raise exception'PUSH_ADMIN_PENDING_NOT_CANCELLED';end if;
 perform set_config('role','authenticated',false);perform set_config('request.jwt.claim.sub',other_u::text,false);begin perform public.notification_push_admin_action('retry_delivery',did,null,'محاولة غير مخولة');raise exception'PUSH_ADMIN_ISOLATION_ACCEPTED';exception when others then if sqlerrm='PUSH_ADMIN_ISOLATION_ACCEPTED'then raise;end if;if sqlerrm not like'%PUSH_OPERATIONS_FORBIDDEN%'then raise;end if;end;
 raise notice'✅ الجولة 16: إلغاء/إعادة محاولة/تعطيل جهاز Push مع السبب والتدقيق والعزل ناجحة';end$$;
