import{useNavigate}from'react-router'
import{useManagerProfile,useSectorSummary,useSectors}from'@features/sector'
import{SHIFT_LABELS}from'@features/sector/types'
import{Icon,type IconName}from'@components/ui/Icon/Icon'
import{LoadingSpinner}from'@components/feedback/LoadingSpinner'
type Tone='cyan'|'blue'|'emerald'|'amber'|'violet'|'rose'|'slate'|'teal'
const tones:Record<Tone,string>={cyan:'border-cyan-200 bg-cyan-50 text-cyan-800',blue:'border-blue-200 bg-blue-50 text-blue-800',emerald:'border-emerald-200 bg-emerald-50 text-emerald-800',amber:'border-amber-200 bg-amber-50 text-amber-800',violet:'border-violet-200 bg-violet-50 text-violet-800',rose:'border-rose-200 bg-rose-50 text-rose-800',slate:'border-slate-200 bg-slate-100 text-slate-800',teal:'border-teal-200 bg-teal-50 text-teal-800'}
export default function ManagerDashboard(){const navigate=useNavigate(),summary=useSectorSummary(),profile=useManagerProfile(),sectors=useSectors();const names=(profile.data?.sectors??[]).map(id=>sectors.data?.find(s=>s.id===id)?.name??`منطقة ${id}`).join(' · '),present=summary.data?.present_today??0,absent=summary.data?.absent_today??0,attendanceTotal=Math.max(1,present+absent),workers=summary.data?.workers??0
 const stats:Array<{label:string;value:string;hint:string;icon:IconName;tone:Tone}>=[{label:'عمال الفريق',value:String(workers),hint:'ضمن مناطق المسؤولية',icon:'users',tone:'cyan'},{label:'الآليات المسندة',value:String(summary.data?.vehicles??0),hint:'آليات فعالة',icon:'truck',tone:'blue'},{label:'الحضور اليوم',value:String(present),hint:`${absent} غائب`,icon:'check-square',tone:'emerald'},{label:'بلاغات الأعطال',value:String(summary.data?.breakdowns??0),hint:'بلاغ مسجل',icon:'alert-triangle',tone:'amber'},{label:'الكتب المرفوعة',value:String(summary.data?.submitted_supply??0),hint:'إلى معاون المدير',icon:'send',tone:'violet'},{label:'الصور الميدانية',value:String(summary.data?.photos??0),hint:'صورة محفوظة',icon:'photo',tone:'rose'}]
 const units:Array<{path:string;label:string;hint:string;icon:IconName;tone:Tone}>=[{path:'/manager/vehicle-trips',label:'حركة الآليات',hint:'الاستلام والمحطة والصيانة والعودة',icon:'truck',tone:'blue'},{path:'/manager/team',label:'إدارة الفريق',hint:'العمال والآليات حسب المنطقة',icon:'users',tone:'cyan'},{path:'/manager/attendance',label:'حضورية العمال',hint:'تسجيل ومراجعة الحضور اليومي',icon:'calendar',tone:'emerald'},{path:'/manager/breakdown',label:'الأعطال',hint:'بلاغ عطل والعودة إلى العمل',icon:'alert-triangle',tone:'amber'},{path:'/manager/request',label:'كتب المستلزمات',hint:'إنشاء ورفع كتاب رسمي',icon:'file-text',tone:'violet'},{path:'/manager/complaints',label:'شكاوى المواطنين',hint:'الصور قبل وبعد والمعالجة',icon:'check-square',tone:'rose'},{path:'/manager/photos',label:'الصور الميدانية',hint:'رفع وتوثيق صور العمل',icon:'photo',tone:'teal'},{path:'/manager/archive',label:'الأرشيف',hint:'الطلبات والأعطال والصور السابقة',icon:'archive-box',tone:'slate'}]
 return <section dir="rtl" className="space-y-6" data-testid="manager-dashboard"><header className="rounded-[2rem] bg-gradient-to-l from-slate-950 via-blue-950 to-cyan-800 p-7 text-white shadow-lg"><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-cyan-100">مركز قيادة القسم الميداني</span><h1 className="mt-4 text-3xl font-black">بوابة مسؤول القسم</h1><p className="mt-2 text-sm leading-7 text-cyan-100">{profile.data?`${SHIFT_LABELS[profile.data.shift]}${names?` · مناطق المسؤولية: ${names}`:''}`:'متابعة الفريق والآليات والطلبات والأعمال الميدانية'}</p></header>
 {summary.isLoading?<div className="p-8"><LoadingSpinner label="جارٍ تجهيز مؤشرات القسم…"/></div>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6" data-testid="mgr-stats">{stats.map(item=><article key={item.label} className={`rounded-3xl border p-5 shadow-sm ${tones[item.tone]}`}><span className="grid size-11 place-items-center rounded-2xl bg-white/80 shadow-sm"><Icon name={item.icon} size={21}/></span><b className="mt-4 block text-3xl text-slate-950">{item.value}</b><p className="mt-1 text-xs font-black text-slate-700">{item.label}</p><small className="mt-1 block text-[10px] opacity-70">{item.hint}</small></article>)}</div>
 <div className="grid gap-5 xl:grid-cols-3"><article className="rounded-3xl border bg-white p-6 shadow-sm xl:col-span-2"><h2 className="font-black text-slate-900">وحدات العمل</h2><p className="mt-1 text-xs text-slate-500">دخول سريع إلى العمليات اليومية المرتبطة بالقسم</p><div className="mt-5 grid gap-3 sm:grid-cols-2" data-testid="mgr-units">{units.map(unit=><button key={unit.path} onClick={()=>navigate(unit.path)} className="group flex items-center gap-4 rounded-2xl border bg-white p-4 text-right transition hover:-translate-y-0.5 hover:shadow-md"><span className={`grid size-12 shrink-0 place-items-center rounded-2xl border ${tones[unit.tone]}`}><Icon name={unit.icon} size={22}/></span><span className="min-w-0"><b className="block text-sm text-slate-900">{unit.label}</b><small className="mt-1 block text-[11px] text-slate-500">{unit.hint}</small></span></button>)}</div></article>
 <article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-black text-slate-900">حالة الحضور اليوم</h2><p className="mt-1 text-xs text-slate-500">نسبة الحضور من الفريق المسجل</p><div className="mx-auto mt-7 grid size-44 place-items-center rounded-full" style={{background:`conic-gradient(#10b981 0 ${present/attendanceTotal*100}%,#f43f5e ${present/attendanceTotal*100}% 100%)`}}><div className="grid size-28 place-items-center rounded-full bg-white text-center"><div><b className="text-2xl">{Math.round(present/attendanceTotal*100)}%</b><p className="text-[10px] text-slate-500">نسبة الحضور</p></div></div></div><div className="mt-6 grid grid-cols-2 gap-3 text-center text-xs"><div className="rounded-2xl bg-emerald-50 p-3 text-emerald-800"><b className="text-lg">{present}</b><p>حاضر</p></div><div className="rounded-2xl bg-rose-50 p-3 text-rose-800"><b className="text-lg">{absent}</b><p>غائب</p></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] text-slate-500"><span>تغطية سجلات الفريق</span><b>{present+absent}/{workers}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,(present+absent)/Math.max(1,workers)*100)}%`}}/></div></div></article></div></>}
 </section>}
