import{fireEvent,render,screen}from'@testing-library/react';import{MemoryRouter}from'react-router';import{beforeEach,describe,expect,it,vi}from'vitest';import ProcessingPage from'../../../src/portals/complaints/pages/Processing/ProcessingPage'
const state=vi.hoisted(()=>({missingAfter:false}));const review=vi.fn();const base={complaintId:'c1',referenceNo:'CMP-1',complaintStatus:'quality_review',sector:'karrada',title:'تراكم نفايات',municipalCenter:'الكرادة',neighborhood:'901',alley:'1',locationText:null,ocrText:null,assignedTo:'m1',managerNotes:null,reviewerNotes:null,receivedAt:'2026-09-06T08:00:00Z',inboxMessageId:'mail1',ticketName:'رفع نفايات شارع 7'};const items=[{...base,id:'i1',sequenceNo:1,status:'processed'},{...base,id:'i2',sequenceNo:2,status:'quality_review',title:'أنقاض',alley:'2'},{...base,id:'i3',complaintId:'c2',referenceNo:'CMP-2',sequenceNo:1,status:'approved',ticketName:'تذكرة معتمدة',assignedTo:'m2'}]
vi.mock('@features/complaints',()=>({useComplaintItems:()=>({data:items,isLoading:false}),useComplaintManagers:()=>({data:[{userId:'m1',fullName:'المسؤول أحمد'},{userId:'m2',fullName:'المسؤول علي'}]}),useComplaintItemsMedia:(ids:string[])=>({data:ids.flatMap((id,index)=>[{id:`b${id}`,itemId:id,kind:'before',url:`before-${id}.jpg`,name:`قبل ${index}`},...(state.missingAfter&&id==='i2'?[]:[{id:`a${id}`,itemId:id,kind:'after',url:`after-${id}.jpg`,name:`بعد ${index}`}])])}),useReviewComplaintAssignmentTicket:()=>({mutate:review,isPending:false})}))
const view=()=>render(<MemoryRouter><ProcessingPage/></MemoryRouter>);beforeEach(()=>{review.mockClear();state.missingAfter=false})
describe('تدقيق تذاكر الشكاوى كاملة',()=>{
 it('يجمع صور البريد والمسؤول في تذكرة واحدة ويعرض جميع الأزواج',()=>{view();expect(screen.getAllByText('رفع نفايات شارع 7')).toHaveLength(2);expect(screen.getByText('2 صورة')).toBeInTheDocument();expect(screen.getByAltText('قبل 0')).toHaveAttribute('src','before-i1.jpg');expect(screen.getByAltText('بعد 1')).toHaveAttribute('src','after-i2.jpg');expect(screen.getByText(/راجع 2 معالجة/)).toBeInTheDocument()})
 it('يمنع الاعتماد إذا نقصت صورة بعد لأي موقع',()=>{state.missingAfter=true;view();expect(screen.getByRole('alert')).toHaveTextContent('1 موقع لا يملك زوج صور');expect(screen.getByRole('button',{name:'اعتماد التذكرة كاملة'})).toBeDisabled()})
 it('يفصل المعتمدة عن قيد التدقيق بواسطة مرشحات واضحة',()=>{view();fireEvent.click(screen.getByRole('button',{name:/معتمدة/}));expect(screen.getAllByText('تذكرة معتمدة').length).toBeGreaterThan(0);expect(screen.queryByText('اعتماد التذكرة كاملة')).not.toBeInTheDocument();expect(screen.getByText(/جاهزة للتقرير/)).toBeInTheDocument()})
 it('يعتمد التذكرة كاملة باستدعاء ذري واحد',()=>{view();fireEvent.change(screen.getByPlaceholderText('الملاحظة إلزامية عند الإرجاع'),{target:{value:'تم فحص جميع الصور'}});fireEvent.click(screen.getByText('اعتماد التذكرة كاملة'));expect(review).toHaveBeenCalledWith({complaintId:'c1',managerId:'m1',approved:true,note:'تم فحص جميع الصور'},expect.any(Object))})
 it('لا يسمح بإرجاع التذكرة بلا سبب ثم يعيدها كاملة',()=>{view();const button=screen.getByText('إعادة التذكرة كاملة');expect(button).toBeDisabled();fireEvent.change(screen.getByPlaceholderText('الملاحظة إلزامية عند الإرجاع'),{target:{value:'الصورة الثانية غير مطابقة'}});fireEvent.click(button);expect(review).toHaveBeenCalledWith(expect.objectContaining({complaintId:'c1',managerId:'m1',approved:false,note:'الصورة الثانية غير مطابقة'}),expect.any(Object))})
})
