import{fireEvent,render,screen}from'@testing-library/react';import{MemoryRouter,Route,Routes}from'react-router';import{beforeAll,beforeEach,describe,expect,it,vi}from'vitest'
import AssignedComplaintsPage from'../../../src/portals/manager/pages/Complaints/AssignedComplaintsPage';import ComplaintTicketPage from'../../../src/portals/manager/pages/Complaints/ComplaintTicketPage'
const complete=vi.fn();const start=vi.fn();const base={complaintId:'c1',referenceNo:'CMP-1',complaintStatus:'assigned',sector:'karrada',title:'تراكم نفايات',municipalCenter:'بلدية الكرادة',neighborhood:'901',alley:'2',locationText:null,ocrText:null,assignedTo:'u1',status:'in_progress',managerNotes:null,reviewerNotes:null,receivedAt:'2026-09-06T08:00:00Z',inboxMessageId:'m1',ticketName:'حملة رفع النفايات'};const items=[{...base,id:'i1',sequenceNo:1},{...base,id:'i2',sequenceNo:2,title:'أنقاض',neighborhood:'902',alley:'3'}]
vi.mock('@components/ui',()=>({CameraCapture:()=>null}))
vi.mock('@features/complaints',()=>({useComplaintItems:()=>({data:items,isLoading:false}),useManagerComplaintTicket:()=>({data:items,isLoading:false,isError:false,refetch:vi.fn()}),useComplaintItemsMedia:()=>({data:[{id:'b1',itemId:'i1',kind:'before',url:'one.jpg',name:'one.jpg',mimeType:'image/jpeg',mediaCode:'B1',displayOrder:1},{id:'b2',itemId:'i2',kind:'before',url:'two.jpg',name:'two.jpg',mimeType:'image/jpeg',mediaCode:'B2',displayOrder:1}]}),useStartComplaintAssignmentTicket:()=>({mutate:start,isPending:false}),useCompleteComplaintAssignmentTicket:()=>({mutate:complete,isPending:false})}))
beforeAll(()=>vi.stubGlobal('URL',{...URL,createObjectURL:vi.fn((file:File)=>`blob:${file.name}`),revokeObjectURL:vi.fn()}));beforeEach(()=>{complete.mockClear();start.mockClear();items.forEach(item=>{item.status='in_progress'})})
function list(){return render(<MemoryRouter><AssignedComplaintsPage/></MemoryRouter>)}function detail(){return render(<MemoryRouter initialEntries={['/manager/complaints/c1']}><Routes><Route path="/manager/complaints/:complaintId" element={<ComplaintTicketPage/>}/></Routes></MemoryRouter>)}
describe('تذاكر مسؤول القسم المجمعة',()=>{
 it('يجمع صور البريد والمسؤول في بطاقة واحدة تعرض الاسم والنوع والتاريخ',()=>{list();expect(screen.getAllByText('حملة رفع النفايات')).toHaveLength(1);expect(screen.getByText((_,el)=>el?.tagName==='SPAN'&&el.textContent?.includes('صورة تلكؤ')===true)).toHaveTextContent('2');expect(screen.getByText('تراكم نفايات')).toBeInTheDocument();expect(screen.getByText('أنقاض')).toBeInTheDocument();expect(screen.getByRole('link',{name:'فتح التذكرة'})).toHaveAttribute('href','/manager/complaints/c1')})
 it('يبدأ جميع عناصر التذكرة باستدعاء واحد',()=>{items.forEach(item=>{item.status='assigned'});detail();fireEvent.click(screen.getByRole('button',{name:'بدء معالجة التذكرة'}));expect(start).toHaveBeenCalledWith('c1',expect.any(Object));items.forEach(item=>{item.status='in_progress'})})
 it('تعرض صفحة التذكرة زوجاً مستقلاً لكل صورة مع المحلة والزقاق دون GPS',()=>{detail();expect(screen.getByAltText('صورة التلكؤ 1')).toHaveAttribute('src','one.jpg');expect(screen.getByAltText('صورة التلكؤ 2')).toHaveAttribute('src','two.jpg');expect(screen.getByText('901')).toBeInTheDocument();expect(screen.getByText('902')).toBeInTheDocument();expect(screen.queryByText(/الموقع الحالي|GPS/)).not.toBeInTheDocument();expect(screen.getAllByText(/أضف صورة معالجة لهذا التلكؤ/)).toHaveLength(2)})
 it('يفرض صورتين بالضبط ثم يرسل الربط واحداً لواحد في عملية واحدة',()=>{detail();const input=screen.getByLabelText(/رفع 2 صور دفعة واحدة/);const first=new File(['a'],'after-a.jpg',{type:'image/jpeg'});fireEvent.change(input,{target:{files:[first]}});expect(screen.getByRole('status')).toHaveTextContent('اختر 2 صورة بالضبط');const second=new File(['b'],'after-b.jpg',{type:'image/jpeg'});fireEvent.change(input,{target:{files:[first,second]}});fireEvent.click(screen.getByRole('button',{name:/إرسال 2 معالجة/}));expect(complete).toHaveBeenCalledWith(expect.objectContaining({complaintId:'c1',files:[expect.objectContaining({itemId:'i1',file:first}),expect.objectContaining({itemId:'i2',file:second})]}),expect.any(Object))})
 it('يبدل صور المعالجة بأزرار متاحة للموبايل',()=>{detail();const first=new File(['a'],'after-a.jpg',{type:'image/jpeg'});const second=new File(['b'],'after-b.jpg',{type:'image/jpeg'});fireEvent.change(screen.getByLabelText(/رفع 2 صور دفعة واحدة/),{target:{files:[first,second]}});fireEvent.click(screen.getByRole('button',{name:'نقل صورة المعالجة 1 إلى الموقع التالي'}));expect(screen.getByAltText('صورة المعالجة 1')).toHaveAttribute('src','blob:after-b.jpg');fireEvent.click(screen.getByRole('button',{name:/إرسال 2 معالجة/}));expect(complete).toHaveBeenCalledWith(expect.objectContaining({files:[expect.objectContaining({itemId:'i1',file:second}),expect.objectContaining({itemId:'i2',file:first})]}),expect.any(Object))})
 it('يبدل صور المعالجة بالسحب قبل تثبيت الاقتران',()=>{const{container}=detail();const first=new File(['a'],'after-a.jpg',{type:'image/jpeg'});const second=new File(['b'],'after-b.jpg',{type:'image/jpeg'});fireEvent.change(screen.getByLabelText(/رفع 2 صور دفعة واحدة/),{target:{files:[first,second]}});const slots=container.querySelectorAll('[draggable="true"]');expect(slots).toHaveLength(2);fireEvent.dragStart(slots[0]!);fireEvent.dragOver(slots[1]!);fireEvent.drop(slots[1]!);expect(screen.getByAltText('صورة المعالجة 1')).toHaveAttribute('src','blob:after-b.jpg');fireEvent.click(screen.getByRole('button',{name:/إرسال 2 معالجة/}));expect(complete).toHaveBeenCalledWith(expect.objectContaining({files:[expect.objectContaining({itemId:'i1',file:second}),expect.objectContaining({itemId:'i2',file:first})]}),expect.any(Object))})
})
