import{useMemo,useState,type ReactNode}from'react'
import{ArrowLeftRight,CheckCircle2,Clock3,Filter,FolderOpen,History,MapPin,Search,Truck}from'lucide-react'
import{useStationConfirmArrival,useStationDispatchVehicle,useStationMovementDays,useStationVisitsForDay}from'@features/vehicle-operations/hooks'
import type{StationVisit}from'@sdk/vehicle-operations.sdk'

const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat('ar-IQ',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Baghdad'}).format(new Date(value)):'—'
const minutes=(value:number|null)=>value===null?'—':value<60?`${value} د`:`${Math.floor(value/60)} س ${value%60} د`
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baghdad'}).format(new Date())
const statusLabel:Record<StationVisit['status'],string>={in_transit:'في الطريق',at_station:'داخل المحطة',dispatched:'غادرت المحطة'}
const statusTone:Record<StationVisit['status'],string>={in_transit:'bg-amber-100 text-amber-800',at_station:'bg-orange-100 text-orange-800',dispatched:'bg-emerald-100 text-emerald-800'}

export default function StationVehicleMovementsPage(){
 const[selectedDay,setSelectedDay]=useState(today),[search,setSearch]=useState(''),[status,setStatus]=useState<''|StationVisit['status']>(''),[sectorId,setSectorId]=useState('')
 const days=useStationMovementDays(),visits=useStationVisitsForDay(selectedDay,{search,status:status||undefined,sectorId:sectorId?Number(sectorId):undefined}),arrive=useStationConfirmArrival(),send=useStationDispatchVehicle()
 const[target,setTarget]=useState<{row:StationVisit;action:'arrive'|'work_site'|'garage'}|null>(null),[notes,setNotes]=useState('')
 const rows=useMemo(()=>visits.data??[],[visits.data])
 const sectors=useMemo(()=>[...new Map(rows.map(row=>[row.sector_id,row.area_name])).entries()],[rows])
 const submit=()=>{if(!target)return;const done=()=>{setTarget(null);setNotes('')};if(target.action==='arrive')arrive.mutate({legId:target.row.visit_id,notes:notes.trim()||undefined},{onSuccess:done});else send.mutate({departureId:target.row.departure_id,destination:target.action,notes:notes.trim()||undefined},{onSuccess:done})}
 const open=rows.filter(row=>row.status!=='dispatched').length,totalStay=rows.reduce((sum,row)=>sum+(row.stay_minutes??0),0)
 return <section dir="rtl" className="space-y-5" data-testid="station-movements-page">
  <header className="rounded-3xl bg-gradient-to-l from-slate-950 via-orange-950 to-orange-700 p-6 text-white shadow-xl"><p className="flex items-center gap-2 text-xs text-orange-100"><Truck size={16}/>سجل تشغيلي مباشر وغير قابل للاستبدال</p><h1 className="mt-2 text-2xl font-black">حركة وزيارات الآليات إلى المحطة</h1><p className="mt-1 text-sm text-orange-100">كل زيارة مستقلة بوقت الوصول والمغادرة ومدة البقاء والوجهة التالية.</p></header>

  <div className="flex gap-3 overflow-x-auto pb-2">{(days.data??[]).map(day=><button key={day.visit_day} data-testid={`station-day-${day.visit_day}`} onClick={()=>setSelectedDay(day.visit_day)} className={`min-w-44 rounded-2xl border p-4 text-right transition ${selectedDay===day.visit_day?'border-orange-500 bg-orange-50 shadow':'bg-white'}`}><span className="flex items-center gap-2 text-sm font-black"><FolderOpen size={17} className="text-orange-600"/>{new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeZone:'Asia/Baghdad'}).format(new Date(`${day.visit_day}T12:00:00Z`))}</span><span className="mt-2 block text-[11px] text-slate-500">{day.visit_count} زيارة · {day.vehicle_count} رحلة</span><span className={`mt-1 block text-[11px] font-bold ${day.open_count?'text-amber-700':'text-emerald-700'}`}>{day.open_count?`${day.open_count} حالة مفتوحة`:'مكتمل'}</span></button>)}</div>

  <div className="grid gap-3 sm:grid-cols-3"><Stat label="زيارات اليوم المختار" value={rows.length} icon={<History/>}/><Stat label="الحالات المفتوحة" value={open} icon={<ArrowLeftRight/>}/><Stat label="إجمالي البقاء" value={minutes(totalStay)} icon={<Clock3/>}/></div>

  <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><label className="relative"><Search className="absolute right-3 top-3 text-slate-400" size={17}/><input aria-label="بحث الزيارات" value={search} onChange={e=>setSearch(e.target.value)} className="h-11 w-full rounded-xl border pr-10 pl-3 text-sm" placeholder="DB أو الآلية أو السائق"/></label><label className="relative"><Filter className="absolute right-3 top-3 text-slate-400" size={17}/><select aria-label="فلتر الحالة" value={status} onChange={e=>setStatus(e.target.value as ''|StationVisit['status'])} className="h-11 w-full rounded-xl border pr-10 pl-3 text-sm"><option value="">كل الحالات</option><option value="in_transit">في الطريق</option><option value="at_station">داخل المحطة</option><option value="dispatched">غادرت</option></select></label><select aria-label="فلتر المنطقة" value={sectorId} onChange={e=>setSectorId(e.target.value)} className="h-11 rounded-xl border px-3 text-sm"><option value="">كل المناطق</option>{sectors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>

  {visits.isLoading?<p className="rounded-3xl border bg-white p-12 text-center text-sm text-slate-500">جارٍ تحميل سجل الزيارات…</p>:<div className="grid gap-4 lg:grid-cols-2">{rows.map(row=><VisitCard key={row.visit_id} row={row} onAction={action=>{setTarget({row,action});setNotes('')}}/>)}</div>}
  {!visits.isLoading&&!rows.length&&<p className="rounded-3xl border bg-white p-12 text-center text-sm text-slate-500">لا توجد زيارات مطابقة في اليوم المختار.</p>}

  {target&&<div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-3xl bg-white p-6"><h2 className="text-lg font-black">تأكيد حركة الآلية DB {target.row.db_number}</h2><p className="mt-2 text-xs text-slate-500">الزيارة رقم {target.row.visit_number} · {target.action==='arrive'?'تأكيد الوصول':target.action==='work_site'?'العودة لموقع العمل':'الإرسال إلى الكراج'}</p><textarea data-testid="station-action-notes" value={notes} onChange={e=>setNotes(e.target.value)} rows={3} maxLength={1000} className="mt-4 w-full rounded-xl border p-3" placeholder="ملاحظات اختيارية"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setTarget(null)} className="h-11 rounded-xl border">إلغاء</button><button data-testid="confirm-station-action" onClick={submit} disabled={arrive.isPending||send.isPending} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-orange-700 font-black text-white disabled:opacity-40"><CheckCircle2 size={16}/>تأكيد وإبلاغ</button></div></div></div>}
 </section>
}

function VisitCard({row,onAction}:{row:StationVisit;onAction:(action:'arrive'|'work_site'|'garage')=>void}){return <article className="rounded-3xl border bg-white p-5 shadow-sm" data-testid={`station-visit-${row.visit_id}`}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b className="rounded-lg bg-slate-900 px-2 py-1 text-xs text-white">DB {row.db_number}</b><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusTone[row.status]}`}>{statusLabel[row.status]}</span><span className="text-[10px] font-bold text-slate-400">الزيارة #{row.visit_number}</span></div><h2 className="mt-3 font-black">{row.vehicle_name}</h2><p className="mt-1 text-xs text-slate-500">{row.driver_name} · {row.shift}</p></div><ArrowLeftRight className="text-orange-600"/></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Info label="منطقة العمل" value={row.area_name} icon={<MapPin/>}/><Info label="مسؤول القسم" value={row.manager_name} icon={<Truck/>}/><Info label="غادرت للمحطة" value={dateTime(row.inbound_departed_at)} icon={<Clock3/>}/><Info label="وصلت المحطة" value={dateTime(row.arrived_at)} icon={<CheckCircle2/>}/><Info label="مدة الطريق" value={minutes(row.transit_minutes)} icon={<Clock3/>}/><Info label="مدة البقاء" value={minutes(row.stay_minutes)} icon={<Clock3/>}/></div>{row.dispatched_at&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-800">غادرت {dateTime(row.dispatched_at)} إلى {row.outbound_destination==='garage'?'الكراج':'موقع العمل'}.</p>}<Notes row={row}/>{row.status==='in_transit'&&<button data-testid={`station-arrive-${row.visit_id}`} onClick={()=>onAction('arrive')} className="mt-4 h-11 w-full rounded-xl bg-emerald-700 font-black text-white">تأكيد وصول الآلية إلى المحطة</button>}{row.status==='at_station'&&<div className="mt-4 grid grid-cols-2 gap-2"><button data-testid={`station-work-${row.visit_id}`} onClick={()=>onAction('work_site')} className="h-11 rounded-xl bg-cyan-700 text-xs font-black text-white">عودة إلى موقع العمل</button><button data-testid={`station-garage-${row.visit_id}`} onClick={()=>onAction('garage')} className="h-11 rounded-xl bg-slate-800 text-xs font-black text-white">إرسال إلى الكراج</button></div>}</article>}
function Notes({row}:{row:StationVisit}){const notes=[['الإرسال',row.inbound_notes],['الوصول',row.arrival_notes],['المغادرة',row.dispatch_notes]].filter(([,value])=>value);return notes.length?<div className="mt-3 space-y-1 rounded-xl bg-slate-50 p-3 text-[11px] text-slate-600">{notes.map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>:null}
function Info({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-1 text-[10px] text-slate-400">{icon}{label}</span><b className="mt-1 block">{value}</b></div>}
function Stat({label,value,icon}:{label:string;value:string|number;icon:ReactNode}){return <div className="rounded-2xl border bg-white p-4"><span className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</span><b className="mt-2 block text-xl">{value}</b></div>}
