import{useMemo,useState}from'react'
import{Link}from'react-router'
import JSZip from'jszip'
import{BookOpen,CalendarDays,CheckCircle2,ChevronLeft,FileArchive,Images,MapPin,Tag,Workflow}from'lucide-react'
import{useComplaintItems,useComplaintItemsMedia,type ManagerComplaintTicket}from'@features/complaints'
import{baghdadDateKey}from'@features/complaints/lib/baghdad-date'

const active=['assigned','in_progress','returned']
function ticketStatus(items:ManagerComplaintTicket['items']):ManagerComplaintTicket['status']{if(items.some(item=>item.status==='returned'))return'returned';if(items.some(item=>item.status==='in_progress'))return'in_progress';if(items.some(item=>item.status==='assigned'))return'ready';if(items.every(item=>item.status==='approved'))return'approved';return'review'}
const labels:Record<ManagerComplaintTicket['status'],string>={ready:'جاهزة للمعالجة',in_progress:'قيد المعالجة',review:'بانتظار التدقيق',approved:'معتمدة',returned:'معادة للتصحيح'}
export default function AssignedComplaintsPage(){
 const[date,setDate]=useState(baghdadDateKey());const{data:items=[],isLoading}=useComplaintItems(true,date);const[filter,setFilter]=useState<'active'|'completed'|'all'>('active');const[selected,setSelected]=useState<string[]>([]);const[downloading,setDownloading]=useState(false);const[error,setError]=useState('')
 const tickets=useMemo(()=>{const groups=new Map<string,ManagerComplaintTicket>();for(const item of items){const current=groups.get(item.complaintId);if(current){current.items.push(item);if(item.title&&!current.types.includes(item.title))current.types.push(item.title);current.status=ticketStatus(current.items)}else groups.set(item.complaintId,{complaintId:item.complaintId,referenceNo:item.referenceNo,name:item.ticketName,receivedAt:item.receivedAt,sector:item.sector,items:[item],types:item.title?[item.title]:[],status:ticketStatus([item])})}return[...groups.values()].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))},[items])
 const shown=tickets.filter(ticket=>filter==='all'||(filter==='active'?ticket.items.some(item=>active.includes(item.status)):ticket.items.every(item=>!active.includes(item.status))));const selectedItems=tickets.filter(ticket=>selected.includes(ticket.complaintId)).flatMap(ticket=>ticket.items.map(item=>item.id));const{data:media=[]}=useComplaintItemsMedia(selectedItems)
 const toggleAll=()=>setSelected(old=>shown.length&&shown.every(ticket=>old.includes(ticket.complaintId))?old.filter(id=>!shown.some(ticket=>ticket.complaintId===id)):[...new Set([...old,...shown.map(ticket=>ticket.complaintId)])])
 async function download(){setDownloading(true);setError('');try{const zip=new JSZip();const before=media.filter(value=>value.kind==='before');await Promise.all(before.map(async value=>{const response=await fetch(value.url);if(!response.ok)throw new Error(`تعذر تنزيل ${value.mediaCode}`);const item=items.find(row=>row.id===value.itemId);zip.file(`${item?.referenceNo}-${item?.sequenceNo}-${value.mediaCode}-${value.name}`,await response.blob())}));const blob=await zip.generateAsync({type:'blob'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`complaint-tickets-${new Date().toISOString().slice(0,10)}.zip`;anchor.click();URL.revokeObjectURL(url)}catch(value){setError(value instanceof Error?value.message:'تعذر تجهيز الصور')}finally{setDownloading(false)}}
 return <section className="space-y-6" dir="rtl">
  <header className="overflow-hidden rounded-3xl bg-gradient-to-l from-slate-950 via-blue-950 to-teal-900 p-6 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-5"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs"><Workflow size={14}/>تذاكر المعالجة الميدانية</span><h1 className="mt-3 text-2xl font-black">الشكاوى المسندة إليّ</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-blue-100">كل بطاقة تمثل بريداً واحداً وما أُسند إليك منه. افتح التذكرة لمطابقة كل صورة تلكؤ بصورة معالجة واحدة.</p></div><Link to="/manager/complaints-guidance" className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 font-bold text-blue-950 shadow"><BookOpen size={19}/>دليل العمل</Link></div><div className="mt-6 grid grid-cols-3 gap-2 sm:max-w-xl"><Stat label="تحتاج إجراء" value={tickets.filter(ticket=>ticket.items.some(item=>active.includes(item.status))).length}/><Stat label="قيد التنفيذ" value={tickets.filter(ticket=>ticket.status==='in_progress').length}/><Stat label="منجزة/تدقيق" value={tickets.filter(ticket=>ticket.items.every(item=>!active.includes(item.status))).length}/></div></header>
  <div className="sticky top-2 z-10 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 rounded-xl border bg-white px-3 text-xs font-bold"><CalendarDays size={15}/><input aria-label="تاريخ التذاكر" type="date" value={date} onChange={event=>{setDate(event.target.value);setSelected([])}} className="py-2 outline-none"/></label>{([['active','تحتاج إجراء'],['completed','المنجزة والتدقيق'],['all','الكل']]as const).map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`rounded-xl px-3 py-2 text-xs font-bold ${filter===value?'bg-blue-700 text-white':'bg-slate-100 text-slate-600'}`}>{label}</button>)}</div><div className="flex flex-wrap gap-2"><button onClick={toggleAll} disabled={!shown.length} className="rounded-xl border px-3 py-2 text-xs font-bold disabled:opacity-40">تحديد التذاكر الظاهرة</button><button onClick={()=>void download()} disabled={!selected.length||!media.length||downloading} className="flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><FileArchive size={16}/>{downloading?'تجهيز الملف…':`تنزيل صور ${selected.length} تذكرة`}</button></div></div>{error&&<p role="alert" className="mt-2 text-xs font-bold text-red-700">{error}</p>}</div>
  {isLoading&&<div className="h-56 animate-pulse rounded-3xl bg-slate-100"/>}{!isLoading&&!shown.length&&<div className="rounded-3xl border border-dashed bg-white p-14 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={40}/><h2 className="mt-3 font-black">لا توجد تذاكر في هذا القسم</h2></div>}
  <div className="grid gap-4">{shown.map(ticket=><article key={ticket.complaintId} className={`rounded-3xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${selected.includes(ticket.complaintId)?'border-blue-500 ring-2 ring-blue-100':'border-slate-200'}`}><div className="flex items-start gap-4"><input type="checkbox" checked={selected.includes(ticket.complaintId)} onChange={()=>setSelected(old=>old.includes(ticket.complaintId)?old.filter(id=>id!==ticket.complaintId):[...old,ticket.complaintId])} aria-label={`تحديد ${ticket.referenceNo}`} className="mt-2 size-5"/><Link to={`/manager/complaints/${ticket.complaintId}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-blue-700">{ticket.referenceNo}</p><h2 className="mt-1 text-lg font-black text-slate-950">{ticket.name}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${ticket.status==='returned'?'bg-amber-100 text-amber-900':ticket.status==='approved'?'bg-emerald-100 text-emerald-800':'bg-blue-50 text-blue-800'}`}>{labels[ticket.status]}</span></div><div className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-3"><span className="flex items-center gap-2"><Images size={17} className="text-rose-600"/><b>{ticket.items.length}</b> صورة تلكؤ</span><span className="flex items-center gap-2"><CalendarDays size={17}/>{new Date(ticket.receivedAt).toLocaleDateString('ar-IQ')}</span><span className="flex items-center gap-2"><MapPin size={17}/>{ticket.sector==='karrada'?'بلدية الكرادة':'بلدية الزعفرانية'}</span></div><div className="mt-3 flex flex-wrap items-center gap-2"><Tag size={15} className="text-slate-400"/>{ticket.types.length?ticket.types.map(type=><span key={type} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{type}</span>):<span className="text-xs text-slate-400">لم يحدد نوع التلكؤ</span>}</div></Link><Link to={`/manager/complaints/${ticket.complaintId}`} aria-label="فتح التذكرة" className="rounded-2xl bg-blue-50 p-3 text-blue-700"><ChevronLeft/></Link></div></article>)}</div>
 </section>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/10 p-3 text-center"><strong className="text-2xl">{value}</strong><p className="text-[11px] text-blue-100">{label}</p></div>}
