import { useState } from 'react'
import {
  useComplaintContacts, useComplaintSettings, useSaveComplaintContact,
  useSaveComplaintSetting, type ComplaintContact, type ComplaintSetting,
} from '@features/complaints'

type ContactDraft=Omit<ComplaintContact,'id'>&{id?:string}
const empty:ContactDraft={name:'',email:'',sector:null,kind:'recipient',isActive:true}
export default function SettingsPage(){
 const{data:contacts=[],isLoading}=useComplaintContacts();const{data:settings=[]}=useComplaintSettings();const save=useSaveComplaintContact();const[draft,setDraft]=useState<ContactDraft>(empty);const[message,setMessage]=useState('')
 const submit=()=>{if(!draft.name.trim()||!draft.email.trim())return setMessage('الاسم والبريد مطلوبان.');save.mutate(draft,{onSuccess:()=>{setMessage(draft.id?'تم تحديث جهة التواصل.':'تمت إضافة جهة التواصل.');setDraft(empty)},onError:()=>setMessage('تعذر حفظ الجهة. تحقق من البريد والصلاحية.')})}
 return <section className="space-y-5" dir="rtl"><header><h1 className="text-2xl font-bold">إعدادات الصفحات والتواصل</h1><p className="text-sm text-slate-500">إدارة To وCC وقواعد المرسلين. التعطيل يحفظ السجل ولا يحذف الجهة. مفاتيح Mailgun تبقى في أسرار الخادم.</p></header>
 {message&&<p aria-live="polite" className="rounded-lg bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}
 <form onSubmit={e=>{e.preventDefault();submit()}} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-2 xl:grid-cols-6"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="اسم الجهة" className="rounded-lg border p-2"/><input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})} placeholder="البريد" className="rounded-lg border p-2"/><select value={draft.sector??''} onChange={e=>setDraft({...draft,sector:(e.target.value||null) as ContactDraft['sector']})} className="rounded-lg border p-2"><option value="">كل القواطع</option><option value="karrada">الكرادة</option><option value="zaafaraniya">الزعفرانية</option></select><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as ContactDraft['kind']})} className="rounded-lg border p-2"><option value="recipient">To — مستلم</option><option value="cc">CC — نسخة</option><option value="sender_rule">مرسل مسموح</option></select><button disabled={save.isPending} className="rounded-lg bg-rose-700 p-2 font-bold text-white disabled:opacity-50">{draft.id?'حفظ التعديل':'إضافة جهة'}</button>{draft.id&&<button type="button" onClick={()=>setDraft(empty)} className="rounded-lg border p-2 font-bold">إلغاء</button>}</form>
 <div className="overflow-x-auto rounded-xl border bg-white">{isLoading?<p className="p-6 text-center">جارٍ التحميل…</p>:!contacts.length?<p className="p-6 text-center text-slate-500">لا توجد جهات تواصل بعد.</p>:<table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">الجهة</th><th className="p-3 text-right">البريد</th><th className="p-3">القاطع</th><th className="p-3">الاستخدام</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{contacts.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-bold">{c.name}</td><td className="p-3" dir="ltr">{c.email}</td><td className="p-3 text-center">{c.sector==='karrada'?'الكرادة':c.sector==='zaafaraniya'?'الزعفرانية':'عام'}</td><td className="p-3 text-center">{c.kind==='recipient'?'To':c.kind==='cc'?'CC':'مرسل'}</td><td className="p-3 text-center">{c.isActive?'مفعّل':'معطّل'}</td><td className="p-3 text-center"><button onClick={()=>setDraft(c)} className="ml-2 font-bold text-blue-700">تعديل</button><button onClick={()=>save.mutate({...c,isActive:!c.isActive},{onSuccess:()=>setMessage(c.isActive?'تم تعطيل الجهة دون حذفها.':'تم تفعيل الجهة.')})} className="font-bold text-rose-700">{c.isActive?'تعطيل':'تفعيل'}</button></td></tr>)}</tbody></table>}</div>
 <div className="grid gap-3 md:grid-cols-2">{settings.map(setting=><SettingCard key={setting.key} setting={setting}/>)}</div></section>
}
function SettingCard({setting}:{setting:ComplaintSetting}){const save=useSaveComplaintSetting();const[value,setValue]=useState(JSON.stringify(setting.value,null,2));const[error,setError]=useState('');return <article className="rounded-xl border bg-white p-4"><strong>{setting.key}</strong><p className="text-xs text-slate-500">{setting.description}</p><textarea dir="ltr" value={value} onChange={e=>setValue(e.target.value)} className="mt-3 min-h-32 w-full rounded border p-2 font-mono text-xs"/>{error&&<p className="text-xs text-red-700">{error}</p>}<button onClick={()=>{try{save.mutate({...setting,value:JSON.parse(value) as Record<string,unknown>},{onSuccess:()=>setError('تم الحفظ')});setError('')}catch{setError('صيغة JSON غير صحيحة')}}} className="mt-2 rounded bg-slate-800 px-3 py-2 text-sm font-bold text-white">حفظ الإعداد</button></article>}
