import { useEffect, useState } from 'react'
import { ImagePlus, Save, X } from 'lucide-react'
import { useUpdateGarageVehicle } from '@features/central-garage/hooks'
import { garageVehicleEditSchema } from '@features/central-garage/schemas'
import type { GarageVehicle } from '@features/central-garage/types'

const inputClass='h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100'
export function EditVehicleDialog({vehicle,onClose}:{vehicle:GarageVehicle;onClose:()=>void}){
  const[form,setForm]=useState({vehicleName:vehicle.vehicleName,dbNumber:vehicle.dbNumber,plateNumber:vehicle.plateNumber,chassisNumber:vehicle.chassisNumber,image:undefined as File|undefined});const[errors,setErrors]=useState<Record<string,string>>({});const[preview,setPreview]=useState<string|null>(null);const updateVehicle=useUpdateGarageVehicle()
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
  const update=(key:string,value:string)=>{setForm(old=>({...old,[key]:value}));setErrors(old=>({...old,[key]:''}))}
  const choose=(file?:File)=>{if(preview)URL.revokeObjectURL(preview);setForm(old=>({...old,image:file}));setPreview(file?URL.createObjectURL(file):null);setErrors(old=>({...old,image:''}))}
  const submit=(event:React.FormEvent)=>{event.preventDefault();const parsed=garageVehicleEditSchema.safeParse(form);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return}updateVehicle.mutate({id:vehicle.id,...parsed.data},{onSuccess:onClose})}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label="تعديل بيانات الآلية"><form onSubmit={submit} className="mx-auto my-8 w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-black">تعديل بيانات الآلية</h2><p className="mt-1 text-xs text-slate-500">تغيير السائق والشفت والموقع يتم من زر تغيير الانطلاقية حفاظاً على السجل.</p></div><button type="button" aria-label="إغلاق" onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="صورة الآلية" error={errors.image} wide><label className="flex min-h-36 cursor-pointer items-center justify-center overflow-hidden rounded-2xl border-2 border-dashed border-cyan-200 bg-cyan-50/50">{preview||vehicle.imageUrl?<img src={preview??vehicle.imageUrl} alt="معاينة صورة الآلية" className="h-44 w-full object-cover"/>:<span className="flex flex-col items-center gap-2 text-cyan-800"><ImagePlus/>اختيار صورة جديدة</span>}<input data-testid="edit-vehicle-image" type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>choose(e.target.files?.[0])}/></label></Field><Field label="اسم السيارة" error={errors.vehicleName}><input data-testid="edit-vehicle-name" value={form.vehicleName} onChange={e=>update('vehicleName',e.target.value)} className={inputClass}/></Field><Field label="رقم DB" error={errors.dbNumber}><input data-testid="edit-vehicle-db" value={form.dbNumber} onChange={e=>update('dbNumber',e.target.value)} className={inputClass}/></Field><Field label="رقم اللوحة" error={errors.plateNumber}><input data-testid="edit-vehicle-plate" value={form.plateNumber} onChange={e=>update('plateNumber',e.target.value)} className={inputClass}/></Field><Field label="رقم الشاصي" error={errors.chassisNumber}><input data-testid="edit-vehicle-chassis" value={form.chassisNumber} onChange={e=>update('chassisNumber',e.target.value)} className={inputClass}/></Field></div>
    {updateVehicle.isError&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">تعذر التحديث. تحقق من عدم تكرار DB أو اللوحة أو الشاصي.</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="h-11 rounded-xl border px-5 font-bold">إلغاء</button><button data-testid="edit-vehicle-submit" disabled={updateVehicle.isPending} className="inline-flex h-11 items-center gap-2 rounded-xl bg-cyan-700 px-6 font-black text-white disabled:opacity-50"><Save size={17}/>{updateVehicle.isPending?'جارٍ الحفظ…':'حفظ التعديلات'}</button></div></form></div>
}
function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:React.ReactNode}){return <label className={`space-y-1.5 text-xs font-bold text-slate-600 ${wide?'sm:col-span-2':''}`}><span>{label}</span>{children}{error&&<span className="block text-red-600">{error}</span>}</label>}
