export {
  useSectors,
  useManagerProfile,
  useManagerProfileForUser,
  useSaveManagerProfile,
  useWorkers,
  useCreateWorker,
  useArchiveWorker,
  useVehicles,
  useCreateVehicle,
  useArchiveVehicle,
  useSupplies,
  useSubmitSupply,
  useBreakdowns,
  useSubmitBreakdown,
  useReturnVehicleToWork,
  useSectorVehicleTrips,
  useSectorVehicleTripDays,
  useSectorVehicleTripsForDay,
  useConfirmSectorVehicleArrival,
  useSendSectorVehicleToGarage,
  usePhotos,
  useUploadPhoto,
  useAttendanceByDate,
  useSetAttendance,
  useSectorSummary,
} from './hooks/useSector'

export {
  workerSchema,
  vehicleSchema,
  supplySchema,
  breakdownSchema,
  managerProfileSchema,
} from './schemas/sector.schema'
export type {
  WorkerFormInput,
  VehicleFormInput,
  SupplyFormInput,
  BreakdownFormInput,
  ManagerProfileFormInput,
} from './schemas/sector.schema'

export { SHIFT_LABELS } from './types'
export type {
  Shift,
  Sector,
  ManagerProfile,
  SectorWorker,
  SectorVehicle,
  SupplyRequest,
  Breakdown,
  SectorPhoto,
  SectorAttendance,
  SectorSummary,
  CreateWorkerInput,
  CreateVehicleInput,
  CreateSupplyInput,
  CreateBreakdownInput,
  CreateAttendanceInput,
} from './types'
