import{useMemo,useState}from'react'
import{Link}from'react-router'
import{Archive,ArrowUpLeft,BarChart3,BookOpen,CheckCircle2,Clock3,Download,FileCheck2,Inbox,Printer,RefreshCw,Send,Users,type LucideIcon}from'lucide-react'
import{downloadComplaintAnalytics,printComplaintAnalytics,useComplaintAnalytics,useComplaintSummary,type ComplaintReportPeriod,type ComplaintSector}from'@features/complaints'

const periodLabels:Record<ComplaintReportPeriod,string>={daily:'يومي',weekly:'أسبوعي',monthly:'شهري',semiannual:'نصف سنوي',annual:'سنوي'}
function iso(date:Date){return date.toISOString().slice(0,10)}
function range(period:ComplaintReportPeriod){const to=new Date();const from=new Date(to);if(period==='weekly')from.setDate(to.getDate()-6);if(period==='monthly')from.setDate(to.getDate()-29);if(period==='semiannual')from.setMonth(to.getMonth()-6);if(period==='annual')from.setFullYear(to.getFullYear()-1);return{from:iso(from),to:iso(to)}}
export default function DashboardPage(){
 const summary=useComplaintSummary();const[period,setPeriod]=useState<ComplaintReportPeriod>('monthly');const[sector,setSector]=useState<ComplaintSector|''>('');const dates=useMemo(()=>range(period),[period]);const analytics=useComplaintAnalytics(dates.from,dates.to,sector||undefined);const data=analytics.data;const max=Math.max(1,...(data?.daily.map(v=>v.total)??[1]))
 const cards=[{label:'إجمالي الشكاوى',value:summary.data?.total,icon:Inbox,tone:'from-sky-600 to-cyan-500'},{label:'بانتظار الإسناد',value:summary.data?.newCount,icon:Clock3,tone:'from-amber-500 to-orange-500'},{label:'قيد التنفيذ',value:summary.data?.inProgress,icon:RefreshCw,tone:'from-violet-600 to-fuchsia-500'},{label:'جاهزة للتدقيق',value:summary.data?.processed,icon:FileCheck2,tone:'from-blue-600 to-indigo-500'},{label:'معتمدة ومؤرشفة',value:summary.data?.archived,icon:CheckCircle2,tone:'from-emerald-600 to-teal-500'},{label:'مسندة',value:summary.data?.assigned,icon:Users,tone:'from-slate-700 to-slate-500'}]
 const quickLinks:Array<{icon:LucideIcon;to:string;label:string;hint:string}>=[{icon:Inbox,to:'/complaints/karrada-sector',label:'وارد الكرادة',hint:'عرض البريد والصور'},{icon:Inbox,to:'/complaints/zaafaraniya-sector',label:'وارد الزعفرانية',hint:'عرض البريد والصور'},{icon:Send,to:'/complaints/assignment',label:'الفرز والإسناد',hint:'توزيع العمل بوضوح'},{icon:CheckCircle2,to:'/complaints/processing',label:'التدقيق والمعالجة',hint:'مراجعة صور قبل وبعد'},{icon:BarChart3,to:'/complaints/templates',label:'التقارير والقوالب',hint:'التصميم والإرسال'},{icon:Archive,to:'/complaints/archive',label:'الأرشيف',hint:'الرجوع إلى المنجز'},{icon:BookOpen,to:'/complaints/guidance',label:'الإرشادات',hint:'شرح البوابة كاملاً'},{icon:ArrowUpLeft,to:'/complaints/data',label:'قاعدة البيانات',hint:'البحث في كل الشكاوى'}]
 return <section className="space-y-7" dir="rtl">
  <header className="relative overflow-hidden rounded-3xl bg-gradient-to-l from-slate-950 via-sky-950 to-teal-900 p-6 text-white shadow-xl sm:p-8"><div className="absolute -left-12 -top-16 size-52 rounded-full bg-cyan-400/15 blur-2xl"/><div className="relative flex flex-wrap items-center justify-between gap-5"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-cyan-100">مركز قيادة الشكاوى</span><h1 className="mt-3 text-2xl font-black sm:text-3xl">نظرة واضحة، قرار أسرع، مدينة أجمل</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-sky-100">متابعة البريد والفرز والمعالجة والتدقيق والتقارير من شاشة واحدة منظمة.</p></div><Link to="/complaints/guidance" className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 font-bold text-sky-900 shadow-lg"><BookOpen size={19}/>دليل موظف الشكاوى</Link></div></header>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(card=><article key={card.label} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className={`h-1.5 bg-gradient-to-l ${card.tone}`}/><div className="p-4"><span className={`flex size-10 items-center justify-center rounded-xl bg-gradient-to-br text-white ${card.tone}`}><card.icon size={20}/></span><strong className="mt-4 block text-3xl text-slate-900">{summary.isLoading?'…':card.value??0}</strong><p className="mt-1 text-xs font-bold text-slate-500">{card.label}</p></div></article>)}</div>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><BarChart3 className="text-sky-700"/><h2 className="text-lg font-black text-slate-900">التحليلات والتقرير الإداري</h2></div><p className="mt-1 text-sm text-slate-500">اختر الفترة والقاطع، ثم اطبع التقرير أو احفظه كملف مستقل.</p></div><div className="flex flex-wrap gap-2">{(Object.keys(periodLabels)as ComplaintReportPeriod[]).map(value=><button key={value} onClick={()=>setPeriod(value)} className={`rounded-xl px-3 py-2 text-xs font-bold transition ${period===value?'bg-sky-700 text-white shadow':'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{periodLabels[value]}</button>)}</div></div>
   <div className="mt-5 flex flex-wrap items-end gap-3"><label className="text-xs font-bold text-slate-600">القاطع<select value={sector} onChange={e=>setSector(e.target.value as ComplaintSector|'')} className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2"><option value="">جميع القواطع</option><option value="karrada">الكرادة</option><option value="zaafaraniya">الزعفرانية</option></select></label><span className="rounded-xl bg-slate-50 px-4 py-2 text-xs text-slate-600">من <b>{dates.from}</b> إلى <b>{dates.to}</b></span><button disabled={!data} onClick={()=>data&&printComplaintAnalytics(data,period)} className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Printer size={17}/>طباعة / حفظ PDF</button><button disabled={!data} onClick={()=>data&&downloadComplaintAnalytics(data,period)} className="flex items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 py-2 text-sm font-bold text-sky-800 disabled:opacity-40"><Download size={17}/>حفظ التقرير</button></div>
   {analytics.isLoading?<div className="mt-6 h-52 animate-pulse rounded-2xl bg-slate-100"/>:<div className="mt-6 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><article className="rounded-2xl bg-slate-50 p-4"><h3 className="text-sm font-bold text-slate-700">حركة الوارد خلال الفترة</h3><div className="mt-5 flex h-48 items-end gap-1 overflow-hidden" aria-label="رسم حركة الشكاوى">{data?.daily.map(point=><div key={point.day} className="group flex min-w-2 flex-1 flex-col items-center justify-end"><span className="mb-1 hidden text-[9px] font-bold group-hover:block">{point.total}</span><div title={`${point.day}: ${point.total}`} className="w-full rounded-t bg-gradient-to-t from-sky-700 to-cyan-400 transition hover:from-teal-700 hover:to-emerald-400" style={{height:`${point.total?Math.max(8,point.total/max*100):2}%`}}/></div>)}</div></article><article className="grid grid-cols-2 gap-3">{[['الإجمالي',data?.summary.total??0],['المعتمدة',data?.summary.approved??0],['قيد العمل',data?.summary.active??0],['بانتظار التدقيق',data?.summary.review??0],['غير المسندة',data?.summary.unassigned??0],['صور بعد',data?.summary.withAfter??0]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-100 p-4"><strong className="text-2xl text-sky-800">{value}</strong><p className="text-xs text-slate-500">{label}</p></div>)}</article></div>}
  </section>
  <section><h2 className="mb-3 text-sm font-black text-slate-700">الوصول السريع</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{quickLinks.map(({icon:Icon,to,label,hint})=><Link key={to} to={to} className="group flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300 hover:shadow-md"><span className="flex size-11 items-center justify-center rounded-xl bg-sky-50 text-sky-700"><Icon size={20}/></span><span><b className="block text-sm text-slate-800">{label}</b><small className="text-slate-500">{hint}</small></span></Link>)}</div></section>
 </section>
}
