import { useState } from 'react'
import { Link, useParams } from 'react-router'
import {
  useComplaintDeliveries, useComplaintItemDetail, useReviewComplaintItem,
  type ComplaintItemDetail, type ComplaintItemStatus,
} from '@features/complaints'

const statusLabel: Record<ComplaintItemStatus,string>={under_review:'قيد المراجعة',assigned:'مسندة',in_progress:'قيد التنفيذ',processed:'بانتظار التدقيق',quality_review:'قيد التدقيق',approved:'معتمدة',returned:'معادة للمسؤول'}

export default function ComplaintDetailPage(){const{id}=useParams();const detail=useComplaintItemDetail(id??null);if(detail.isLoading)return <p className="p-10 text-center">جارٍ تحميل التفاصيل…</p>;if(!detail.data)return <p className="p-10 text-center text-red-700">تعذر العثور على الشكوى</p>;return <DetailContent detail={detail.data}/>}

function DetailContent({detail}:{detail:ComplaintItemDetail}){
 const review=useReviewComplaintItem();const{data:deliveries=[]}=useComplaintDeliveries(detail.item.complaintId);const[note,setNote]=useState('')
 const item=detail.item;return <section className="space-y-5" dir="rtl">
  <header className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/complaints/data" className="text-sm text-blue-700">العودة إلى البيانات</Link><h1 className="mt-1 text-2xl font-bold">{item.referenceNo} — الموقع {item.sequenceNo}</h1><p className="text-sm text-slate-500">{item.sector==='karrada'?'قاطع الكرادة':'قاطع الزعفرانية'} · {statusLabel[item.status]}</p></div><span className="rounded-full bg-blue-50 px-4 py-2 text-sm font-bold text-blue-800">{statusLabel[item.status]}</span></header>
  <div className="grid gap-4 lg:grid-cols-3"><article className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="font-bold">بطاقة الموقع</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2">{[['المركز البلدي',item.municipalCenter],['المحلة',item.neighborhood],['الزقاق',item.alley],['نوع الشكوى',item.title],['وصف الموقع',item.locationText],['البريد المرسل',detail.senderEmail]].map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 p-3"><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-1 font-bold">{v||'—'}</dd></div>)}</dl>{detail.subject&&<div className="mt-4 rounded-lg border p-3"><b>موضوع الرسالة: {detail.subject}</b><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{detail.bodyText||'لا يوجد نص'}</p></div>}</article>
  <article className="rounded-xl border bg-white p-5"><h2 className="font-bold">سجل الحالات</h2><ol className="mt-3 space-y-3">{detail.history.map(event=><li key={event.id} className="border-r-2 border-rose-300 pr-3 text-sm"><b>{event.fromStatus?`${event.fromStatus} ← `:''}{event.toStatus}</b><time className="block text-xs text-slate-500">{new Date(event.createdAt).toLocaleString('ar-IQ')}</time>{event.note&&<p className="text-slate-600">{event.note}</p>}</li>)}</ol></article></div>
  <article className="rounded-xl border bg-white p-5"><h2 className="font-bold">صور قبل وبعد</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{(['before','after'] as const).map(kind=><div key={kind}><h3 className="mb-2 text-sm font-bold">{kind==='before'?'قبل المعالجة':'بعد المعالجة'}</h3><div className="grid gap-2 sm:grid-cols-2">{detail.media.filter(m=>m.kind===kind&&m.mimeType.startsWith('image/')).map(m=><a key={m.id} href={m.url} target="_blank" rel="noreferrer"><img src={m.url} alt={m.name} className="h-52 w-full rounded-lg bg-slate-100 object-contain"/><span className="text-xs text-slate-500">{m.capturedAt?new Date(m.capturedAt).toLocaleString('ar-IQ'):m.name}</span></a>)}</div></div>)}</div></article>
  {['processed','quality_review'].includes(item.status)&&<article className="rounded-xl border bg-white p-5"><h2 className="font-bold">قرار التدقيق</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="الملاحظة، وهي إلزامية عند الإرجاع" className="mt-3 min-h-24 w-full rounded-lg border p-3"/><div className="mt-3 flex gap-2"><button onClick={()=>review.mutate({itemId:item.id,approved:true,note})} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white">اعتماد</button><button disabled={!note.trim()} onClick={()=>review.mutate({itemId:item.id,approved:false,note})} className="rounded-lg bg-amber-600 px-4 py-2 font-bold text-white disabled:opacity-50">إرجاع</button></div></article>}
  <article className="rounded-xl border bg-white p-5"><h2 className="font-bold">محاولات الإرسال</h2>{deliveries.length===0?<p className="mt-3 text-sm text-slate-500">لا توجد محاولات إرسال مرتبطة بعد.</p>:deliveries.map(d=><div key={d.id} className="mt-3 flex flex-wrap justify-between border-t pt-3 text-sm"><span>{d.subject} — {d.recipients.join('، ')}</span><b>{d.status}</b>{d.errorMessage&&<span className="w-full text-red-700">{d.errorMessage}</span>}</div>)}</article>
 </section>
}
