import{useMemo,useState}from'react'
import{Link}from'react-router'
import{CheckCircle2,ChevronLeft,Clock3,Images,RotateCcw,Search,ShieldCheck,UserRound}from'lucide-react'
import{useComplaintItems,useComplaintItemsMedia,useComplaintManagers,useReviewComplaintAssignmentTicket,type ComplaintItem}from'@features/complaints'
import{ComplaintWorkflow}from'../../components/ComplaintUi'

type Filter='review'|'approved'|'returned'|'active'|'all';type Ticket={key:string;complaintId:string;managerId:string;name:string;referenceNo:string;receivedAt:string;items:ComplaintItem[];state:Exclude<Filter,'all'>}
const stateMeta={review:{label:'قيد التدقيق',className:'bg-amber-100 text-amber-900'},approved:{label:'معتمدة',className:'bg-emerald-100 text-emerald-800'},returned:{label:'معادة للمسؤول',className:'bg-rose-100 text-rose-800'},active:{label:'قيد المعالجة',className:'bg-blue-100 text-blue-800'}} as const
function ticketState(items:ComplaintItem[]):Ticket['state']{if(items.some(item=>['processed','quality_review'].includes(item.status)))return'review';if(items.every(item=>item.status==='approved'))return'approved';if(items.some(item=>item.status==='returned'))return'returned';return'active'}
export default function ProcessingPage(){
 const{data:all=[],isLoading}=useComplaintItems(false);const{data:managers=[]}=useComplaintManagers();const[filter,setFilter]=useState<Filter>('review');const[search,setSearch]=useState('');const[selected,setSelected]=useState<string|null>(null);const[note,setNote]=useState('');const[message,setMessage]=useState('');const review=useReviewComplaintAssignmentTicket()
 const tickets=useMemo(()=>{const groups=new Map<string,ComplaintItem[]>();all.filter(item=>item.assignedTo).forEach(item=>{const key=`${item.complaintId}:${item.assignedTo}`;groups.set(key,[...(groups.get(key)??[]),item])});return[...groups.entries()].map(([key,items]):Ticket=>{const first=items[0]!;return{key,complaintId:first.complaintId,managerId:first.assignedTo!,name:first.ticketName||first.referenceNo,referenceNo:first.referenceNo,receivedAt:first.receivedAt,items:items.sort((a,b)=>a.sequenceNo-b.sequenceNo),state:ticketState(items)}}).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))},[all])
 const counts=useMemo(()=>({review:tickets.filter(x=>x.state==='review').length,approved:tickets.filter(x=>x.state==='approved').length,returned:tickets.filter(x=>x.state==='returned').length,active:tickets.filter(x=>x.state==='active').length,all:tickets.length}),[tickets]);const shown=tickets.filter(ticket=>(filter==='all'||ticket.state===filter)&&`${ticket.name} ${ticket.referenceNo}`.toLowerCase().includes(search.toLowerCase()));const active=tickets.find(ticket=>ticket.key===selected)??shown[0]??null;const media=useComplaintItemsMedia(active?.items.map(item=>item.id)??[])
 const decide=(approved:boolean)=>{if(!active)return;review.mutate({complaintId:active.complaintId,managerId:active.managerId,approved,note},{onSuccess:count=>{setMessage(approved?`تم اعتماد التذكرة كاملة (${count} معالجة).`:`تمت إعادة التذكرة كاملة (${count} معالجة) إلى المسؤول.`);setNote('');setSelected(null)},onError:error=>setMessage(error instanceof Error?error.message:'تعذر حفظ قرار التدقيق.')})}
 return <section className="min-h-full space-y-5 pb-8" dir="rtl"><header className="rounded-3xl bg-gradient-to-l from-slate-950 via-fuchsia-950 to-rose-900 p-6 text-white shadow-xl"><span className="text-xs font-bold text-fuchsia-200">مركز الجودة</span><h1 className="mt-2 text-2xl font-black">معالجة الشكاوى والتدقيق</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-fuchsia-100">كل بطاقة تمثل تذكرة البريد والمسؤول كاملة. راجع جميع أزواج قبل/بعد ثم اعتمد التذكرة أو أعدها دفعة واحدة.</p></header><ComplaintWorkflow current="review"/>{message&&<p role="status" className="rounded-2xl bg-blue-50 p-4 text-sm font-bold text-blue-900">{message}</p>}
 <div className="grid gap-2 rounded-2xl border bg-white p-2 shadow-sm sm:grid-cols-5">{(['review','approved','returned','active','all']as Filter[]).map(value=><button key={value} onClick={()=>{setFilter(value);setSelected(null)}} className={`rounded-xl px-3 py-3 text-sm font-bold ${filter===value?'bg-slate-900 text-white':'bg-slate-50 text-slate-700'}`}>{value==='all'?'الكل':stateMeta[value].label} <span className="mr-1 rounded-full bg-white/20 px-2">{counts[value]}</span></button>)}</div>
 <label className="flex items-center gap-2 rounded-2xl border bg-white px-4 py-3"><Search size={18} className="text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="ابحث باسم التذكرة أو الرقم المرجعي" className="w-full outline-none"/></label>
 {isLoading?<div className="h-64 animate-pulse rounded-3xl bg-slate-100"/>:!shown.length?<p className="rounded-3xl border border-dashed bg-white p-12 text-center text-slate-500">لا توجد تذاكر ضمن هذه الحالة.</p>:<div className="grid items-start gap-5 xl:grid-cols-[.75fr_1.25fr]"><aside className="space-y-3">{shown.map(ticket=>{const manager=managers.find(value=>value.userId===ticket.managerId);return <button key={ticket.key} onClick={()=>{setSelected(ticket.key);setNote('');setMessage('')}} className={`w-full rounded-2xl border bg-white p-4 text-right shadow-sm transition ${active?.key===ticket.key?'border-fuchsia-500 ring-2 ring-fuchsia-100':'hover:border-slate-400'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-fuchsia-700">{ticket.referenceNo}</p><h2 className="mt-1 font-black">{ticket.name}</h2></div><span className={`rounded-full px-3 py-1 text-[11px] font-bold ${stateMeta[ticket.state].className}`}>{stateMeta[ticket.state].label}</span></div><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500"><span className="flex items-center gap-1"><Images size={14}/>{ticket.items.length} صورة</span><span className="flex items-center gap-1"><UserRound size={14}/>{manager?.fullName||'مسؤول القسم'}</span><span className="flex items-center gap-1"><Clock3 size={14}/>{new Date(ticket.receivedAt).toLocaleDateString('ar-IQ')}</span></div></button>})}</aside>{active&&<TicketReview ticket={active} managerName={managers.find(value=>value.userId===active.managerId)?.fullName} media={media.data??[]} note={note} setNote={setNote} decide={decide} pending={review.isPending}/>}</div>}
 </section>
}
function TicketReview({ticket,managerName,media,note,setNote,decide,pending}:{ticket:Ticket;managerName?:string;media:Array<{id:string;itemId:string|null;kind:string;url:string;name:string}>;note:string;setNote:(value:string)=>void;decide:(approved:boolean)=>void;pending:boolean}){return <article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div><span className="text-xs text-slate-500">تذكرة كاملة — {managerName||'مسؤول القسم'}</span><h2 className="mt-1 text-xl font-black">{ticket.name}</h2><p className="mt-1 text-sm text-slate-500">راجع {ticket.items.length} معالجة قبل اتخاذ القرار.</p></div><span className={`rounded-full px-3 py-2 text-xs font-bold ${stateMeta[ticket.state].className}`}>{stateMeta[ticket.state].label}</span></div><div className="mt-5 space-y-4">{ticket.items.map((item,index)=>{const before=media.find(value=>value.itemId===item.id&&value.kind==='before');const after=media.find(value=>value.itemId===item.id&&value.kind==='after');return <section key={item.id} className="rounded-2xl border bg-slate-50 p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><b>الموقع {index+1} · {item.title||'نوع غير محدد'}</b><span className="text-xs text-slate-500">محلة {item.neighborhood||'—'} · زقاق {item.alley||'—'}</span></div><div className="grid gap-3 sm:grid-cols-2"><ImageBox title="قبل المعالجة" src={before?.url} alt={before?.name}/><ImageBox title="بعد المعالجة" src={after?.url} alt={after?.name}/></div><Link to={`/complaints/items/${item.id}`} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-blue-700">فتح التفاصيل وتصحيح الصور والبيانات <ChevronLeft size={14}/></Link></section>})}</div>{ticket.state==='review'&&<div className="sticky bottom-3 mt-5 rounded-2xl border bg-white/95 p-4 shadow-lg backdrop-blur"><label className="text-sm font-bold">ملاحظة قرار التذكرة<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="الملاحظة إلزامية عند الإرجاع" className="mt-2 min-h-20 w-full rounded-xl border p-3"/></label><div className="mt-3 grid gap-2 sm:grid-cols-2"><button disabled={pending} onClick={()=>decide(true)} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-700 p-3 font-black text-white disabled:opacity-50"><ShieldCheck size={18}/>اعتماد التذكرة كاملة</button><button disabled={pending||!note.trim()} onClick={()=>decide(false)} className="flex items-center justify-center gap-2 rounded-xl bg-amber-600 p-3 font-black text-white disabled:opacity-50"><RotateCcw size={18}/>إعادة التذكرة كاملة</button></div></div>}{ticket.state==='approved'&&<p className="mt-5 flex items-center gap-2 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-800"><CheckCircle2/>هذه التذكرة معتمدة بالكامل وجاهزة للتقرير.</p>}</article>}
function ImageBox({title,src,alt}:{title:string;src?:string;alt?:string}){return <div className="overflow-hidden rounded-xl border bg-white p-2"><h3 className="mb-2 text-xs font-bold text-slate-600">{title}</h3>{src?<a href={src} target="_blank" rel="noreferrer"><img src={src} alt={alt||title} className="h-52 w-full rounded-lg bg-slate-100 object-contain"/></a>:<div className="flex h-52 items-center justify-center rounded-lg bg-slate-100 text-sm text-slate-400">لا توجد صورة</div>}</div>}
