import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router'
import {
  useComplaintReport, useComplaintReportDownload, useGenerateComplaintReport,
  useSaveComplaintReportDraft, useSendComplaintEmail, useSetComplaintReportStatus,
  type ComplaintReportDetail,
} from '@features/complaints'

export default function ReportEditorPage(){const{id}=useParams();const query=useComplaintReport(id??null);if(query.isLoading)return <p className="p-10 text-center">جارٍ تحميل التقرير…</p>;if(!query.data)return <p className="p-10 text-center text-red-700">التقرير غير موجود</p>;return <Editor key={`${query.data.id}-${query.data.createdAt}-${query.data.status}`} initial={query.data}/>}

function Editor({initial}:{initial:ComplaintReportDetail}){
 const[title,setTitle]=useState(initial.title);const[layout,setLayout]=useState(initial.layout);const[recipients,setRecipients]=useState(initial.recipients.join('\n'));const[items,setItems]=useState(initial.items);const[dragged,setDragged]=useState<number|null>(null);const[message,setMessage]=useState('')
 const save=useSaveComplaintReportDraft();const generate=useGenerateComplaintReport();const approve=useSetComplaintReportStatus();const download=useComplaintReportDownload();const send=useSendComplaintEmail()
 useEffect(()=>{setTitle(initial.title);setLayout(initial.layout);setRecipients(initial.recipients.join('\n'));setItems(initial.items)},[initial])
 const emails=useMemo(()=>[...new Set(recipients.split(/[\n,;]+/).map(v=>v.trim().toLowerCase()).filter(Boolean))],[recipients]);const editable=['draft','quality_review','failed'].includes(initial.status)
 const setLayoutValue=(key:string,value:unknown)=>setLayout(old=>({...old,[key]:value}));const accent=String(layout.accent??'#cf63c6')
 const move=(from:number,to:number)=>{if(to<0||to>=items.length)return;setItems(old=>{const next=[...old];const[picked]=next.splice(from,1);if(!picked)return old;next.splice(to,0,picked);return next.map((v,i)=>({...v,displayOrder:i+1}))})}
 const saveNow=()=>save.mutate({id:initial.id,title,layout,recipients:emails,items},{onSuccess:()=>setMessage('تم حفظ تصميم التقرير وترتيب المواقع.'),onError:()=>setMessage('تعذر حفظ التعديلات؛ راجع العنوان والمستلمين.')})
 return <section className="space-y-5" dir="rtl"><header className="flex flex-wrap justify-between gap-3"><div><Link to="/complaints/templates" className="text-sm text-blue-700">العودة إلى التقارير</Link><h1 className="mt-1 text-2xl font-bold">محرر التقرير</h1><p className="text-sm text-slate-500">{initial.reportDate} · {initial.sector==='karrada'?'قاطع الكرادة':'قاطع الزعفرانية'} · {initial.status}</p></div><div className="flex flex-wrap gap-2">{editable&&<button onClick={saveNow} disabled={save.isPending||!emails.length} className="rounded-lg bg-slate-800 px-4 py-2 font-bold text-white disabled:opacity-50">حفظ التصميم</button>}{editable&&<button onClick={()=>generate.mutate(initial.id,{onSuccess:()=>setMessage('تم توليد PowerPoint وأصبح جاهزاً للمراجعة.'),onError:()=>setMessage('تعذر توليد PowerPoint؛ احفظ التصميم أولاً وتأكد من تضمين عناصر.')})} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">توليد PowerPoint</button>}{initial.pptxPath&&<button onClick={()=>download.mutate(initial.pptxPath!,{onSuccess:url=>window.open(url,'_blank','noopener,noreferrer')})} className="rounded-lg border px-4 py-2 font-bold">تنزيل ومراجعة</button>}{initial.status==='quality_review'&&<button onClick={()=>approve.mutate({reportId:initial.id,status:'approved'},{onSuccess:()=>setMessage('تم اعتماد التقرير.'),onError:()=>setMessage('تعذر الاعتماد؛ يشترط وجود ملف PowerPoint مولّد وحالة قيد التدقيق.')})} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white">اعتماد</button>}{initial.status==='approved'&&initial.pptxPath&&<button onClick={()=>send.mutate({reportId:initial.id,to:emails,subject:title,text:`السلام عليكم، مرفق ${title}`,attachmentPaths:[initial.pptxPath!]},{onSuccess:()=>setMessage('قُبل طلب الإرسال، وسيتم تحديث حالة التسليم تلقائياً.'),onError:()=>setMessage('تعذر الإرسال؛ تحقق من أسرار Mailgun والمستلمين المعتمدين.')})} className="rounded-lg bg-rose-700 px-4 py-2 font-bold text-white">إرسال نهائي</button>}</div></header>
 {message&&<p aria-live="polite" className="rounded-lg bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}
 <div className="grid gap-4 xl:grid-cols-[360px_1fr]"><aside className="space-y-4"><article className="rounded-xl border bg-white p-4"><h2 className="font-bold">هوية وتصميم الشرائح</h2><label className="mt-3 block text-xs">عنوان التقرير<input disabled={!editable} value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full rounded border p-2 text-sm"/></label><label className="mt-3 flex items-center justify-between text-xs">اللون الرئيسي<input disabled={!editable} type="color" value={accent} onChange={e=>setLayoutValue('accent',e.target.value)}/></label><label className="mt-3 block text-xs">عنوان الغلاف<input disabled={!editable} value={String(layout.title??'تقرير معالجة الشكاوى ليوم')} onChange={e=>setLayoutValue('title',e.target.value)} className="mt-1 w-full rounded border p-2"/></label><div className="grid grid-cols-2 gap-2"><label className="mt-3 text-xs">عنوان قبل<input disabled={!editable} value={String(layout.beforeLabel??'صورة التلكؤ / الشكوى')} onChange={e=>setLayoutValue('beforeLabel',e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="mt-3 text-xs">عنوان بعد<input disabled={!editable} value={String(layout.afterLabel??'صورة المعالجة')} onChange={e=>setLayoutValue('afterLabel',e.target.value)} className="mt-1 w-full rounded border p-2"/></label></div><label className="mt-3 block text-xs">خط عنوان الغلاف<select disabled={!editable} value={String(layout.fontFamily??'Arial')} onChange={e=>setLayoutValue('fontFamily',e.target.value)} className="mt-1 w-full rounded border p-2"><option>Arial</option><option>Tahoma</option><option>Calibri</option></select></label><label className="mt-3 block text-xs">حجم عنوان الغلاف: {Number(layout.coverFontSize??30)}<input disabled={!editable} type="range" min="20" max="42" value={Number(layout.coverFontSize??30)} onChange={e=>setLayoutValue('coverFontSize',Number(e.target.value))} className="w-full"/></label><label className="mt-3 block text-xs">ارتفاع صور قبل/بعد: {Number(layout.imageHeight??4.8).toFixed(1)}<input disabled={!editable} type="range" min="3" max="4.8" step="0.1" value={Number(layout.imageHeight??4.8)} onChange={e=>setLayoutValue('imageHeight',Number(e.target.value))} className="w-full"/></label><label className="mt-3 block text-xs">البريد: سطر لكل مستلم<textarea disabled={!editable} value={recipients} onChange={e=>setRecipients(e.target.value)} className="mt-1 min-h-24 w-full rounded border p-2"/></label></article>
 <article className="rounded-xl border bg-white p-4"><h2 className="font-bold">معاينة مباشرة</h2><div className="mt-3 aspect-video rounded-lg border bg-white p-3" style={{borderColor:accent}}><div className="rounded p-2 text-center font-bold text-white" style={{background:accent,fontSize:Math.max(12,Number(layout.coverFontSize??30)/2)}}>{String(layout.title??title)}</div><div className="mt-3 grid grid-cols-2 gap-2 text-center text-[10px]"><div className="rounded bg-slate-100 p-2">{String(layout.afterLabel??'بعد')}</div><div className="rounded bg-slate-100 p-2">{String(layout.beforeLabel??'قبل')}</div></div></div></article></aside>
 <article className="rounded-xl border bg-white p-4"><div className="flex justify-between"><h2 className="font-bold">ترتيب ومحتوى التقرير</h2><span className="text-xs text-slate-500">{items.filter(i=>i.included).length} من {items.length} موقع</span></div><p className="mt-1 text-xs text-slate-500">اسحب البطاقات أو استخدم الأسهم. يمكن استبعاد الموقع من العرض دون حذف بياناته.</p><div className="mt-4 space-y-2">{items.map((entry,index)=><div key={entry.itemId} draggable={editable} onDragStart={()=>setDragged(index)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragged!==null)move(dragged,index);setDragged(null)}} className={`flex flex-wrap items-center gap-3 rounded-lg border p-3 ${entry.included?'bg-white':'bg-slate-100 opacity-60'}`}><span className="cursor-grab text-slate-400">☰</span><input disabled={!editable} type="checkbox" checked={entry.included} onChange={e=>setItems(old=>old.map(v=>v.itemId===entry.itemId?{...v,included:e.target.checked}:v))}/><div className="min-w-0 flex-1"><Link to={`/complaints/items/${entry.itemId}`} className="font-bold text-blue-700">{entry.item.referenceNo} / {entry.item.sequenceNo}</Link><p className="truncate text-xs text-slate-500">محلة {entry.item.neighborhood||'—'} · زقاق {entry.item.alley||'—'} · {entry.item.status}</p></div><button disabled={!editable||index===0} onClick={()=>move(index,index-1)} aria-label="تحريك للأعلى" className="rounded border px-2 py-1">↑</button><button disabled={!editable||index===items.length-1} onClick={()=>move(index,index+1)} aria-label="تحريك للأسفل" className="rounded border px-2 py-1">↓</button></div>)}</div></article></div>
 <article className="rounded-xl border bg-white p-4"><h2 className="font-bold">سجل محاولات التسليم</h2>{!initial.deliveries.length?<p className="mt-3 text-sm text-slate-500">لم تبدأ أي محاولة إرسال لهذا التقرير.</p>:<div className="mt-3 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-slate-50"><th className="p-2 text-right">الوقت</th><th className="p-2 text-right">المستلمون</th><th className="p-2">الحالة</th><th className="p-2 text-right">النتيجة</th></tr></thead><tbody>{initial.deliveries.map(d=><tr key={d.id} className="border-t"><td className="p-2">{new Date(d.createdAt).toLocaleString('ar-IQ')}</td><td className="p-2" dir="ltr">{d.recipients.join(', ')}</td><td className="p-2 text-center font-bold">{d.status}</td><td className="p-2">{d.errorMessage??(d.deliveredAt?`تم التسليم ${new Date(d.deliveredAt).toLocaleString('ar-IQ')}`:'بانتظار تحديث المزود')}</td></tr>)}</tbody></table></div>}</article>
 </section>
}
