import { useDeferredValue, useState } from 'react'
import { AlertTriangle, ArrowDownToLine, Droplets, Fuel, History, Plus, Search, Send, X } from 'lucide-react'
import { garageFillSchema, garageStockSchema, garageTankSchema, garageZeroSchema } from '@features/central-garage/schemas'
import { useAddGarageTank, useAddGarageTankStock, useFillGarageVehicle, useGarageTankMovements, useGarageTanks, useGarageVehicles, useRequestGarageTankZero } from '@features/central-garage/hooks'
import type { GarageFuelType, GarageTank } from '@features/central-garage/types'
import { LoadingSpinner } from '@components/feedback/LoadingSpinner'
import { EmptyState } from '@components/feedback/EmptyState'

const fuelMeta:Record<GarageFuelType,{title:string;description:string;color:string}>={gas_oil:{title:'الكاز',description:'خزانات الكاز وتعبئة الآليات',color:'from-amber-950 to-orange-700'},hydraulic:{title:'الهيدروليك',description:'مخزون سائل الهيدروليك وحركات الصرف',color:'from-blue-950 to-cyan-700'},grease:{title:'الدهن',description:'خزانات الدهن وسجل التوزيع',color:'from-violet-950 to-fuchsia-700'},c_oil:{title:'C-Oil',description:'خزانات C-Oil وحركات الآليات',color:'from-slate-950 to-teal-700'}}
const input='h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-amber-600 focus:ring-2 focus:ring-amber-100'
const baghdadToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baghdad',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())

type Dialog={kind:'stock'|'fill'|'zero'|'history';tank:GarageTank}|{kind:'add'}|null
export default function FuelTypePage({fuelType}:{fuelType:GarageFuelType}){
  const meta=fuelMeta[fuelType];const tanks=useGarageTanks(fuelType);const[dialog,setDialog]=useState<Dialog>(null)
  return <section className="space-y-5" dir="rtl" data-testid={`fuel-page-${fuelType}`}>
    <header className={`flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-gradient-to-l ${meta.color} p-6 text-white shadow-xl`}><div><span className="inline-flex items-center gap-2 text-xs font-bold text-white/75"><Fuel size={16}/>الوقود والزيوت</span><h1 className="mt-2 text-3xl font-black">{meta.title}</h1><p className="mt-1 text-sm text-white/75">{meta.description}</p></div><button data-testid="open-add-tank" onClick={()=>setDialog({kind:'add'})} className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-5 font-black text-slate-900"><Plus size={18}/>إضافة خزان جديد</button></header>
    {tanks.isLoading?<div className="rounded-2xl bg-white p-12"><LoadingSpinner label="جارٍ تحميل الخزانات…"/></div>:(tanks.data?.length??0)===0?<EmptyState title={`لا توجد خزانات ${meta.title}`} hint="أضف الخزان الأول وحدد سعته وكميته الابتدائية"/>:<div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{tanks.data?.map(tank=><TankCard key={tank.id} tank={tank} onAction={kind=>setDialog({kind,tank})}/>)}</div>}
    {dialog?.kind==='add'&&<AddTankDialog fuelType={fuelType} onClose={()=>setDialog(null)}/>} 
    {dialog&&dialog.kind==='stock'&&<StockDialog tank={dialog.tank} onClose={()=>setDialog(null)}/>} 
    {dialog&&dialog.kind==='fill'&&<FillDialog tank={dialog.tank} onClose={()=>setDialog(null)}/>} 
    {dialog&&dialog.kind==='zero'&&<ZeroDialog tank={dialog.tank} onClose={()=>setDialog(null)}/>} 
    {dialog&&dialog.kind==='history'&&<HistoryDialog tank={dialog.tank} onClose={()=>setDialog(null)}/>} 
  </section>
}

function TankCard({tank,onAction}:{tank:GarageTank;onAction:(kind:'stock'|'fill'|'zero'|'history')=>void}){const pct=Math.min(100,Math.max(0,tank.currentQuantity*100/tank.capacity));const low=pct<=tank.lowStockThreshold;return <article className={`rounded-3xl border bg-white p-5 shadow-sm ${low?'border-red-200':'border-slate-200'}`} data-testid={`tank-${tank.id}`}><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-slate-400">الخزان</p><h2 className="mt-1 text-lg font-black text-slate-900">{tank.tankName}</h2></div><span className={`flex size-11 items-center justify-center rounded-2xl ${low?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{low?<AlertTriangle/>:<Droplets/>}</span></div><div className="mt-5"><div className="flex items-end justify-between"><p><b className="text-2xl text-slate-950">{tank.currentQuantity.toLocaleString('ar-IQ')}</b><span className="text-xs text-slate-500"> / {tank.capacity.toLocaleString('ar-IQ')} وحدة</span></p><b className={low?'text-red-700':'text-emerald-700'}>{pct.toFixed(1)}%</b></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-all ${low?'bg-red-500':pct<50?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${pct}%`}}/></div>{low&&<p className="mt-2 text-xs font-bold text-red-700">تنبيه: وصل المخزون إلى حد الانخفاض</p>}</div><div className="mt-5 grid grid-cols-2 gap-2"><Action testId={`stock-${tank.id}`} icon={<Plus/>} label="إضافة كمية" onClick={()=>onAction('stock')}/><Action testId={`fill-${tank.id}`} icon={<ArrowDownToLine/>} label="تعبئة آلية" onClick={()=>onAction('fill')}/><Action testId={`history-${tank.id}`} icon={<History/>} label="سجل الحركات" onClick={()=>onAction('history')}/><Action testId={`zero-${tank.id}`} icon={<Send/>} label="طلب تصفير" danger onClick={()=>onAction('zero')}/></div></article>}
function Action({testId,icon,label,onClick,danger}:{testId:string;icon:React.ReactNode;label:string;onClick:()=>void;danger?:boolean}){return <button data-testid={testId} onClick={onClick} className={`inline-flex h-10 items-center justify-center gap-1.5 rounded-xl text-xs font-black ${danger?'border border-red-200 bg-red-50 text-red-700':'bg-slate-100 text-slate-700 hover:bg-amber-50 hover:text-amber-800'} [&>svg]:size-4`}>{icon}{label}</button>}

function Shell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label={title}><div className="mx-auto my-8 w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{title}</h2><button aria-label="إغلاق" onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div>{children}</div></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block space-y-1.5 text-xs font-bold text-slate-600"><span>{label}</span>{children}{error&&<span className="block text-red-600">{error}</span>}</label>}
function errorsOf(result:{error:{issues:Array<{path:PropertyKey[];message:string}>}}){return Object.fromEntries(result.error.issues.map(i=>[String(i.path[0]),i.message]))}

function AddTankDialog({fuelType,onClose}:{fuelType:GarageFuelType;onClose:()=>void}){const[form,setForm]=useState({fuelType,tankName:'',capacity:'',initialQuantity:'0',lowStockThreshold:'20'});const[errors,setErrors]=useState<Record<string,string>>({});const add=useAddGarageTank();const submit=(e:React.FormEvent)=>{e.preventDefault();const p=garageTankSchema.safeParse(form);if(!p.success){setErrors(errorsOf(p));return}add.mutate(p.data,{onSuccess:onClose})};return <Shell title="إضافة خزان جديد" onClose={onClose}><form onSubmit={submit} className="mt-5 space-y-4" data-testid="add-tank-form"><Field label="اسم الخزان" error={errors.tankName}><input data-testid="tank-name" className={input} value={form.tankName} onChange={e=>setForm({...form,tankName:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="سعة الخزان" error={errors.capacity}><input data-testid="tank-capacity" type="number" min="0" step="0.001" className={input} value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field><Field label="الكمية الابتدائية" error={errors.initialQuantity}><input data-testid="tank-initial" type="number" min="0" step="0.001" className={input} value={form.initialQuantity} onChange={e=>setForm({...form,initialQuantity:e.target.value})}/></Field></div><Field label="حد تنبيه انخفاض المخزون (%)" error={errors.lowStockThreshold}><input data-testid="tank-threshold" type="number" min="0" max="100" className={input} value={form.lowStockThreshold} onChange={e=>setForm({...form,lowStockThreshold:e.target.value})}/></Field><Submit testId="tank-submit" pending={add.isPending} label="إنشاء الخزان"/></form></Shell>}
function StockDialog({tank,onClose}:{tank:GarageTank;onClose:()=>void}){const[form,setForm]=useState({quantity:'',notes:''});const[errors,setErrors]=useState<Record<string,string>>({});const add=useAddGarageTankStock();const submit=(e:React.FormEvent)=>{e.preventDefault();const p=garageStockSchema.safeParse(form);if(!p.success){setErrors(errorsOf(p));return}add.mutate({tankId:tank.id,...p.data},{onSuccess:onClose})};return <Shell title={`إضافة كمية إلى ${tank.tankName}`} onClose={onClose}><p className="mt-2 text-sm text-slate-500">المتاح حتى السعة: {(tank.capacity-tank.currentQuantity).toLocaleString('ar-IQ')} وحدة</p><form onSubmit={submit} className="mt-5 space-y-4"><Field label="الكمية المضافة" error={errors.quantity}><input data-testid="stock-quantity" type="number" min="0" step="0.001" className={input} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="ملاحظات"><textarea data-testid="stock-notes" className="min-h-24 w-full rounded-xl border p-3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Submit testId="stock-submit" pending={add.isPending} label="إضافة وتحديث الرصيد"/></form></Shell>}
function FillDialog({tank,onClose}:{tank:GarageTank;onClose:()=>void}){const[search,setSearch]=useState('');const deferred=useDeferredValue(search);const[selected,setSelected]=useState('');const[quantity,setQuantity]=useState('');const[nextDate,setNextDate]=useState('');const[notes,setNotes]=useState('');const[errors,setErrors]=useState<Record<string,string>>({});const vehicles=useGarageVehicles({search:deferred,pageSize:12});const fill=useFillGarageVehicle();const submit=(e:React.FormEvent)=>{e.preventDefault();const p=garageFillSchema.safeParse({vehicleId:selected,quantity,nextRefillDate:nextDate,notes});if(!p.success){setErrors(errorsOf(p));return}fill.mutate({tankId:tank.id,...p.data},{onSuccess:onClose})};return <Shell title={`تعبئة آلية من ${tank.tankName}`} onClose={onClose}><p className="mt-2 text-sm text-slate-500">الرصيد الحالي: <b>{tank.currentQuantity.toLocaleString('ar-IQ')}</b> وحدة</p><form onSubmit={submit} className="mt-5 space-y-4"><Field label="ابحث عن الآلية" error={errors.vehicleId}><div className="relative"><Search className="absolute right-3 top-3 text-slate-400" size={18}/><input data-testid="fill-vehicle-search" className={`${input} pr-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم DB أو السائق أو اللوحة"/></div><div className="mt-2 max-h-40 space-y-1 overflow-y-auto">{vehicles.data?.rows.map(v=><button data-testid={`select-fill-vehicle-${v.id}`} type="button" key={v.id} onClick={()=>setSelected(v.id)} className={`flex w-full justify-between rounded-xl border p-2.5 text-xs ${selected===v.id?'border-amber-500 bg-amber-50':'border-slate-200'}`}><b>{v.vehicleName} · DB {v.dbNumber}</b><span>{v.driverName}</span></button>)}</div></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="كمية التعبئة" error={errors.quantity}><input data-testid="fill-quantity" type="number" min="0" step="0.001" className={input} value={quantity} onChange={e=>setQuantity(e.target.value)}/></Field><Field label="تاريخ الموعد التالي" error={errors.nextRefillDate}><input data-testid="fill-next-date" type="date" min={baghdadToday()} className={input} value={nextDate} onChange={e=>setNextDate(e.target.value)}/></Field></div><Field label="ملاحظات"><textarea data-testid="fill-notes" className="min-h-20 w-full rounded-xl border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></Field><Submit testId="fill-submit" pending={fill.isPending} label="تأكيد التعبئة وخصم الرصيد"/></form></Shell>}
function ZeroDialog({tank,onClose}:{tank:GarageTank;onClose:()=>void}){const[reason,setReason]=useState('');const[error,setError]=useState('');const request=useRequestGarageTankZero();const submit=(e:React.FormEvent)=>{e.preventDefault();const p=garageZeroSchema.safeParse({reason});if(!p.success){setError(p.error.issues[0]?.message??'السبب مطلوب');return}request.mutate({tankId:tank.id,reason:p.data.reason},{onSuccess:onClose})};return <Shell title="طلب تصفير الخزان" onClose={onClose}><div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><b>لن يتم التصفير الآن.</b><p className="mt-1">سيُرسل الطلب إلى بوابة التطوير المركزية، والرصيد الحالي {tank.currentQuantity} وحدة.</p></div><form onSubmit={submit} className="mt-4 space-y-4"><Field label="سبب التصفير" error={error}><textarea data-testid="zero-reason" className="min-h-28 w-full rounded-xl border p-3" value={reason} onChange={e=>setReason(e.target.value)}/></Field><Submit testId="zero-submit" pending={request.isPending} label="إرسال الطلب للتطوير المركزية"/></form></Shell>}
function HistoryDialog({tank,onClose}:{tank:GarageTank;onClose:()=>void}){const history=useGarageTankMovements(tank.id);return <Shell title={`سجل حركات ${tank.tankName}`} onClose={onClose}><div className="mt-5 max-h-[60vh] space-y-2 overflow-y-auto">{history.isLoading?<LoadingSpinner label=""/>:history.data?.map(m=><div key={m.id} className="rounded-2xl border p-3 text-xs"><div className="flex justify-between"><b>{m.movementType==='stock_in'?'إضافة مخزون':m.movementType==='vehicle_fill'?'تعبئة آلية':'تصفير معتمد'}</b><span className={m.quantity>0?'text-emerald-700':'text-red-700'}>{m.quantity>0?'+':''}{m.quantity}</span></div><p className="mt-1 text-slate-500">الرصيد: {m.quantityBefore} ← {m.quantityAfter}</p><p className="mt-1 text-slate-400">{new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Baghdad'}).format(new Date(m.createdAt))}</p>{m.nextRefillDate&&<p className="mt-1 font-bold text-cyan-800">الموعد التالي: {m.nextRefillDate}</p>}</div>)}{!history.isLoading&&!history.data?.length&&<p className="py-8 text-center text-sm text-slate-400">لا توجد حركات</p>}</div></Shell>}
function Submit({testId,pending,label}:{testId:string;pending:boolean;label:string}){return <button data-testid={testId} disabled={pending} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-amber-700 font-black text-white disabled:opacity-60">{pending?'جارٍ التنفيذ…':label}</button>}
