import { useDeferredValue, useEffect, useState } from 'react'
import { Archive, ChevronLeft, ChevronRight, Clock3, Search } from 'lucide-react'
import { Link } from 'react-router'
import { useGarageAreas, useGarageVehicles } from '@features/central-garage/hooks'
import type { GarageShift } from '@features/central-garage/types'
import { EmptyState } from '@components/feedback/EmptyState'
import { LoadingSpinner } from '@components/feedback/LoadingSpinner'

const inputClass='h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100'
const arDate=(value:string)=>new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Baghdad'}).format(new Date(value))
export default function GarageArchivePage(){
  const[search,setSearch]=useState('');const deferred=useDeferredValue(search);const[sector,setSector]=useState('');const[shift,setShift]=useState('');const[page,setPage]=useState(1);const areas=useGarageAreas()
  useEffect(()=>setPage(1),[deferred,sector,shift])
  const vehicles=useGarageVehicles({search:deferred,sectorId:sector?Number(sector):undefined,shift:shift as GarageShift||undefined,page,pageSize:24,archived:true});const total=vehicles.data?.totalCount??0;const pages=Math.max(1,Math.ceil(total/24))
  return <section className="space-y-5" dir="rtl" data-testid="garage-archive-page">
    <header className="rounded-3xl bg-gradient-to-l from-slate-950 to-slate-700 p-6 text-white shadow-xl"><span className="inline-flex items-center gap-2 text-xs font-bold text-slate-200"><Archive size={16}/>السجلات المحفوظة</span><h1 className="mt-2 text-2xl font-black">أرشيف آليات الكراج</h1><p className="mt-1 text-sm text-slate-200">الآليات المؤرشفة مع سبب وتوقيت الأرشفة والسجلات التاريخية الكاملة</p></header>
    <div className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_180px_auto]"><label className="relative"><Search className="absolute right-3 top-3 text-slate-400" size={18}/><input data-testid="archive-search" value={search} onChange={e=>setSearch(e.target.value)} className={`${inputClass} pr-10`} placeholder="DB، السيارة، السائق، اللوحة أو الشاصي"/></label><select data-testid="archive-area" value={sector} onChange={e=>setSector(e.target.value)} className={inputClass}><option value="">كل المواقع</option>{(['karrada','zaafaraniya'] as const).map(parent=><optgroup key={parent} label={parent==='karrada'?'قاطع الكرادة':'قاطع الزعفرانية'}>{(areas.data??[]).filter(a=>a.parentSector===parent).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</optgroup>)}</select><select data-testid="archive-shift" value={shift} onChange={e=>setShift(e.target.value)} className={inputClass}><option value="">كل الشفتات</option><option value="morning">صباحي</option><option value="evening">مسائي</option><option value="night">ليلي</option></select><div className="flex items-center justify-center rounded-xl bg-slate-100 px-4 text-sm font-black">{total} مؤرشفة</div></div>
    {vehicles.isLoading?<div className="rounded-2xl bg-white p-12"><LoadingSpinner label="جارٍ تحميل الأرشيف…"/></div>:vehicles.isError?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-6 text-center font-bold text-red-700">تعذر تحميل أرشيف الآليات.</div>:!vehicles.data?.rows.length?<EmptyState title="أرشيف الآليات فارغ" hint="ستظهر هنا الآليات التي تمت أرشفتها"/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{vehicles.data.rows.map(v=><Link key={v.id} to={`/central-garage/vehicles-database/${v.id}`} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:border-cyan-300 hover:shadow-lg" data-testid={`archived-vehicle-${v.id}`}><div className="relative"><img src={v.imageUrl} alt={`صورة ${v.vehicleName}`} className="h-40 w-full object-cover grayscale-[35%]"/><span className="absolute right-3 top-3 rounded-full bg-slate-950/80 px-3 py-1 text-[11px] font-black text-white">DB {v.dbNumber}</span></div><div className="p-4"><div className="flex justify-between gap-3"><div><h2 className="font-black text-slate-900">{v.vehicleName}</h2><p className="mt-1 text-xs text-slate-500">{v.driverName} · {v.areaName}</p></div><Archive className="text-slate-400" size={20}/></div><div className="mt-3 rounded-2xl bg-slate-50 p-3 text-xs"><p className="font-bold text-slate-700">سبب الأرشفة: {v.archiveReason??'غير مسجل'}</p>{v.archivedAt&&<p className="mt-2 flex items-center gap-1 text-[11px] text-slate-400"><Clock3 size={13}/>{arDate(v.archivedAt)}</p>}</div></div></Link>)}</div>}
    {total>24&&<nav className="flex items-center justify-center gap-3" aria-label="صفحات الأرشيف"><button aria-label="الصفحة السابقة" disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronRight/></button><span className="text-sm font-bold">{page} من {pages}</span><button aria-label="الصفحة التالية" disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronLeft/></button></nav>}
  </section>
}
