import { useState } from 'react'
import { Archive, ArrowRight, CalendarClock, Droplets, Hash, MapPin, Pencil, RotateCcw, ShieldCheck, UserRound } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router'
import { useArchiveGarageVehicle, useGarageAreas, useGarageAssignments, useGarageVehicle, useGarageVehicleMovements, useRestoreGarageVehicle } from '@features/central-garage/hooks'
import { garageArchiveReasonSchema } from '@features/central-garage/schemas'
import { LoadingSpinner } from '@components/feedback/LoadingSpinner'
import { AssignmentDialog } from '../components/AssignmentDialog'
import { EditVehicleDialog } from '../components/EditVehicleDialog'

const arDate=(value:string)=>new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Baghdad'}).format(new Date(value))
export default function VehicleDetailPage(){
  const{vehicleId:id=''}=useParams();const navigate=useNavigate();const vehicle=useGarageVehicle(id);const history=useGarageAssignments(id);const movements=useGarageVehicleMovements(id);const areas=useGarageAreas();const archive=useArchiveGarageVehicle();const restore=useRestoreGarageVehicle();const[assignOpen,setAssignOpen]=useState(false);const[editOpen,setEditOpen]=useState(false);const[archiveOpen,setArchiveOpen]=useState(false);const[restoreOpen,setRestoreOpen]=useState(false);const[reason,setReason]=useState('')
  if(vehicle.isLoading)return <div className="p-12"><LoadingSpinner label="جارٍ تحميل تفاصيل الآلية…"/></div>
  if(vehicle.isError||!vehicle.data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center font-bold text-red-700">تعذر العثور على الآلية المطلوبة.</div>
  const v=vehicle.data
  const submitArchive=(e:React.FormEvent)=>{e.preventDefault();if(!garageArchiveReasonSchema.safeParse(reason).success)return;archive.mutate({vehicleId:v.id,reason:reason.trim()},{onSuccess:()=>navigate('/central-garage/vehicles-database')})}
  const submitRestore=(e:React.FormEvent)=>{e.preventDefault();if(!garageArchiveReasonSchema.safeParse(reason).success)return;restore.mutate({vehicleId:v.id,reason:reason.trim()},{onSuccess:()=>navigate('/central-garage/vehicles-database')})}
  return <section className="space-y-5" dir="rtl" data-testid="vehicle-detail-page">
    <Link to={v.archivedAt?'/central-garage/archive':'/central-garage/vehicles-database'} className="inline-flex items-center gap-2 text-sm font-bold text-cyan-800"><ArrowRight size={17}/>{v.archivedAt?'العودة إلى الأرشيف':'العودة إلى قاعدة الآليات'}</Link>
    {v.archivedAt&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><b className="text-amber-900">هذه الآلية مؤرشفة</b><p className="mt-1 text-amber-800">السبب: {v.archiveReason??'غير مسجل'} · {arDate(v.archivedAt)}</p></div>}
    <article className="overflow-hidden rounded-3xl border bg-white shadow-xl"><div className="grid lg:grid-cols-[380px_1fr]"><img src={v.imageUrl} alt={`صورة ${v.vehicleName}`} className="h-72 w-full object-cover lg:h-full"/><div className="p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-cyan-800">DB {v.dbNumber}</span><h1 className="mt-3 text-3xl font-black text-slate-950">{v.vehicleName}</h1><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><UserRound size={17}/>{v.driverName}</p></div><div className="flex flex-wrap gap-2">{v.archivedAt?<button data-testid="open-restore-vehicle" onClick={()=>{setReason('');setRestoreOpen(true)}} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-700 px-4 text-xs font-black text-white"><RotateCcw size={15}/>استعادة الآلية</button>:<><button data-testid="open-edit-vehicle" onClick={()=>setEditOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-xl border border-cyan-200 bg-cyan-50 px-4 text-xs font-black text-cyan-800"><Pencil size={15}/>تعديل البيانات</button><button data-testid="detail-change-assignment" onClick={()=>setAssignOpen(true)} className="h-10 rounded-xl bg-cyan-700 px-4 text-xs font-black text-white">تغيير الانطلاقية</button><button data-testid="open-archive-vehicle" onClick={()=>{setReason('');setArchiveOpen(true)}} className="h-10 rounded-xl border border-red-200 bg-red-50 px-4 text-xs font-black text-red-700">أرشفة</button></>}</div></div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2"><Info icon={<Hash/>} label="رقم اللوحة" value={v.plateNumber}/><Info icon={<ShieldCheck/>} label="رقم الشاصي" value={v.chassisNumber}/><Info icon={<MapPin/>} label="موقع العمل" value={`${v.parentSector==='karrada'?'قاطع الكرادة':'قاطع الزعفرانية'} · ${v.areaName}`}/><Info icon={<CalendarClock/>} label="الشفت" value={v.shift==='morning'?'صباحي':v.shift==='evening'?'مسائي':'ليلي'}/></div></div></div></article>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black text-slate-900"><UserRound className="text-cyan-700"/>سجل الانطلاقية</h2>{history.isLoading?<LoadingSpinner label=""/>:<div className="mt-4 space-y-3">{history.data?.map((entry,index)=><div key={entry.id} className={`rounded-2xl border p-4 ${index===0&&entry.endsAt===null?'border-cyan-200 bg-cyan-50/50':'border-slate-200'}`}><div className="flex justify-between gap-3"><b>{entry.driverName}</b>{entry.endsAt===null&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-bold text-emerald-800">الحالي</span>}</div><p className="mt-2 text-xs text-slate-600">{(areas.data??[]).find(a=>a.id===entry.sectorId)?.name??`منطقة ${entry.sectorId}`} · {entry.shift==='morning'?'صباحي':entry.shift==='evening'?'مسائي':'ليلي'}</p><p className="mt-1 text-[11px] text-slate-400">من {arDate(entry.startsAt)}{entry.endsAt?` إلى ${arDate(entry.endsAt)}`:''}</p>{entry.changeReason&&<p className="mt-2 text-xs text-slate-500">السبب: {entry.changeReason}</p>}</div>)}{!history.data?.length&&<p className="py-6 text-center text-sm text-slate-400">لا يوجد سجل</p>}</div>}</section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black text-slate-900"><Droplets className="text-amber-700"/>سجل التعبئة</h2>{movements.isLoading?<LoadingSpinner label=""/>:<div className="mt-4 space-y-3">{movements.data?.filter(m=>m.movementType==='vehicle_fill').map(entry=><div key={entry.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><b className="text-amber-800">{Math.abs(entry.quantity)} وحدة</b><span className="text-[11px] text-slate-400">{arDate(entry.createdAt)}</span></div><p className="mt-2 text-xs text-slate-600">الرصيد: {entry.quantityBefore} ← {entry.quantityAfter}</p><p className="mt-1 text-xs font-bold text-cyan-800">الموعد التالي: {entry.nextRefillDate??'غير محدد'}</p></div>)}{!movements.data?.some(m=>m.movementType==='vehicle_fill')&&<p className="py-6 text-center text-sm text-slate-400">لا توجد عمليات تعبئة</p>}</div>}</section></div>
    {assignOpen&&<AssignmentDialog vehicle={v} areas={areas.data??[]} onClose={()=>setAssignOpen(false)}/>} 
    {editOpen&&<EditVehicleDialog vehicle={v} onClose={()=>setEditOpen(false)}/>} 
    {archiveOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label="أرشفة الآلية"><form onSubmit={submitArchive} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><Archive className="text-red-600"/><h2 className="mt-3 text-xl font-black">أرشفة الآلية</h2><p className="mt-1 text-sm text-slate-500">لن تُحذف البيانات أو السجلات السابقة.</p><textarea data-testid="archive-reason" value={reason} onChange={e=>setReason(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border p-3 text-sm" placeholder="سبب الأرشفة (5 أحرف على الأقل)"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setArchiveOpen(false)} className="h-10 rounded-xl border px-4 font-bold">إلغاء</button><button data-testid="archive-submit" disabled={reason.trim().length<5||archive.isPending} className="h-10 rounded-xl bg-red-600 px-5 font-black text-white disabled:opacity-40">تأكيد الأرشفة</button></div></form></div>}
    {restoreOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label="استعادة الآلية"><form onSubmit={submitRestore} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><RotateCcw className="text-emerald-700"/><h2 className="mt-3 text-xl font-black">استعادة الآلية</h2><p className="mt-1 text-sm text-slate-500">ستُعاد إلى قاعدة الآليات وتُنشأ انطلاقة فعالة جديدة مع الاحتفاظ بالسجل السابق.</p><textarea data-testid="restore-reason" value={reason} onChange={e=>setReason(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border p-3 text-sm" placeholder="سبب الاستعادة (5 أحرف على الأقل)"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setRestoreOpen(false)} className="h-10 rounded-xl border px-4 font-bold">إلغاء</button><button data-testid="restore-submit" disabled={reason.trim().length<5||restore.isPending} className="h-10 rounded-xl bg-emerald-700 px-5 font-black text-white disabled:opacity-40">تأكيد الاستعادة</button></div></form></div>}
  </section>
}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><span className="text-cyan-700 [&>svg]:size-5">{icon}</span><div><p className="text-[11px] text-slate-400">{label}</p><p className="text-sm font-black text-slate-800">{value}</p></div></div>}
