export const hrKeys = {
  all: ['hr'] as const,
  shifts: () => [...hrKeys.all, 'shifts'] as const,
  employees: (f?: unknown) => [...hrKeys.all, 'employees', f ?? {}] as const,
  employee: (id: string) => [...hrKeys.all, 'employee', id] as const,
  documents: (id: string) => [...hrKeys.all, 'documents', id] as const,
  assignments: (id: string) => [...hrKeys.all, 'assignments', id] as const,
  attendance: (f?: unknown) => [...hrKeys.all, 'attendance', f ?? {}] as const,
  leaves: (f?: unknown) => [...hrKeys.all, 'leaves', f ?? {}] as const,
  deductions: (month: string, employee?: string | null) => [...hrKeys.all, 'deductions', month, employee ?? 'all'] as const,
  audit: (f?: unknown) => [...hrKeys.all, 'audit', f ?? {}] as const,
  exports: (month?: string) => [...hrKeys.all, 'exports', month ?? 'all'] as const,
  exportRows: (id: string) => [...hrKeys.all, 'export-rows', id] as const,
  dashboard: () => [...hrKeys.all, 'dashboard'] as const,
  payrollSheet: (month: string) => [...hrKeys.all, 'payroll-sheet', month] as const,
  salaryProfile: (id: string) => [...hrKeys.all, 'salary-profile', id] as const,
  notices: () => [...hrKeys.all, 'finance-notices'] as const,
  departments: () => [...hrKeys.all, 'departments'] as const,
  me: () => [...hrKeys.all, 'me'] as const,
  policy: () => [...hrKeys.all, 'policy'] as const,
  leaveTypes: (all?: boolean) => [...hrKeys.all, 'leave-types', all ? 'all' : 'active'] as const,
  leaveRequests: (f?: unknown) => [...hrKeys.all, 'leave-requests', f ?? {}] as const,
  balance: (employeeId: string, year?: number | null) => [...hrKeys.all, 'balance', employeeId, year ?? 'current'] as const,
  ledger: (employeeId: string, year?: number | null) => [...hrKeys.all, 'ledger', employeeId, year ?? 'current'] as const,
  alerts: (month?: string | null, onlyOpen?: boolean) => [...hrKeys.all, 'alerts', month ?? 'all', onlyOpen ?? true] as const,
  leavesDashboard: () => [...hrKeys.all, 'leaves-dashboard'] as const,
}
