import type{ReactNode}from'react'
import{AlertTriangle,ArrowLeft,Boxes,CheckCircle2,Clock3,Cog,PackageCheck,Truck,Wallet,Wrench}from'lucide-react'
import{Link}from'react-router'
import{useMaintenanceCases,useMaintenanceInventory}from'@features/vehicle-operations/hooks'
const money=(value:number)=>new Intl.NumberFormat('ar-IQ').format(value)
export default function MaintenanceDashboardPage(){const cases=useMaintenanceCases(),inventory=useMaintenanceInventory(),rows=cases.data??[],items=inventory.data??[],active=rows.filter(r=>!r.completed_at),waiting=active.filter(r=>!r.arrived_at),ready=active.filter(r=>Boolean(r.readiness_approved_at)),overdue=active.filter(r=>r.expected_completion_at&&new Date(r.expected_completion_at)<new Date()),low=items.filter(i=>i.current_quantity<=i.low_stock_threshold),cost=rows.reduce((s,r)=>s+Number(r.actual_cost??0),0),avg=active.length?Math.round(active.reduce((s,r)=>s+Number(r.progress??0),0)/active.length):0
 const status=[{label:'في الطريق أو بانتظار الاستلام',value:waiting.length,color:'bg-cyan-500'},{label:'قيد الفحص والإصلاح',value:Math.max(0,active.length-waiting.length-ready.length),color:'bg-amber-500'},{label:'جاهزة للمغادرة',value:ready.length,color:'bg-emerald-500'},{label:'متأخرة عن الموعد',value:overdue.length,color:'bg-rose-500'}],max=Math.max(1,...status.map(s=>s.value))
 return <section dir="rtl" className="space-y-6" data-testid="maintenance-dashboard"><header className="rounded-[2rem] bg-gradient-to-l from-slate-950 via-amber-950 to-orange-700 p-7 text-white shadow-lg"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs text-amber-100"><Cog size={15}/>مركز إدارة الصيانة والمخزون</span><h1 className="mt-4 text-3xl font-black">لوحة قيادة الصيانة</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-amber-100">متابعة وصول الآليات والتشخيص والأعمال والقطع والكلف والجاهزية حتى تسليم الآلية.</p></header>
 <nav className="grid gap-3 sm:grid-cols-2"><Quick to="/maintenance/vehicle-cases" icon={<Wrench/>} title="حالات صيانة الآليات" hint="الاستلام والتشخيص والتحديث والتسليم" tone="border-amber-200 bg-amber-50 text-amber-800"/><Quick to="/maintenance/inventory" icon={<Boxes/>} title="مخزون قطع الصيانة" hint="الأصناف والاستلام والصرف والتركيب" tone="border-violet-200 bg-violet-50 text-violet-800"/></nav>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card icon={<Wrench/>} label="الحالات المفتوحة" value={active.length} hint="تحتاج متابعة" tone="border-amber-200 bg-amber-50 text-amber-800"/><Card icon={<Truck/>} label="بانتظار الوصول" value={waiting.length} hint="آلية في الطريق" tone="border-cyan-200 bg-cyan-50 text-cyan-800"/><Card icon={<PackageCheck/>} label="جاهزة للتسليم" value={ready.length} hint="تم اعتماد الجاهزية" tone="border-emerald-200 bg-emerald-50 text-emerald-800"/><Card icon={<Clock3/>} label="حالات متأخرة" value={overdue.length} hint="تجاوزت الموعد" tone="border-rose-200 bg-rose-50 text-rose-800"/><Card icon={<AlertTriangle/>} label="نقص المخزون" value={low.length} hint="عند أو دون الحد" tone="border-red-200 bg-red-50 text-red-800"/><Card icon={<Wallet/>} label="الكلفة المسجلة" value={money(cost)} hint="دينار عراقي" tone="border-violet-200 bg-violet-50 text-violet-800"/></div>
 <div className="grid gap-5 xl:grid-cols-3"><article className="rounded-3xl border bg-white p-6 shadow-sm xl:col-span-2"><h2 className="font-black">توزيع الحالات التشغيلية</h2><p className="mt-1 text-xs text-slate-500">حالة الآليات المفتوحة حالياً</p><div className="mt-7 space-y-5">{status.map(item=><div key={item.label} className="grid grid-cols-[12rem_1fr_3rem] items-center gap-3 text-xs"><b>{item.label}</b><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.color}`} style={{width:`${Math.max(item.value?8:0,item.value/max*100)}%`}}/></div><b className="text-left">{item.value}</b></div>)}</div></article><article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-black">متوسط تقدم الصيانة</h2><p className="mt-1 text-xs text-slate-500">لكل الحالات المفتوحة</p><div className="mx-auto mt-7 grid size-44 place-items-center rounded-full" style={{background:`conic-gradient(#f59e0b 0 ${avg}%,#e2e8f0 ${avg}% 100%)`}}><div className="grid size-28 place-items-center rounded-full bg-white"><div className="text-center"><b className="text-3xl text-amber-700">{avg}%</b><p className="text-[10px] text-slate-500">نسبة الإنجاز</p></div></div></div></article></div>
 <div className="grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border bg-white p-6"><h2 className="flex items-center gap-2 font-black"><AlertTriangle className="text-red-600"/>أصناف تحتاج إعادة تجهيز</h2><div className="mt-4 space-y-2">{low.slice(0,6).map(item=><div key={item.id} className="flex justify-between rounded-2xl bg-red-50 p-3 text-xs"><span><b>{item.item_name}</b><small className="mr-2 text-red-500">{item.sku}</small></span><b className="text-red-800">{item.current_quantity} {item.unit}</b></div>)}{!low.length&&<p className="flex items-center justify-center gap-2 py-10 text-sm text-emerald-700"><CheckCircle2/>جميع الأصناف فوق الحد الأدنى.</p>}</div></article><article className="rounded-3xl border bg-white p-6"><h2 className="font-black">الحالات الأعلى أولوية</h2><div className="mt-4 space-y-2">{active.slice(0,6).map(item=><Link key={item.case_id} to="/maintenance/vehicle-cases" className="flex items-center justify-between rounded-2xl border p-3 text-xs hover:border-amber-300"><span><b>{item.vehicle_name}</b><small className="mr-2 text-slate-500">DB {item.db_number}</small></span><span className="rounded-full bg-amber-50 px-2 py-1 font-bold text-amber-800">{item.progress}%</span></Link>)}{!active.length&&<p className="py-10 text-center text-sm text-slate-500">لا توجد حالات صيانة مفتوحة.</p>}</div></article></div></section>}
function Card({icon,label,value,hint,tone}:{icon:ReactNode;label:string;value:string|number;hint:string;tone:string}){return <article className={`rounded-3xl border p-5 shadow-sm ${tone}`}><span className="grid size-11 place-items-center rounded-2xl bg-white/80">{icon}</span><b className="mt-4 block text-3xl text-slate-950">{value}</b><p className="mt-1 text-xs font-black text-slate-700">{label}</p><small className="text-[10px] opacity-70">{hint}</small></article>}
function Quick({to,icon,title,hint,tone}:{to:string;icon:ReactNode;title:string;hint:string;tone:string}){return <Link to={to} className="group flex items-center gap-4 rounded-3xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className={`grid size-12 place-items-center rounded-2xl border ${tone}`}>{icon}</span><span className="flex-1"><b>{title}</b><small className="mt-1 block text-slate-500">{hint}</small></span><ArrowLeft className="text-slate-300 group-hover:text-amber-700"/></Link>}
