-- ═══════════════════════════════════════════════════════════════
-- 00014 · سجل التدقيق — Generic Audit Trigger
-- القراءة: super_admin فقط. الكتابة: عبر الـ trigger فقط (SECURITY DEFINER).
-- ═══════════════════════════════════════════════════════════════

create table public.audit_logs (
  id             bigint generated by default as identity primary key,
  table_name     text not null,
  record_id      text,
  operation      text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  old_row        jsonb,
  new_row        jsonb,
  changed_fields jsonb,
  actor_id       uuid,
  actor_role     text,
  created_at     timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

create policy "audit: قراءة بواسطة Super Admin" on public.audit_logs
  for select to authenticated
  using (app.has_role(array['super_admin']));

-- لا سياسات INSERT/UPDATE/DELETE → محصور بالـ trigger

create or replace function app.audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, app
as $$
declare
  changed jsonb;
begin
  changed = null;

  if tg_op = 'UPDATE' then
    select coalesce(jsonb_object_agg(k, new_val), '{}'::jsonb)
    into changed
    from jsonb_each(to_jsonb(new)) new_e(k, new_val)
    join jsonb_each(to_jsonb(old)) old_e(k, old_val) using (k)
    where new_val is distinct from old_val;
  end if;

  insert into public.audit_logs
    (table_name, record_id, operation, old_row, new_row, changed_fields, actor_id, actor_role)
  values
    (tg_table_name,
     coalesce((to_jsonb(new) ->> 'id'), (to_jsonb(old) ->> 'id')),
     tg_op,
     case when tg_op <> 'INSERT' then to_jsonb(old) end,
     case when tg_op <> 'DELETE' then to_jsonb(new) end,
     changed,
     auth.uid(),
     app.current_role());

  return coalesce(new, old);
end;
$$;

-- إرفاق الـ trigger بالجداول الحساسة دفعة واحدة
do $$
declare
  t text;
begin
  foreach t in array array['employees', 'departments', 'requests', 'payrolls',
                           'payslips', 'budget_allocations', 'it_assets', 'user_roles']
  loop
    execute format('
      create trigger trg_audit_%s
        after insert or update or delete on public.%I
        for each row execute function app.audit_trigger();
    ', t, t);
  end loop;
end;
$$;

create index idx_audit_table_record on public.audit_logs (table_name, record_id);
create index idx_audit_created      on public.audit_logs (created_at desc);
create index idx_audit_actor        on public.audit_logs (actor_id);
