-- ═══════════════════════════════════════════════════════════════
-- 00017 · سجل أخطاء التطبيق (وحدة قاعدة البيانات — البوابة التقنية)
--  · أي مستخدم مصادق يبلّغ عن خطأ (insert صفه هو فقط)
--  · القراءة والحل: it_admin / super_admin حصراً
-- ═══════════════════════════════════════════════════════════════

create table public.app_errors (
  id          bigint generated by default as identity primary key,
  error_type  text not null default 'runtime'
              check (error_type in ('runtime', 'network', 'validation', 'auth')),
  message     text not null,
  stack       text,
  url         text,
  user_agent  text,
  user_id     uuid references auth.users (id) on delete set null,
  context     jsonb not null default '{}',
  resolved    boolean not null default false,
  resolved_by uuid references auth.users (id) on delete set null,
  created_at  timestamptz not null default now()
);

alter table public.app_errors enable row level security;

-- البلاغ: كل مصادق يُدرج خطأ باسمه هو فقط
create policy "app_errors: إبلاغ باسمي" on public.app_errors
  for insert to authenticated
  with check (user_id = auth.uid());

-- القراءة والحل: IT / Super Admin
create policy "app_errors: قراءة بواسطة IT" on public.app_errors
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "app_errors: حل بواسطة IT" on public.app_errors
  for update to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create index idx_app_errors_created  on public.app_errors (created_at desc);
create index idx_app_errors_open     on public.app_errors (created_at desc) where not resolved;
create index idx_app_errors_type     on public.app_errors (error_type);
