-- ═══════════════════════════════════════════════════════════════
-- 00012 · تذاكر الدعم التقني
-- ═══════════════════════════════════════════════════════════════

create table public.it_tickets (
  id            uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  created_by    uuid not null references public.employees (id) on delete cascade,
  assigned_to   uuid references public.employees (id) on delete set null,
  title         text not null,
  description   text,
  category      text not null default 'hardware'
                check (category in ('hardware', 'software', 'network', 'account', 'other')),
  priority      text not null default 'medium'
                check (priority in ('low', 'medium', 'high', 'critical')),
  status        text not null default 'open'
                check (status in ('open', 'in_progress', 'resolved', 'closed', 'cancelled')),
  resolved_at   timestamptz,
  version       integer not null default 1,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.it_tickets enable row level security;

create policy "tickets: قراءة تذكرتي" on public.it_tickets
  for select to authenticated
  using (created_by = (select app.current_employee_id()));

create policy "tickets: قراءة كاملة بواسطة IT" on public.it_tickets
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "tickets: فتح تذكرة" on public.it_tickets
  for insert to authenticated
  with check (created_by = (select app.current_employee_id()));

create policy "tickets: إدارة بواسطة IT" on public.it_tickets
  for update to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

-- صاحب التذكرة يستطيع إلغاء تذكرته وهي open فقط
create policy "tickets: إلغاء تذكرتي المفتوحة" on public.it_tickets
  for update to authenticated
  using      (created_by = (select app.current_employee_id()) and status = 'open')
  with check (created_by = (select app.current_employee_id()) and status = 'open');

create index idx_tickets_creator   on public.it_tickets (created_by);
create index idx_tickets_assignee  on public.it_tickets (assigned_to);
create index idx_tickets_status    on public.it_tickets (status, priority);

create trigger trg_tickets_updated_at
  before update on public.it_tickets for each row execute function app.set_updated_at();
create trigger trg_tickets_version
  before update on public.it_tickets for each row execute function app.bump_version();
