-- ═══════════════════════════════════════════════════════════════
-- 00016 · أمن تسجيل الدخول — طبقة الخادم
--  · سجل محاولات الدخول + إقفال تلقائي (5 محاولات فاشلة → قفل 15 دقيقة)
--  · الدوال SECURITY DEFINER لأن الدخول يحدث قبل المصادقة (anon)
--  · الجدول بلا سياسات RLS → محصور تماماً بالدوال (لا قراءة مباشرة إطلاقاً)
-- طبقات الحماية الموازية (خارج هذه الـ migration):
--  · Rate limiting مدمج في Supabase Auth (لكل IP/بريد)
--  · CAPTCHA اختياري (انظر config.toml) · حارس المتصفح في الواجهة
-- ═══════════════════════════════════════════════════════════════

create table public.login_attempts (
  id           bigint generated by default as identity primary key,
  email        text not null,
  user_id      uuid references auth.users (id) on delete set null,
  ip_address   inet,
  success      boolean not null default false,
  attempted_at timestamptz not null default now()
);

alter table public.login_attempts enable row level security;

-- لا سياسات — لا أحد يقرأ سجل المحاولات مباشرة (super_admin عبر audit فقط لاحقاً)

create index idx_login_attempts_email_time on public.login_attempts (email, attempted_at desc);
create index idx_login_attempts_cleanup    on public.login_attempts (attempted_at);

-- ── تسجيل محاولة (فاشلة أو ناجحة) ──
create or replace function app.record_login_attempt(p_email text, p_success boolean)
returns void
language plpgsql
security definer
set search_path = public, app
as $$
begin
  insert into public.login_attempts (email, success) values (lower(p_email), p_success);

  -- نظافة دورية: لا نحتفظ بسجل أقدم من 30 يوماً
  delete from public.login_attempts
  where attempted_at < now() - interval '30 days';

  -- النجاح يمحو عدّاد الفشل لهذا البريد
  if p_success then
    delete from public.login_attempts
    where email = lower(p_email) and not success;
  end if;
end;
$$;

-- ── هل الدخول مقفل لهذا البريد؟ ──
create or replace function app.is_login_locked(p_email text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select (
    select count(*)
    from public.login_attempts
    where email = lower(p_email)
      and not success
      and attempted_at > now() - interval '15 minutes'
  ) >= 5;
$$;

-- ── الثواني المتبقية للقفل (لواجهة العد التنازلي) ──
create or replace function app.login_lock_remaining_seconds(p_email text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(
    0,
    extract(epoch from (
      (select attempted_at + interval '15 minutes'
       from public.login_attempts
       where email = lower(p_email)
         and not success
         and attempted_at > now() - interval '15 minutes'
       order by attempted_at desc
       limit 1)
      - now()
    ))::integer
  );
$$;

-- ── فتح القفل إدارياً (super_admin / دعم فني) ──
create or replace function app.unlock_login(p_email text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.login_attempts where email = lower(p_email) and not success;
$$;

revoke all on function app.unlock_login from public, anon, authenticated;
grant execute on function app.unlock_login to authenticated;

grant execute on function app.record_login_attempt(text, boolean)       to anon, authenticated;
grant execute on function app.is_login_locked(text)                     to anon, authenticated;
grant execute on function app.login_lock_remaining_seconds(text)        to anon, authenticated;

-- سجل تدقيق لأحداث القفل (يُرفق في 00014 آلياً؟ لا — login_attempts غير مشمول؛
-- القفل حدث أمني حساس: نسجله عند التفعيل الأول للنظام إذا طلب الأمن)
comment on table public.login_attempts is 'سجل محاولات الدخول — وصول فقط عبر دوال app.* (SECURITY DEFINER)';
