-- ═══════════════════════════════════════════════════════════════
-- 00025 · التكاملات: أجهزة البصمة (ZKTeco ADMS) + GPS تتبع الشاحنات
-- ═══════════════════════════════════════════════════════════════

-- ── أجهزة البصمة ──
create table public.biometric_devices (
  id            uuid primary key default gen_random_uuid(),
  serial_number text not null unique,
  name          text not null,
  branch_id     uuid references public.branches (id) on delete set null,
  location_hint text,
  is_active     boolean not null default true,
  last_seen_at  timestamptz,
  firmware      text,
  registered_by uuid references auth.users (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- الرفع الخام من ADMS (logging قبل التحويل — تتبع كامل)
create table public.biometric_pushes (
  id           bigint generated by default as identity primary key,
  device_sn    text not null,
  table_name   text,                                -- ATTLOG / OPERLOG / ATTPHOTO
  raw_payload  text not null,
  parsed_ok    boolean not null default false,
  error_note   text,
  received_at  timestamptz not null default now()
);

alter table public.biometric_devices enable row level security;
alter table public.biometric_pushes  enable row level security;

-- القراءة: IT فقط (الجهاز نفسه لا يقرأ — يكتب عبر الدالة)
create policy "bio: قراءة بواسطة IT" on public.biometric_devices
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "bio: إدارة بواسطة IT" on public.biometric_devices
  for all to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create policy "bio_pushes: قراءة بواسطة IT" on public.biometric_pushes
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create index idx_bio_pushes_device on public.biometric_pushes (device_sn, received_at desc);
create index idx_bio_devices_sn    on public.biometric_devices (serial_number);

-- ── GPS: المزودون · الشاحنات · المواقع · الأحداث ──
create table public.gps_providers (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  type        text not null default 'traccar'
              check (type in ('traccar', 'osmand', 'custom_webhook', 'vendor_api')),
  api_key     text,                                  -- مفتاح التحقق من نداءاتهم
  webhook_url text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.vehicles (
  id               uuid primary key default gen_random_uuid(),
  plate            text not null unique,
  name             text not null,
  branch_id        uuid references public.branches (id) on delete set null,
  gps_provider_id  uuid references public.gps_providers (id) on delete set null,
  device_unique_id text,                              -- uniqueId في مزود التتبع
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table public.vehicle_positions (
  id           bigint generated by default as identity primary key,
  vehicle_id   uuid not null references public.vehicles (id) on delete cascade,
  latitude     double precision not null,
  longitude    double precision not null,
  speed_kmh    double precision,
  heading      double precision,
  ignition     boolean,
  fix_time     timestamptz not null,
  received_at  timestamptz not null default now()
);

create table public.gps_events (
  id          bigint generated by default as identity primary key,
  vehicle_id  uuid references public.vehicles (id) on delete cascade,
  event_type  text not null
              check (event_type in ('device_online', 'device_offline', 'geofence_enter',
                                    'geofence_exit', 'overspeed', 'sos')),
  payload     jsonb not null default '{}',
  occurred_at timestamptz not null default now()
);

alter table public.gps_providers      enable row level security;
alter table public.vehicles           enable row level security;
alter table public.vehicle_positions  enable row level security;
alter table public.gps_events         enable row level security;

-- القراءة: IT + المالية (تكاليف تشغيل) + super_admin — الإدارة IT فقط
create policy "gps_prov: قراءة IT" on public.gps_providers
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "gps_prov: إدارة IT" on public.gps_providers
  for all to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create policy "vehicles: قراءة للمصادقين" on public.vehicles
  for select to authenticated using (true);

create policy "vehicles: إدارة IT" on public.vehicles
  for all to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create policy "positions: قراءة IT" on public.vehicle_positions
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "events: قراءة IT" on public.gps_events
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create index idx_positions_vehicle_time on public.vehicle_positions (vehicle_id, fix_time desc);
create index idx_events_vehicle_time    on public.gps_events (vehicle_id, occurred_at desc);
create index idx_vehicles_provider      on public.vehicles (gps_provider_id);

-- ── سجل التكاملات + إعدادات النظام ──
create table public.integration_logs (
  id           bigint generated by default as identity primary key,
  provider     text not null,                        -- biometric / gps:{name}
  direction    text not null check (direction in ('inbound', 'outbound')),
  endpoint     text,
  status       text not null default 'success'
               check (status in ('success', 'error', 'rejected')),
  payload      jsonb not null default '{}',
  error_note   text,
  created_at   timestamptz not null default now()
);

create table public.system_settings (
  key        text primary key,
  value      jsonb not null default '{}',
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.integration_logs enable row level security;
alter table public.system_settings  enable row level security;

create policy "ilogs: قراءة IT" on public.integration_logs
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "settings: قراءة للمصادقين" on public.system_settings
  for select to authenticated using (true);

create policy "settings: إدارة IT" on public.system_settings
  for all to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create index idx_ilogs_provider_time on public.integration_logs (provider, created_at desc);

-- ── حالة الجهاز عبر دالة آمنة (يستدعيها المستقبل بدون مصادقة) ──
create or replace function app.biometric_touch(p_sn text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.biometric_devices
  set last_seen_at = now()
  where serial_number = p_sn and is_active;
$$;

revoke all on function app.biometric_touch(text) from public, anon, authenticated;

create trigger trg_vehicles_updated_at
  before update on public.vehicles for each row execute function app.set_updated_at();

do $$ begin
  execute format('create trigger trg_audit_biometric_devices after insert or update or delete on public.biometric_devices
                  for each row execute function app.audit_trigger();');
end $$;
