-- ═══════════════════════════════════════════════════════════════
-- 00030 · قياسات حية — latency الاتصال يُسجل لرسم تاريخي حقيقي
-- ═══════════════════════════════════════════════════════════════

create table public.connection_samples (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users (id) on delete set null,
  latency_ms  integer not null check (latency_ms >= 0),
  sampled_at  timestamptz not null default now()
);

alter table public.connection_samples enable row level security;

create policy "conn: قراءة IT" on public.connection_samples
  for select to authenticated
  using (app.has_role(array['it_admin','super_admin']));

create policy "conn: إدراج باسمي" on public.connection_samples
  for insert to authenticated
  with check (user_id = auth.uid());

create index idx_conn_time on public.connection_samples (sampled_at desc);

-- نظافة: آخر 24 ساعة فقط
create or replace function app.connection_cleanup()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.connection_samples where sampled_at < now() - interval '24 hours';
$$;

-- ═══ RPC: تسجيل قياس + قراءة التاريخ (IT) ═══
create or replace function public.connection_sample(p_latency_ms integer)
returns void
language sql
security definer
set search_path = public, app
as $$
  insert into public.connection_samples (user_id, latency_ms)
  values (auth.uid(), greatest(0, least(p_latency_ms, 60000)));
  select app.connection_cleanup();
$$;

create or replace function public.connection_history()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case
    when not app.has_role(array['it_admin','super_admin']) then '[]'::jsonb
    else coalesce((
      select jsonb_agg(jsonb_build_object(
        'at', s.sampled_at, 'ms', s.latency_ms
      ) order by s.sampled_at)
      from (
        select sampled_at, latency_ms from public.connection_samples
        where sampled_at > now() - interval '2 hours'
        order by sampled_at desc limit 100
      ) s
    ), '[]'::jsonb)
  end;
$$;

grant execute on function public.connection_sample(integer) to authenticated;
grant execute on function public.connection_history()     to authenticated;
