-- ═══════════════════════════════════════════════════════════════
-- 00038 · FlowBridge — جسر الأحداث الحقيقية (بلا بيانات وهمية)
--  المشكلة: audit_logs مقصور على super_admin (بيانات حساسة: رواتب/رواتب
--  كاملة old_row/new_row)، وFlowBridge صفحة IT (it_admin). الحل: تتابع
--  (relay) ضيّق يُسجّل فقط (المصدر/الجدول أو المزوّد/العملية/الحالة/الوقت)
--  بلا أي حمولة حساسة — يخدم بث حي آمن لتحريك التصميم فقط.
--
--  · flowbridge_events        : الحدث الضيق المُبَث (Realtime)
--  · flowbridge_event_bindings: يربط IT حدثاً حقيقياً (جدول+عملية أو
--    مزوّد+حالة) بمعرّف تدفق (flowId) في مخطط المصمم — بلا هذا الربط
--    لا يمكن معرفة أي تدفق يجب تحريكه عند وقوع أي حدث حقيقي.
-- ═══════════════════════════════════════════════════════════════

create table public.flowbridge_events (
  id           bigint generated by default as identity primary key,
  source       text not null check (source in ('audit', 'integration')),
  table_name   text,          -- من audit_logs (tg_table_name)
  operation    text,          -- INSERT/UPDATE/DELETE من audit_logs
  provider     text,          -- من integration_logs (biometric / gps:...)
  status       text,          -- success/error/rejected من integration_logs
  actor_role   text,          -- من audit_logs فقط (بلا actor_id — لا هوية)
  occurred_at  timestamptz not null default now()
);

comment on table public.flowbridge_events is
  'تتابع ضيق وآمن لأحداث حقيقية (بلا حمولة/هوية) — يغذي بث FlowBridge الحي';

alter table public.flowbridge_events enable row level security;

create policy "fb_events: قراءة بواسطة IT" on public.flowbridge_events
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

-- لا سياسات إدراج/تعديل/حذف من العميل → محصور بالـ triggers أدناه (security definer)

create index idx_fb_events_occurred on public.flowbridge_events (occurred_at desc);
create index idx_fb_events_table    on public.flowbridge_events (table_name, operation);
create index idx_fb_events_provider on public.flowbridge_events (provider, status);

-- ── تتابع من audit_logs (بلا old_row/new_row/actor_id) ──
create or replace function app.flowbridge_relay_audit()
returns trigger
language plpgsql
security definer
set search_path = public, app
as $$
begin
  -- لا نُتابع أحداث flowbridge_state نفسها (منع حلقة ضجيج ذاتية)
  if new.table_name = 'flowbridge_state' then
    return new;
  end if;
  insert into public.flowbridge_events (source, table_name, operation, actor_role)
  values ('audit', new.table_name, new.operation, new.actor_role);
  return new;
end;
$$;

create trigger trg_flowbridge_relay_audit
  after insert on public.audit_logs
  for each row execute function app.flowbridge_relay_audit();

-- ── تتابع من integration_logs (بلا payload/error_note) ──
create or replace function app.flowbridge_relay_integration()
returns trigger
language plpgsql
security definer
set search_path = public, app
as $$
begin
  insert into public.flowbridge_events (source, provider, status)
  values ('integration', new.provider, new.status);
  return new;
end;
$$;

create trigger trg_flowbridge_relay_integration
  after insert on public.integration_logs
  for each row execute function app.flowbridge_relay_integration();

-- ── ربط الأحداث الحقيقية بتدفقات المخطط (يُدار من صفحة الإعدادات) ──
create table public.flowbridge_event_bindings (
  id               uuid primary key default gen_random_uuid(),
  flow_id          text not null,             -- معرّف التدفق داخل graph.flows[].id
  source           text not null check (source in ('audit', 'integration')),
  match_table      text,                       -- عند source='audit'
  match_operation  text check (match_operation in ('INSERT', 'UPDATE', 'DELETE')),
  match_provider   text,                       -- عند source='integration'
  match_status     text check (match_status in ('success', 'error', 'rejected')),
  created_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),

  constraint fb_binding_audit_shape
    check (source <> 'audit' or match_table is not null),
  constraint fb_binding_integration_shape
    check (source <> 'integration' or match_provider is not null)
);

comment on table public.flowbridge_event_bindings is
  'ربط تدفق في المخطط بحدث حقيقي (جدول+عملية أو مزوّد+حالة) — أساس pulse() الحي';

alter table public.flowbridge_event_bindings enable row level security;

create policy "fb_bindings: قراءة بواسطة IT" on public.flowbridge_event_bindings
  for select to authenticated
  using (app.has_role(array['it_admin', 'super_admin']));

create policy "fb_bindings: إدارة بواسطة IT" on public.flowbridge_event_bindings
  for all to authenticated
  using      (app.has_role(array['it_admin', 'super_admin']))
  with check (app.has_role(array['it_admin', 'super_admin']));

create index idx_fb_bindings_audit       on public.flowbridge_event_bindings (match_table, match_operation);
create index idx_fb_bindings_integration on public.flowbridge_event_bindings (match_provider, match_status);

-- ═══ Realtime: بث flowbridge_events فقط (ضيق وآمن) إن كانت منصة Supabase ═══
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    execute 'alter publication supabase_realtime add table public.flowbridge_events';
  end if;
exception
  when duplicate_object then null;
end $$;
