-- 00063 · أرشفة بريد الشكاوى كمجلد وطلب حذف نهائي بموافقة مدير النظام.
alter table public.complaint_inbox_messages add column archived_at timestamptz,add column archive_reason text;
create table public.complaint_archive_folders(id uuid primary key default gen_random_uuid(),inbox_message_id uuid unique references public.complaint_inbox_messages(id)on delete set null,subject text not null,sender_email text not null,sector text not null check(sector in('karrada','zaafaraniya')),snapshot jsonb not null default'{}',archived_by uuid references auth.users(id),archived_at timestamptz not null default now(),restored_at timestamptz,permanently_deleted_at timestamptz);
create table public.complaint_deletion_requests(id uuid primary key default gen_random_uuid(),folder_id uuid not null references public.complaint_archive_folders(id)on delete cascade,reason text not null check(length(trim(reason))>=5),status text not null default'pending'check(status in('pending','approved','rejected','executed','failed')),requested_by uuid not null references auth.users(id),requested_at timestamptz not null default now(),decided_by uuid references auth.users(id),decided_at timestamptz,decision_note text,executed_at timestamptz,error_message text);
create index idx_complaint_archive_folders_archived_at on public.complaint_archive_folders(archived_at desc);
create index idx_complaint_deletion_requests_status on public.complaint_deletion_requests(status,requested_at desc);
create unique index uq_complaint_deletion_requests_active_folder on public.complaint_deletion_requests(folder_id)where status in('pending','approved');
alter table public.complaint_archive_folders enable row level security;alter table public.complaint_deletion_requests enable row level security;
create policy "complaint folders read" on public.complaint_archive_folders for select to authenticated using(app.has_role(array['complaints_officer','it_admin','super_admin']));
create policy "complaint requests read" on public.complaint_deletion_requests for select to authenticated using(app.has_role(array['complaints_officer','it_admin','super_admin']));
create or replace function public.complaint_archive_email(p_message_id uuid,p_reason text)returns uuid language plpgsql security definer set search_path=public,app as $$declare f uuid;m public.complaint_inbox_messages%rowtype;begin if not app.has_role(array['complaints_officer','super_admin'])then raise exception'COMPLAINT_ARCHIVE_FORBIDDEN';end if;if length(trim(coalesce(p_reason,'')))<5 then raise exception'COMPLAINT_ARCHIVE_REASON_REQUIRED';end if;select*into m from public.complaint_inbox_messages where id=p_message_id for update;if not found then raise exception'COMPLAINT_EMAIL_NOT_FOUND';end if;insert into public.complaint_archive_folders(inbox_message_id,subject,sender_email,sector,snapshot,archived_by)values(m.id,coalesce(m.subject,'دون موضوع'),m.sender_email,m.source_sector,jsonb_build_object('receivedAt',m.received_at,'attachmentCount',m.attachment_count),auth.uid())on conflict(inbox_message_id)do update set restored_at=null,archived_at=now(),archived_by=auth.uid()returning id into f;update public.complaint_inbox_messages set archived_at=now(),archive_reason=trim(p_reason)where id=m.id;update public.complaints set status='archived',archived_at=now()where inbox_message_id=m.id;return f;end$$;
create or replace function public.complaint_restore_email(p_folder_id uuid)returns void language plpgsql security definer set search_path=public,app as $$declare mid uuid;begin if not app.has_role(array['complaints_officer','super_admin'])then raise exception'COMPLAINT_RESTORE_FORBIDDEN';end if;select inbox_message_id into mid from public.complaint_archive_folders where id=p_folder_id and restored_at is null and permanently_deleted_at is null for update;if mid is null then raise exception'COMPLAINT_FOLDER_NOT_RESTORABLE';end if;update public.complaint_archive_folders set restored_at=now()where id=p_folder_id;update public.complaint_inbox_messages set archived_at=null,archive_reason=null where id=mid;update public.complaints set status=case when exists(select 1 from public.complaint_items where complaint_id=complaints.id and status in('processed','quality_review'))then'quality_review'else'under_review'end,archived_at=null where inbox_message_id=mid;end$$;
create or replace function public.complaint_request_permanent_deletion(p_folder_id uuid,p_reason text)returns uuid language plpgsql security definer set search_path=public,app as $$declare r uuid;begin if not app.has_role(array['complaints_officer','super_admin'])then raise exception'COMPLAINT_DELETE_REQUEST_FORBIDDEN';end if;if length(trim(coalesce(p_reason,'')))<5 then raise exception'COMPLAINT_DELETE_REASON_REQUIRED';end if;if not exists(select 1 from public.complaint_archive_folders where id=p_folder_id and restored_at is null and permanently_deleted_at is null)then raise exception'COMPLAINT_FOLDER_NOT_ARCHIVED';end if;insert into public.complaint_deletion_requests(folder_id,reason,requested_by)values(p_folder_id,trim(p_reason),auth.uid())returning id into r;insert into public.notifications(user_id,title,body,type,link)select ur.user_id,'طلب حذف نهائي لشكاوى','طلب جديد يحتاج مراجعة مدير النظام','warning','/it/archive'from public.user_roles ur where ur.role='it_admin';return r;end$$;
create or replace function public.complaint_decide_deletion(p_request_id uuid,p_approved boolean,p_note text)returns void language plpgsql security definer set search_path=public,app as $$begin if not app.has_role(array['super_admin'])then raise exception'COMPLAINT_DELETE_APPROVAL_FORBIDDEN';end if;update public.complaint_deletion_requests set status=case when p_approved then'approved'else'rejected'end,decided_by=auth.uid(),decided_at=now(),decision_note=nullif(trim(p_note),'')where id=p_request_id and status='pending';if not found then raise exception'COMPLAINT_DELETE_REQUEST_NOT_PENDING';end if;end$$;
revoke all on function public.complaint_archive_email(uuid,text),public.complaint_restore_email(uuid),public.complaint_request_permanent_deletion(uuid,text),public.complaint_decide_deletion(uuid,boolean,text)from public,anon;grant execute on function public.complaint_archive_email(uuid,text),public.complaint_restore_email(uuid),public.complaint_request_permanent_deletion(uuid,text),public.complaint_decide_deletion(uuid,boolean,text)to authenticated;
