-- توحيد العطل مع رحلة الآلية + سجل صيانة تفصيلي لا يستبدل التحديثات السابقة.
alter table public.vehicle_maintenance_cases
 add column assigned_technician text,
 add column estimated_cost numeric(14,2) check(estimated_cost is null or estimated_cost>=0),
 add column actual_cost numeric(14,2) check(actual_cost is null or actual_cost>=0),
 add column delay_reason text;

create table public.vehicle_maintenance_updates(
 id uuid primary key default gen_random_uuid(),case_id uuid not null references public.vehicle_maintenance_cases(id) on delete cascade,status text not null,progress smallint not null check(progress between 0 and 100),diagnosis text,work_notes text,parts_notes text,assigned_technician text,estimated_cost numeric(14,2),actual_cost numeric(14,2),delay_reason text,expected_completion_at timestamptz,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),
 constraint maintenance_update_text_limits check(length(coalesce(diagnosis,''))<=3000 and length(coalesce(work_notes,''))<=5000 and length(coalesce(parts_notes,''))<=3000 and length(coalesce(delay_reason,''))<=2000));
create index maintenance_updates_case_time on public.vehicle_maintenance_updates(case_id,created_at desc);
alter table public.vehicle_maintenance_updates enable row level security;
create policy "maintenance updates authorized read" on public.vehicle_maintenance_updates for select to authenticated using(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or exists(select 1 from public.vehicle_maintenance_cases c where c.id=case_id and c.manager_id=auth.uid()));
create trigger trg_audit_maintenance_updates after insert or update or delete on public.vehicle_maintenance_updates for each row execute function app.audit_trigger();

create table public.vehicle_maintenance_parts(
 id uuid primary key default gen_random_uuid(),case_id uuid not null references public.vehicle_maintenance_cases(id) on delete cascade,part_name text not null,quantity numeric(12,3) not null check(quantity>0),unit text not null default 'قطعة',unit_cost numeric(14,2) check(unit_cost is null or unit_cost>=0),notes text,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),constraint maintenance_part_name_check check(length(trim(part_name)) between 2 and 200));
create index maintenance_parts_case on public.vehicle_maintenance_parts(case_id,created_at);
alter table public.vehicle_maintenance_parts enable row level security;
create policy "maintenance parts authorized read" on public.vehicle_maintenance_parts for select to authenticated using(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or exists(select 1 from public.vehicle_maintenance_cases c where c.id=case_id and c.manager_id=auth.uid()));
create trigger trg_audit_maintenance_parts after insert or update or delete on public.vehicle_maintenance_parts for each row execute function app.audit_trigger();

insert into public.vehicle_maintenance_updates(case_id,status,progress,diagnosis,work_notes,parts_notes,expected_completion_at,created_at,created_by)
select c.id,c.status,c.progress,c.diagnosis,c.work_notes,c.parts_notes,c.expected_completion_at,c.updated_at,coalesce((select arrived_by from public.vehicle_trip_legs where departure_id=c.departure_id and destination_type='maintenance' order by sequence_no desc limit 1),c.manager_id) from public.vehicle_maintenance_cases c;

drop function if exists public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz);
create function public.maintenance_update_case(p_case_id uuid,p_status text,p_progress integer,p_diagnosis text default null,p_work_notes text default null,p_parts_notes text default null,p_expected_completion_at timestamptz default null,p_assigned_technician text default null,p_estimated_cost numeric default null,p_actual_cost numeric default null,p_delay_reason text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;begin
 if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_status not in('at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready') or p_progress not between 0 and 100 then raise exception 'MAINTENANCE_UPDATE_INVALID';end if;if p_actual_cost is not null and p_actual_cost<0 or p_estimated_cost is not null and p_estimated_cost<0 then raise exception 'MAINTENANCE_COST_INVALID';end if;
 update public.vehicle_maintenance_cases set status=p_status,progress=p_progress,diagnosis=nullif(trim(coalesce(p_diagnosis,'')),''),work_notes=nullif(trim(coalesce(p_work_notes,'')),''),parts_notes=nullif(trim(coalesce(p_parts_notes,'')),''),expected_completion_at=p_expected_completion_at,assigned_technician=nullif(trim(coalesce(p_assigned_technician,'')),''),estimated_cost=p_estimated_cost,actual_cost=p_actual_cost,delay_reason=nullif(trim(coalesce(p_delay_reason,'')),''),ready_at=case when p_status='ready' then coalesce(ready_at,now()) else ready_at end,updated_at=now() where id=p_case_id and arrived_at is not null and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;
 insert into public.vehicle_maintenance_updates(case_id,status,progress,diagnosis,work_notes,parts_notes,assigned_technician,estimated_cost,actual_cost,delay_reason,expected_completion_at,created_by) values(c.id,c.status,c.progress,c.diagnosis,c.work_notes,c.parts_notes,c.assigned_technician,c.estimated_cost,c.actual_cost,c.delay_reason,c.expected_completion_at,u);return c;end$$;

create or replace function public.maintenance_add_part(p_case_id uuid,p_part_name text,p_quantity numeric,p_unit text default 'قطعة',p_unit_cost numeric default null,p_notes text default null)
returns public.vehicle_maintenance_parts language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();r public.vehicle_maintenance_parts;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if length(trim(coalesce(p_part_name,'')))<2 or p_quantity<=0 or p_unit_cost<0 then raise exception 'MAINTENANCE_PART_INVALID';end if;if not exists(select 1 from public.vehicle_maintenance_cases where id=p_case_id and completed_at is null) then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;insert into public.vehicle_maintenance_parts(case_id,part_name,quantity,unit,unit_cost,notes,created_by) values(p_case_id,trim(p_part_name),p_quantity,coalesce(nullif(trim(p_unit),''),'قطعة'),p_unit_cost,nullif(trim(coalesce(p_notes,'')),''),u) returning * into r;return r;end$$;

create or replace function public.maintenance_case_timeline(p_case_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public,app as $$declare c public.vehicle_maintenance_cases;begin select * into c from public.vehicle_maintenance_cases where id=p_case_id;if not found or not(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or c.manager_id=auth.uid()) then raise exception 'MAINTENANCE_CASE_FORBIDDEN';end if;return jsonb_build_object('case',to_jsonb(c),'updates',coalesce((select jsonb_agg(to_jsonb(u) order by u.created_at desc) from public.vehicle_maintenance_updates u where u.case_id=c.id),'[]'::jsonb),'parts',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at) from public.vehicle_maintenance_parts p where p.case_id=c.id),'[]'::jsonb),'legs',coalesce((select jsonb_agg(to_jsonb(l) order by l.sequence_no) from public.vehicle_trip_legs l where l.departure_id=c.departure_id),'[]'::jsonb));end$$;

create or replace function public.maintenance_case_days(p_limit integer default 60)
returns table(case_day date,total_count bigint,open_count bigint) language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_limit not between 1 and 365 then raise exception 'MAINTENANCE_DAY_LIMIT_INVALID';end if;return query with days as(select(current_date-g)::date as case_date from generate_series(0,p_limit-1)g) select x.case_date,count(c.id),count(c.id)filter(where c.completed_at is null) from days x join public.vehicle_maintenance_cases c on c.reported_at<x.case_date+1 and(c.completed_at is null or c.completed_at>=x.case_date) group by x.case_date order by x.case_date desc;end$$;
create or replace function public.maintenance_cases_for_day(p_day date)
returns table(case_id uuid,departure_id uuid,breakdown_id uuid,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text,status text,fault_type text,priority text,reported_at timestamptz,arrived_at timestamptz,diagnosis text,work_notes text,parts_notes text,progress smallint,expected_completion_at timestamptz,ready_at timestamptz,departed_maintenance_at timestamptz,completed_at timestamptz,assigned_technician text,estimated_cost numeric,actual_cost numeric,delay_reason text)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;return query select c.id,c.departure_id,c.breakdown_id,c.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,se.name,d.recipient_manager_name,c.status,c.fault_type,c.priority,c.reported_at,c.arrived_at,c.diagnosis,c.work_notes,c.parts_notes,c.progress,c.expected_completion_at,c.ready_at,c.departed_maintenance_at,c.completed_at,c.assigned_technician,c.estimated_cost,c.actual_cost,c.delay_reason from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join public.sectors se on se.id=d.sector_id where c.reported_at<p_day+1 and(c.completed_at is null or c.completed_at>=p_day) order by(c.completed_at is null)desc,c.reported_at desc;end$$;

-- منع إغلاق العطل القديم خارج دورة الصيانة المرتبطة.
create or replace function public.sector_return_vehicle_to_work(p_breakdown_id uuid,p_resolution_notes text default null)
returns public.sector_breakdowns language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();r public.sector_breakdowns;begin if not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;if exists(select 1 from public.vehicle_maintenance_cases where breakdown_id=p_breakdown_id and completed_at is null) then raise exception 'BREAKDOWN_CONTROLLED_BY_MAINTENANCE';end if;if length(trim(coalesce(p_resolution_notes,'')))<3 then raise exception 'BREAKDOWN_RESOLUTION_NOTES_REQUIRED';end if;update public.sector_breakdowns set status='resolved',resolved_at=now(),resolved_by=u,resolution_notes=trim(p_resolution_notes) where id=p_breakdown_id and manager_id=u and status='logged' and archived_at is null returning * into r;if not found then raise exception 'BREAKDOWN_OPEN_NOT_FOUND';end if;return r;end$$;

revoke all on function public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text),public.maintenance_add_part(uuid,text,numeric,text,numeric,text),public.maintenance_case_timeline(uuid),public.maintenance_case_days(integer),public.maintenance_cases_for_day(date) from public,anon;
grant execute on function public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text),public.maintenance_add_part(uuid,text,numeric,text,numeric,text),public.maintenance_case_timeline(uuid),public.maintenance_case_days(integer),public.maintenance_cases_for_day(date) to authenticated;
