-- الآلية الواحدة تعمل حتى ثلاثة شفتات، ولكل شفت سائق وموقع مستقلان مع سجل تاريخي.
create table public.garage_vehicle_shift_assignments(
 id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.garage_vehicles(id) on delete cascade,shift text not null check(shift in('morning','evening','night')),driver_name text not null,sector_id smallint not null references public.sectors(id),starts_at timestamptz not null default now(),ends_at timestamptz,change_reason text,created_by uuid not null references auth.users(id),
 constraint shift_driver_name_check check(length(trim(driver_name)) between 2 and 160),constraint shift_assignment_time_order check(ends_at is null or ends_at>=starts_at));
create unique index one_active_vehicle_shift_assignment on public.garage_vehicle_shift_assignments(vehicle_id,shift) where ends_at is null;
create index garage_vehicle_shift_history on public.garage_vehicle_shift_assignments(vehicle_id,starts_at desc);
alter table public.garage_vehicle_shift_assignments enable row level security;
create policy "garage shift assignment read" on public.garage_vehicle_shift_assignments for select to authenticated using(app.has_role(array['central_garage_officer','ops_room','super_admin']));
create trigger trg_audit_garage_shift_assignments after insert or update or delete on public.garage_vehicle_shift_assignments for each row execute function app.audit_trigger();
insert into public.garage_vehicle_shift_assignments(vehicle_id,shift,driver_name,sector_id,starts_at,ends_at,change_reason,created_by)
select vehicle_id,shift,driver_name,sector_id,starts_at,ends_at,coalesce(change_reason,'ترحيل الإسناد الحالي إلى نموذج الشفتات'),assigned_by from public.garage_driver_assignments on conflict do nothing;

create or replace function public.garage_set_vehicle_shift_assignment(p_vehicle_id uuid,p_shift text,p_driver_name text,p_sector_id smallint,p_reason text)
returns public.garage_vehicle_shift_assignments language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();r public.garage_vehicle_shift_assignments;begin if p_shift not in('morning','evening','night') or length(trim(coalesce(p_driver_name,'')))<2 or length(trim(coalesce(p_reason,'')))<3 then raise exception 'GARAGE_SHIFT_ASSIGNMENT_INVALID';end if;if not exists(select 1 from public.garage_vehicles where id=p_vehicle_id and archived_at is null) then raise exception 'GARAGE_VEHICLE_NOT_FOUND';end if;perform pg_advisory_xact_lock(hashtextextended(p_vehicle_id::text||p_shift,0));if exists(select 1 from public.garage_departures where vehicle_id=p_vehicle_id and shift=p_shift and returned_at is null) then raise exception 'GARAGE_SHIFT_IN_FIELD';end if;update public.garage_vehicle_shift_assignments set ends_at=now(),change_reason=trim(p_reason) where vehicle_id=p_vehicle_id and shift=p_shift and ends_at is null;insert into public.garage_vehicle_shift_assignments(vehicle_id,shift,driver_name,sector_id,change_reason,created_by) values(p_vehicle_id,p_shift,trim(p_driver_name),p_sector_id,trim(p_reason),u) returning * into r;return r;end$$;

create or replace function public.garage_vehicle_shift_assignments_list(p_vehicle_id uuid)
returns table(id uuid,vehicle_id uuid,shift text,driver_name text,sector_id smallint,area_name text,parent_sector text,starts_at timestamptz,ends_at timestamptz,change_reason text)
language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select a.id,a.vehicle_id,a.shift,a.driver_name,a.sector_id,s.name,s.parent_sector,a.starts_at,a.ends_at,a.change_reason from public.garage_vehicle_shift_assignments a join public.sectors s on s.id=a.sector_id where a.vehicle_id=p_vehicle_id order by(a.ends_at is null)desc,a.starts_at desc;end$$;

create or replace function public.garage_record_shift_departure(p_vehicle_id uuid,p_shift text,p_notes text,p_recipient_manager_id uuid)
returns public.garage_departures language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();v public.garage_vehicles;a public.garage_vehicle_shift_assignments;d public.garage_departures;mn text;begin select * into v from public.garage_vehicles where id=p_vehicle_id and archived_at is null for update;if not found then raise exception 'GARAGE_VEHICLE_NOT_FOUND';end if;if exists(select 1 from public.vehicle_maintenance_cases where vehicle_id=v.id and completed_at is null) then raise exception 'GARAGE_VEHICLE_IN_MAINTENANCE';end if;if exists(select 1 from public.garage_departures where vehicle_id=v.id and returned_at is null) then raise exception 'GARAGE_DEPARTURE_ALREADY_OPEN';end if;select * into a from public.garage_vehicle_shift_assignments where vehicle_id=v.id and shift=p_shift and ends_at is null;if not found then raise exception 'GARAGE_SHIFT_ASSIGNMENT_NOT_FOUND';end if;select coalesce(nullif(e.full_name,''),au.email,p_recipient_manager_id::text) into mn from public.manager_profiles mp join auth.users au on au.id=mp.user_id left join public.employees e on e.user_id=mp.user_id where mp.user_id=p_recipient_manager_id and mp.shift=p_shift and a.sector_id=any(mp.sectors);if not found then raise exception 'GARAGE_RECIPIENT_MANAGER_INVALID';end if;insert into public.garage_departures(vehicle_id,driver_name,shift,sector_id,departed_by,notes,recipient_manager_id,recipient_manager_name) values(v.id,a.driver_name,p_shift,a.sector_id,u,nullif(trim(coalesce(p_notes,'')),''),p_recipient_manager_id,mn) returning * into d;insert into public.notifications(user_id,title,body,type,link) values(p_recipient_manager_id,'آلية في الطريق إلى موقع العمل',format('%s · DB %s انطلقت في الشفت %s',v.vehicle_name,v.db_number,p_shift),'info','/manager/vehicle-trips');return d;end$$;
revoke all on function public.garage_set_vehicle_shift_assignment(uuid,text,text,smallint,text),public.garage_vehicle_shift_assignments_list(uuid),public.garage_record_shift_departure(uuid,text,text,uuid) from public,anon;
grant execute on function public.garage_set_vehicle_shift_assignment(uuid,text,text,smallint,text),public.garage_vehicle_shift_assignments_list(uuid),public.garage_record_shift_departure(uuid,text,text,uuid) to authenticated;
create or replace function public.garage_shift_dispatch_recipients(p_vehicle_id uuid,p_shift text)
returns table(user_id uuid,manager_name text,shift text,sectors smallint[]) language plpgsql stable security definer set search_path=public,app as $$declare sid smallint;begin perform app.require_garage_actor();select sector_id into sid from public.garage_vehicle_shift_assignments where vehicle_id=p_vehicle_id and shift=p_shift and ends_at is null;if sid is null then return;end if;return query select mp.user_id,coalesce(nullif(e.full_name,''),u.email,mp.user_id::text),mp.shift,mp.sectors from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where sid=any(mp.sectors) and mp.shift=p_shift and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager') order by 2;end$$;
revoke all on function public.garage_shift_dispatch_recipients(uuid,text) from public,anon;grant execute on function public.garage_shift_dispatch_recipients(uuid,text) to authenticated;
create or replace function app.sync_initial_garage_shift_assignment() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.garage_vehicle_shift_assignments(vehicle_id,shift,driver_name,sector_id,starts_at,change_reason,created_by) values(new.vehicle_id,new.shift,new.driver_name,new.sector_id,new.starts_at,'إنشاء الإسناد الأول مع الآلية',new.assigned_by) on conflict do nothing;return new;end$$;
drop trigger if exists trg_sync_initial_garage_shift on public.garage_driver_assignments;create trigger trg_sync_initial_garage_shift after insert on public.garage_driver_assignments for each row execute function app.sync_initial_garage_shift_assignment();
