-- دورة تشغيل متعددة الزيارات: موقع العمل ↔ المحطة، ومسار الصيانة طويل الأمد.
create table public.vehicle_trip_legs(
 id uuid primary key default gen_random_uuid(),departure_id uuid not null references public.garage_departures(id) on delete cascade,sequence_no integer not null,
 origin_type text not null check(origin_type in('work_site','transfer_station','maintenance')),
 destination_type text not null check(destination_type in('work_site','transfer_station','maintenance','garage')),
 departed_at timestamptz not null default now(),departed_by uuid not null references auth.users(id),departure_notes text,
 arrived_at timestamptz,arrived_by uuid references auth.users(id),arrival_notes text,created_at timestamptz not null default now(),
 unique(departure_id,sequence_no),constraint vehicle_trip_leg_order check(arrived_at is null or arrived_at>=departed_at),
 constraint vehicle_trip_leg_notes check(length(coalesce(departure_notes,''))<=1000 and length(coalesce(arrival_notes,''))<=1000)
);
create unique index vehicle_trip_one_open_leg on public.vehicle_trip_legs(departure_id) where arrived_at is null;
create index vehicle_trip_legs_day_idx on public.vehicle_trip_legs(((departed_at at time zone 'Asia/Baghdad')::date));
alter table public.vehicle_trip_legs enable row level security;
create policy "trip legs authorized read" on public.vehicle_trip_legs for select to authenticated using(
 app.has_role(array['central_garage_officer','transfer_station','maintenance','ops_room','super_admin']) or exists(select 1 from public.garage_departures d where d.id=departure_id and d.recipient_manager_id=auth.uid()));
create trigger trg_audit_vehicle_trip_legs after insert or update or delete on public.vehicle_trip_legs for each row execute function app.audit_trigger();

create table public.vehicle_maintenance_cases(
 id uuid primary key default gen_random_uuid(),departure_id uuid not null references public.garage_departures(id),breakdown_id uuid not null references public.sector_breakdowns(id),vehicle_id uuid not null references public.garage_vehicles(id),manager_id uuid not null references auth.users(id),
 status text not null default 'to_maintenance' check(status in('to_maintenance','at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready','to_work','to_garage','returned_to_work','closed_at_garage')),
 fault_type text not null,priority text not null default 'normal' check(priority in('normal','urgent','critical')),reported_at timestamptz not null default now(),
 arrived_at timestamptz,diagnosis text,work_notes text,parts_notes text,progress smallint not null default 0 check(progress between 0 and 100),expected_completion_at timestamptz,
 ready_at timestamptz,departed_maintenance_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now(),
 constraint maintenance_times_order check((arrived_at is null or arrived_at>=reported_at) and (ready_at is null or ready_at>=arrived_at) and (departed_maintenance_at is null or departed_maintenance_at>=arrived_at) and(completed_at is null or completed_at>=reported_at))
);
create unique index one_open_maintenance_per_vehicle on public.vehicle_maintenance_cases(vehicle_id) where completed_at is null;
create index maintenance_status_idx on public.vehicle_maintenance_cases(status,reported_at desc);
alter table public.vehicle_maintenance_cases enable row level security;
create policy "maintenance cases authorized read" on public.vehicle_maintenance_cases for select to authenticated using(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or manager_id=auth.uid());
create trigger trg_audit_vehicle_maintenance after insert or update or delete on public.vehicle_maintenance_cases for each row execute function app.audit_trigger();

create or replace function app.next_trip_leg_sequence(p_departure uuid) returns integer language sql volatile security definer set search_path=public as $$select coalesce(max(sequence_no),0)+1 from public.vehicle_trip_legs where departure_id=p_departure$$;

create or replace function public.sector_send_vehicle_to_station(p_departure_id uuid,p_notes text default null)
returns public.vehicle_trip_legs language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();d public.garage_departures;l public.vehicle_trip_legs;begin
 if not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;if length(coalesce(p_notes,''))>1000 then raise exception 'TRIP_NOTES_TOO_LONG';end if;
 select * into d from public.garage_departures where id=p_departure_id and recipient_manager_id=u and arrived_at is not null and returned_at is null for update;if not found then raise exception 'TRIP_NOT_AT_MANAGER_SITE';end if;
 if exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null) then raise exception 'TRIP_LEG_ALREADY_OPEN';end if;
 if exists(select 1 from public.vehicle_trip_legs where departure_id=d.id) and not exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and destination_type='work_site' and arrived_at is not null order by sequence_no desc limit 1) then raise exception 'TRIP_NOT_AT_MANAGER_SITE';end if;
 update public.garage_departures set site_departed_at=coalesce(site_departed_at,now()),site_departed_by=coalesce(site_departed_by,u),site_departure_notes=coalesce(site_departure_notes,nullif(trim(coalesce(p_notes,'')),'')) where id=d.id;
 insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes) values(d.id,app.next_trip_leg_sequence(d.id),'work_site','transfer_station',u,nullif(trim(coalesce(p_notes,'')),'')) returning * into l;
 insert into public.notifications(user_id,title,body,type,link) select ur.user_id,'آلية في الطريق إلى المحطة التحويلية',format('الآلية DB %s غادرت موقع العمل باتجاه المحطة',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'info','/transfer-station/vehicle-movements' from public.user_roles ur where ur.role='transfer_station';return l;end$$;

create or replace function public.station_confirm_vehicle_arrival(p_leg_id uuid,p_notes text default null)
returns public.vehicle_trip_legs language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();l public.vehicle_trip_legs;d public.garage_departures;begin
 if not app.has_role(array['transfer_station']) then raise exception 'STATION_FORBIDDEN';end if;update public.vehicle_trip_legs set arrived_at=now(),arrived_by=u,arrival_notes=nullif(trim(coalesce(p_notes,'')),'') where id=p_leg_id and destination_type='transfer_station' and arrived_at is null returning * into l;if not found then raise exception 'STATION_ARRIVAL_NOT_ALLOWED';end if;select * into d from public.garage_departures where id=l.departure_id;insert into public.notifications(user_id,title,body,type,link) values(d.recipient_manager_id,'وصلت الآلية إلى المحطة التحويلية',format('أكدت المحطة وصول الآلية DB %s',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'success','/manager/vehicle-trips');return l;end$$;

create or replace function public.station_dispatch_vehicle(p_departure_id uuid,p_destination text,p_notes text default null)
returns public.vehicle_trip_legs language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();d public.garage_departures;l public.vehicle_trip_legs;dest text;begin
 if not app.has_role(array['transfer_station']) then raise exception 'STATION_FORBIDDEN';end if;dest:=case p_destination when 'work_site' then 'work_site' when 'garage' then 'garage' else null end;if dest is null then raise exception 'STATION_DESTINATION_INVALID';end if;
 select * into d from public.garage_departures where id=p_departure_id and returned_at is null for update;if not found or exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null) or not exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and destination_type='transfer_station' and arrived_at is not null order by sequence_no desc limit 1) then raise exception 'VEHICLE_NOT_AT_STATION';end if;
 insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes) values(d.id,app.next_trip_leg_sequence(d.id),'transfer_station',dest,u,nullif(trim(coalesce(p_notes,'')),'')) returning * into l;
 if dest='work_site' then insert into public.notifications(user_id,title,body,type,link) values(d.recipient_manager_id,'الآلية عائدة إلى موقع العمل',format('غادرت الآلية DB %s المحطة باتجاه موقعك',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'info','/manager/vehicle-trips');else insert into public.notifications(user_id,title,body,type,link) values(d.recipient_manager_id,'الآلية غادرت المحطة إلى الكراج',format('الآلية DB %s لن تعود للموقع وغادرت باتجاه الكراج',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'warning','/manager/vehicle-trips');insert into public.notifications(user_id,title,body,type,link) values(d.departed_by,'آلية في الطريق من المحطة إلى الكراج',format('الآلية DB %s في الطريق إلى الكراج',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'info','/central-garage/drivers-dispatch');end if;return l;end$$;

create or replace function public.sector_confirm_vehicle_site_return(p_leg_id uuid,p_notes text default null)
returns public.vehicle_trip_legs language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();l public.vehicle_trip_legs;begin if not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;update public.vehicle_trip_legs l0 set arrived_at=now(),arrived_by=u,arrival_notes=nullif(trim(coalesce(p_notes,'')),'') from public.garage_departures d where l0.id=p_leg_id and d.id=l0.departure_id and d.recipient_manager_id=u and l0.destination_type='work_site' and l0.arrived_at is null returning l0.* into l;if not found then raise exception 'SITE_RETURN_NOT_ALLOWED';end if;return l;end$$;

create or replace function public.sector_send_vehicle_to_maintenance(p_departure_id uuid,p_fault_type text,p_priority text default 'normal',p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();d public.garage_departures;v public.garage_vehicles;b public.sector_breakdowns;c public.vehicle_maintenance_cases;l public.vehicle_trip_legs;nm text;begin
 if not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;if length(trim(coalesce(p_fault_type,'')))<3 or p_priority not in('normal','urgent','critical') then raise exception 'MAINTENANCE_INPUT_INVALID';end if;select * into d from public.garage_departures where id=p_departure_id and recipient_manager_id=u and arrived_at is not null and returned_at is null for update;if not found or exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null) then raise exception 'TRIP_NOT_AT_MANAGER_SITE';end if;select * into v from public.garage_vehicles where id=d.vehicle_id;select coalesce(nullif(e.full_name,''),au.email,u::text) into nm from auth.users au left join public.employees e on e.user_id=au.id where au.id=u;
 insert into public.sector_breakdowns(manager_id,manager_name,shift,sectors,db_number,fault_type,notes,status) values(u,nm,d.shift,array[d.sector_id],v.db_number,trim(p_fault_type),nullif(trim(coalesce(p_notes,'')),''),'logged') returning * into b;
 insert into public.vehicle_maintenance_cases(departure_id,breakdown_id,vehicle_id,manager_id,fault_type,priority) values(d.id,b.id,v.id,u,trim(p_fault_type),p_priority) returning * into c;
 insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes) values(d.id,app.next_trip_leg_sequence(d.id),'work_site','maintenance',u,nullif(trim(coalesce(p_notes,'')),'')) returning * into l;
 insert into public.notifications(user_id,title,body,type,link) select ur.user_id,'آلية في الطريق إلى الصيانة',format('الآلية DB %s تعطلت وغادرت موقع العمل إلى الصيانة',v.db_number),'error','/maintenance/vehicle-cases' from public.user_roles ur where ur.role='maintenance';return c;end$$;

create or replace function public.maintenance_confirm_arrival(p_case_id uuid,p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;l public.vehicle_trip_legs;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;update public.vehicle_maintenance_cases set status='at_maintenance',arrived_at=now(),updated_at=now() where id=p_case_id and status='to_maintenance' returning * into c;if not found then raise exception 'MAINTENANCE_ARRIVAL_NOT_ALLOWED';end if;update public.vehicle_trip_legs set arrived_at=now(),arrived_by=u,arrival_notes=nullif(trim(coalesce(p_notes,'')),'') where departure_id=c.departure_id and destination_type='maintenance' and arrived_at is null returning * into l;insert into public.notifications(user_id,title,body,type,link) values(c.manager_id,'وصلت الآلية إلى الصيانة','أكدت الصيانة استلام الآلية وبدء متابعة حالتها','success','/manager/vehicle-trips');return c;end$$;

create or replace function public.maintenance_update_case(p_case_id uuid,p_status text,p_progress integer,p_diagnosis text default null,p_work_notes text default null,p_parts_notes text default null,p_expected_completion_at timestamptz default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare c public.vehicle_maintenance_cases;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_status not in('at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready') or p_progress not between 0 and 100 then raise exception 'MAINTENANCE_UPDATE_INVALID';end if;update public.vehicle_maintenance_cases set status=p_status,progress=p_progress,diagnosis=nullif(trim(coalesce(p_diagnosis,'')),''),work_notes=nullif(trim(coalesce(p_work_notes,'')),''),parts_notes=nullif(trim(coalesce(p_parts_notes,'')),''),expected_completion_at=p_expected_completion_at,ready_at=case when p_status='ready' then coalesce(ready_at,now()) else ready_at end,updated_at=now() where id=p_case_id and arrived_at is not null and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;return c;end$$;

create or replace function public.maintenance_dispatch_vehicle(p_case_id uuid,p_destination text,p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;d public.garage_departures;l public.vehicle_trip_legs;dest text;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;dest:=case p_destination when 'work_site' then 'work_site' when 'garage' then 'garage' else null end;if dest is null then raise exception 'MAINTENANCE_DESTINATION_INVALID';end if;update public.vehicle_maintenance_cases set status=case when dest='work_site' then 'to_work' else 'to_garage' end,departed_maintenance_at=now(),updated_at=now() where id=p_case_id and status='ready' and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_NOT_READY';end if;select * into d from public.garage_departures where id=c.departure_id;insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes) values(d.id,app.next_trip_leg_sequence(d.id),'maintenance',dest,u,nullif(trim(coalesce(p_notes,'')),'')) returning * into l;if dest='work_site' then insert into public.notifications(user_id,title,body,type,link) values(c.manager_id,'الآلية عائدة من الصيانة إلى العمل','غادرت الآلية الصيانة وهي في الطريق إلى موقع العمل','success','/manager/vehicle-trips');else insert into public.notifications(user_id,title,body,type,link) values(c.manager_id,'الآلية غادرت الصيانة إلى الكراج','لن تعود الآلية إلى الموقع وغادرت الصيانة إلى الكراج','warning','/manager/vehicle-trips');insert into public.notifications(user_id,title,body,type,link) values(d.departed_by,'آلية عائدة من الصيانة إلى الكراج','غادرت الآلية الصيانة وهي في الطريق إلى الكراج','info','/central-garage/drivers-dispatch');end if;return c;end$$;

create or replace function public.operational_vehicle_movements(p_from date,p_to date)
returns table(leg_id uuid,departure_id uuid,vehicle_id uuid,db_number text,vehicle_name text,driver_name text,shift text,sector_id smallint,manager_name text,origin_type text,destination_type text,departed_at timestamptz,arrived_at timestamptz,duration_minutes integer,departure_notes text,arrival_notes text)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['ops_room','super_admin']) then raise exception 'OPS_ROOM_FORBIDDEN';end if;return query select l.id,d.id,d.vehicle_id,v.db_number,v.vehicle_name,d.driver_name,d.shift,d.sector_id,d.recipient_manager_name,l.origin_type,l.destination_type,l.departed_at,l.arrived_at,case when l.arrived_at is null then null else floor(extract(epoch from(l.arrived_at-l.departed_at))/60)::int end,l.departure_notes,l.arrival_notes from public.vehicle_trip_legs l join public.garage_departures d on d.id=l.departure_id join public.garage_vehicles v on v.id=d.vehicle_id where(l.departed_at at time zone 'Asia/Baghdad')::date between p_from and p_to order by l.departed_at desc;end$$;

revoke all on function public.sector_send_vehicle_to_station(uuid,text),public.station_confirm_vehicle_arrival(uuid,text),public.station_dispatch_vehicle(uuid,text,text),public.sector_confirm_vehicle_site_return(uuid,text),public.sector_send_vehicle_to_maintenance(uuid,text,text,text),public.maintenance_confirm_arrival(uuid,text),public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz),public.maintenance_dispatch_vehicle(uuid,text,text),public.operational_vehicle_movements(date,date) from public,anon;
grant execute on function public.sector_send_vehicle_to_station(uuid,text),public.station_confirm_vehicle_arrival(uuid,text),public.station_dispatch_vehicle(uuid,text,text),public.sector_confirm_vehicle_site_return(uuid,text),public.sector_send_vehicle_to_maintenance(uuid,text,text,text),public.maintenance_confirm_arrival(uuid,text),public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz),public.maintenance_dispatch_vehicle(uuid,text,text),public.operational_vehicle_movements(date,date) to authenticated;

create or replace function public.trip_legs_for_departure(p_departure_id uuid)
returns setof public.vehicle_trip_legs language plpgsql stable security definer set search_path=public,app as $$declare d public.garage_departures;begin select * into d from public.garage_departures where id=p_departure_id;if not found or not(app.has_role(array['central_garage_officer','transfer_station','maintenance','ops_room','super_admin']) or d.recipient_manager_id=auth.uid()) then raise exception 'TRIP_LEGS_FORBIDDEN';end if;return query select * from public.vehicle_trip_legs where departure_id=p_departure_id order by sequence_no;end$$;

create or replace function public.station_vehicle_movements()
returns table(leg_id uuid,departure_id uuid,sequence_no integer,origin_type text,destination_type text,departed_at timestamptz,arrived_at timestamptz,departure_notes text,arrival_notes text,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['transfer_station']) then raise exception 'STATION_FORBIDDEN';end if;return query select l.id,d.id,l.sequence_no,l.origin_type,l.destination_type,l.departed_at,l.arrived_at,l.departure_notes,l.arrival_notes,d.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,s.name,d.recipient_manager_name from public.vehicle_trip_legs l join public.garage_departures d on d.id=l.departure_id join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where(l.destination_type='transfer_station' or l.origin_type='transfer_station') and(l.arrived_at is null or(l.departed_at at time zone 'Asia/Baghdad')::date>=(now() at time zone 'Asia/Baghdad')::date-7) order by(l.arrived_at is null)desc,l.departed_at desc;end$$;

create or replace function public.maintenance_vehicle_cases()
returns table(case_id uuid,departure_id uuid,breakdown_id uuid,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text,status text,fault_type text,priority text,reported_at timestamptz,arrived_at timestamptz,diagnosis text,work_notes text,parts_notes text,progress smallint,expected_completion_at timestamptz,ready_at timestamptz,departed_maintenance_at timestamptz,completed_at timestamptz)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;return query select c.id,c.departure_id,c.breakdown_id,c.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,s.name,d.recipient_manager_name,c.status,c.fault_type,c.priority,c.reported_at,c.arrived_at,c.diagnosis,c.work_notes,c.parts_notes,c.progress,c.expected_completion_at,c.ready_at,c.departed_maintenance_at,c.completed_at from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join public.sectors s on s.id=d.sector_id where c.completed_at is null or(c.completed_at at time zone 'Asia/Baghdad')::date>=(now() at time zone 'Asia/Baghdad')::date-30 order by(c.completed_at is null)desc,c.reported_at desc;end$$;

create or replace function public.sector_confirm_vehicle_site_return(p_leg_id uuid,p_notes text default null)
returns public.vehicle_trip_legs language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();l public.vehicle_trip_legs;c public.vehicle_maintenance_cases;begin if not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;update public.vehicle_trip_legs l0 set arrived_at=now(),arrived_by=u,arrival_notes=nullif(trim(coalesce(p_notes,'')),'') from public.garage_departures d where l0.id=p_leg_id and d.id=l0.departure_id and d.recipient_manager_id=u and l0.destination_type='work_site' and l0.arrived_at is null returning l0.* into l;if not found then raise exception 'SITE_RETURN_NOT_ALLOWED';end if;update public.vehicle_maintenance_cases set status='returned_to_work',completed_at=now(),updated_at=now() where departure_id=l.departure_id and status='to_work' and completed_at is null returning * into c;if found then update public.sector_breakdowns set status='resolved',resolved_at=now(),resolved_by=u,resolution_notes=coalesce(nullif(trim(coalesce(p_notes,'')),''),'عادت الآلية من الصيانة إلى موقع العمل') where id=c.breakdown_id;end if;return l;end$$;

create or replace function public.garage_record_return(p_departure_id uuid)
returns public.garage_departures language plpgsql volatile security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();d public.garage_departures;l public.vehicle_trip_legs;c public.vehicle_maintenance_cases;begin select * into d from public.garage_departures where id=p_departure_id and returned_at is null for update;if not found then raise exception 'GARAGE_OPEN_DEPARTURE_NOT_FOUND';end if;select * into l from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null for update;if found then if l.destination_type<>'garage' then raise exception 'GARAGE_VEHICLE_NOT_SENT_BACK';end if;update public.vehicle_trip_legs set arrived_at=now(),arrived_by=u,arrival_notes='أكد الكراج الوصول' where id=l.id;elsif d.recipient_manager_id is not null and d.site_departed_at is null then raise exception 'GARAGE_VEHICLE_NOT_SENT_BACK';end if;update public.garage_departures set arrived_at=coalesce(arrived_at,now()),arrived_by=coalesce(arrived_by,u),site_departed_at=coalesce(site_departed_at,now()),site_departed_by=coalesce(site_departed_by,u),returned_at=now(),returned_by=u where id=d.id returning * into d;update public.vehicle_maintenance_cases set status='closed_at_garage',completed_at=now(),updated_at=now() where departure_id=d.id and status='to_garage' and completed_at is null returning * into c;if found then update public.sector_breakdowns set status='resolved',resolved_at=now(),resolved_by=u,resolution_notes='أغلقت الحالة بعد وصول الآلية من الصيانة إلى الكراج' where id=c.breakdown_id;end if;if d.recipient_manager_id is not null then insert into public.notifications(user_id,title,body,type,link) values(d.recipient_manager_id,'وصلت الآلية إلى الكراج',format('أكد الكراج استلام الآلية DB %s وإغلاق الانطلاقة',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'success','/manager/vehicle-trips');end if;return d;end$$;

revoke all on function public.trip_legs_for_departure(uuid),public.station_vehicle_movements(),public.maintenance_vehicle_cases() from public,anon;
grant execute on function public.trip_legs_for_departure(uuid),public.station_vehicle_movements(),public.maintenance_vehicle_cases() to authenticated;

create or replace function public.operational_attendance(p_from date,p_to date)
returns table(id uuid,log_date date,worker_name text,sector_id smallint,area_name text,shift text,is_present boolean,note text,manager_id uuid)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['ops_room','super_admin']) then raise exception 'OPS_ROOM_FORBIDDEN';end if;return query select a.id,a.log_date,a.worker_name,a.sector_id,s.name,a.shift,a.is_present,a.note,a.manager_id from public.sector_attendance a join public.sectors s on s.id=a.sector_id where a.log_date between p_from and p_to and a.archived_at is null order by a.log_date desc,s.name,a.worker_name;end$$;
create or replace function public.operational_garage_trips(p_from date,p_to date)
returns table(id uuid,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text,departed_at timestamptz,arrived_at timestamptz,site_departed_at timestamptz,returned_at timestamptz,total_minutes integer,work_minutes integer,downtime_minutes integer)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['ops_room','super_admin']) then raise exception 'OPS_ROOM_FORBIDDEN';end if;return query select d.id,d.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,s.name,d.recipient_manager_name,d.departed_at,d.arrived_at,d.site_departed_at,d.returned_at,case when d.returned_at is null then null else floor(extract(epoch from(d.returned_at-d.departed_at))/60)::int end,case when d.arrived_at is null then null else greatest(0,floor(extract(epoch from(coalesce(d.site_departed_at,d.returned_at,now())-d.arrived_at))/60)::int-coalesce((select sum(floor(extract(epoch from(coalesce(c.completed_at,now())-c.reported_at))/60)::int) from public.vehicle_maintenance_cases c where c.departure_id=d.id),0))::int end,coalesce((select sum(floor(extract(epoch from(coalesce(c.completed_at,now())-c.reported_at))/60)::int) from public.vehicle_maintenance_cases c where c.departure_id=d.id),0)::int from public.garage_departures d join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where(d.departed_at at time zone 'Asia/Baghdad')::date between p_from and p_to order by d.departed_at desc;end$$;
create or replace function public.operational_maintenance_cases(p_from date,p_to date)
returns setof public.vehicle_maintenance_cases language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['ops_room','super_admin']) then raise exception 'OPS_ROOM_FORBIDDEN';end if;return query select * from public.vehicle_maintenance_cases where(reported_at at time zone 'Asia/Baghdad')::date between p_from and p_to or completed_at is null order by(completed_at is null)desc,reported_at desc;end$$;
revoke all on function public.operational_attendance(date,date),public.operational_garage_trips(date,date),public.operational_maintenance_cases(date,date) from public,anon;
grant execute on function public.operational_attendance(date,date),public.operational_garage_trips(date,date),public.operational_maintenance_cases(date,date) to authenticated;
