-- 00089 · مرفقات الصيانة، الفني المرجعي، واعتماد جاهزية الآلية قبل المغادرة

alter table public.vehicle_maintenance_cases
 add column assigned_technician_id uuid references auth.users(id),
 add column ready_declared_by uuid references auth.users(id),
 add column readiness_approved_at timestamptz,
 add column readiness_approved_by uuid references auth.users(id),
 add column readiness_approval_notes text;
alter table public.vehicle_maintenance_updates add column assigned_technician_id uuid references auth.users(id);

create table public.vehicle_maintenance_attachments(
 id uuid primary key default gen_random_uuid(),case_id uuid not null references public.vehicle_maintenance_cases(id) on delete cascade,
 storage_path text not null unique,original_name text not null,mime_type text not null,size_bytes bigint not null,sha256 text not null,caption text,
 created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),
 constraint maintenance_attachment_name_check check(length(trim(original_name)) between 1 and 255),
 constraint maintenance_attachment_type_check check(mime_type in('image/jpeg','image/png','image/webp','application/pdf')),
 constraint maintenance_attachment_size_check check(size_bytes between 1 and 26214400),
 constraint maintenance_attachment_sha_check check(sha256~'^[0-9a-f]{64}$'),
 constraint maintenance_attachment_caption_check check(length(coalesce(caption,''))<=500)
);
create index maintenance_attachments_case_time on public.vehicle_maintenance_attachments(case_id,created_at);
alter table public.vehicle_maintenance_attachments enable row level security;
create policy "maintenance attachments authorized read" on public.vehicle_maintenance_attachments for select to authenticated using(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or exists(select 1 from public.vehicle_maintenance_cases c where c.id=case_id and c.manager_id=auth.uid()));
create trigger trg_audit_maintenance_attachments after insert or update or delete on public.vehicle_maintenance_attachments for each row execute function app.audit_trigger();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('maintenance-attachments','maintenance-attachments',false,26214400,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "maintenance files upload" on storage.objects for insert to authenticated with check(bucket_id='maintenance-attachments' and app.has_role(array['maintenance']));
create policy "maintenance files read" on storage.objects for select to authenticated using(bucket_id='maintenance-attachments' and(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or exists(select 1 from public.vehicle_maintenance_attachments a join public.vehicle_maintenance_cases c on c.id=a.case_id where a.storage_path=storage.objects.name and c.manager_id=auth.uid())));
create policy "maintenance files remove" on storage.objects for delete to authenticated using(bucket_id='maintenance-attachments' and app.has_role(array['maintenance']));

create or replace function public.maintenance_technicians()
returns table(user_id uuid,display_name text,email text) language plpgsql stable security definer set search_path=public,app as $$
begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;return query select ur.user_id,coalesce(nullif(trim(e.full_name),''),u.email,ur.user_id::text),u.email from public.user_roles ur join auth.users u on u.id=ur.user_id left join public.employees e on e.user_id=ur.user_id where ur.role='maintenance' order by 2;end$$;

create or replace function public.maintenance_register_attachment(p_case_id uuid,p_storage_path text,p_original_name text,p_mime_type text,p_size_bytes bigint,p_sha256 text,p_caption text default null)
returns public.vehicle_maintenance_attachments language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();r public.vehicle_maintenance_attachments;begin
 if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;
 if not exists(select 1 from public.vehicle_maintenance_cases where id=p_case_id and completed_at is null) then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;
 if p_storage_path not like p_case_id::text||'/%' or p_mime_type not in('image/jpeg','image/png','image/webp','application/pdf') or p_size_bytes not between 1 and 26214400 or p_sha256!~'^[0-9a-f]{64}$' then raise exception 'MAINTENANCE_ATTACHMENT_INVALID';end if;
 if(select count(*) from public.vehicle_maintenance_attachments where case_id=p_case_id)>=50 then raise exception 'MAINTENANCE_ATTACHMENT_LIMIT';end if;
 insert into public.vehicle_maintenance_attachments(case_id,storage_path,original_name,mime_type,size_bytes,sha256,caption,created_by) values(p_case_id,p_storage_path,trim(p_original_name),p_mime_type,p_size_bytes,lower(p_sha256),nullif(trim(coalesce(p_caption,'')),''),u) returning * into r;return r;
end$$;

-- استبدال تحديث الحالة لإسناد فني من حساب فعلي وتسجيل معلن الجاهزية.
drop function public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text);
create function public.maintenance_update_case(p_case_id uuid,p_status text,p_progress integer,p_diagnosis text default null,p_work_notes text default null,p_parts_notes text default null,p_expected_completion_at timestamptz default null,p_assigned_technician text default null,p_estimated_cost numeric default null,p_actual_cost numeric default null,p_delay_reason text default null,p_assigned_technician_id uuid default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;tech_name text;begin
 if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_status not in('at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready') or p_progress not between 0 and 100 then raise exception 'MAINTENANCE_UPDATE_INVALID';end if;if p_status='ready' and p_progress<>100 then raise exception 'MAINTENANCE_READY_REQUIRES_100';end if;if p_actual_cost is not null and p_actual_cost<0 or p_estimated_cost is not null and p_estimated_cost<0 then raise exception 'MAINTENANCE_COST_INVALID';end if;
 if p_assigned_technician_id is not null then select coalesce(nullif(trim(e.full_name),''),au.email,p_assigned_technician_id::text) into tech_name from auth.users au left join public.employees e on e.user_id=au.id where au.id=p_assigned_technician_id and exists(select 1 from public.user_roles ur where ur.user_id=au.id and ur.role='maintenance');if not found then raise exception 'MAINTENANCE_TECHNICIAN_INVALID';end if;else tech_name:=nullif(trim(coalesce(p_assigned_technician,'')),'');end if;
 update public.vehicle_maintenance_cases set status=p_status,progress=p_progress,diagnosis=nullif(trim(coalesce(p_diagnosis,'')),''),work_notes=nullif(trim(coalesce(p_work_notes,'')),''),parts_notes=nullif(trim(coalesce(p_parts_notes,'')),''),expected_completion_at=p_expected_completion_at,assigned_technician=coalesce(tech_name,assigned_technician),assigned_technician_id=coalesce(p_assigned_technician_id,assigned_technician_id),estimated_cost=p_estimated_cost,actual_cost=p_actual_cost,delay_reason=nullif(trim(coalesce(p_delay_reason,'')),''),ready_at=case when p_status='ready' then coalesce(ready_at,now()) else ready_at end,ready_declared_by=case when p_status='ready' then u else ready_declared_by end,readiness_approved_at=case when p_status='ready' then null else readiness_approved_at end,readiness_approved_by=case when p_status='ready' then null else readiness_approved_by end,readiness_approval_notes=case when p_status='ready' then null else readiness_approval_notes end,updated_at=now() where id=p_case_id and arrived_at is not null and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;
 insert into public.vehicle_maintenance_updates(case_id,status,progress,diagnosis,work_notes,parts_notes,assigned_technician,assigned_technician_id,estimated_cost,actual_cost,delay_reason,expected_completion_at,created_by) values(c.id,c.status,c.progress,c.diagnosis,c.work_notes,c.parts_notes,c.assigned_technician,c.assigned_technician_id,c.estimated_cost,c.actual_cost,c.delay_reason,c.expected_completion_at,u);return c;end$$;

create or replace function public.maintenance_approve_readiness(p_case_id uuid,p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;begin
 if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;
 update public.vehicle_maintenance_cases set readiness_approved_at=now(),readiness_approved_by=u,readiness_approval_notes=nullif(trim(coalesce(p_notes,'')),''),updated_at=now() where id=p_case_id and status='ready' and progress=100 and diagnosis is not null and work_notes is not null and completed_at is null and readiness_approved_at is null returning * into c;
 if not found then raise exception 'MAINTENANCE_READINESS_NOT_APPROVABLE';end if;return c;
end$$;

create or replace function public.maintenance_dispatch_vehicle(p_case_id uuid,p_destination text,p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;d public.garage_departures;l public.vehicle_trip_legs;dest text;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;dest:=case p_destination when 'work_site' then 'work_site' when 'garage' then 'garage' else null end;if dest is null then raise exception 'MAINTENANCE_DESTINATION_INVALID';end if;update public.vehicle_maintenance_cases set status=case when dest='work_site' then 'to_work' else 'to_garage' end,departed_maintenance_at=now(),updated_at=now() where id=p_case_id and status='ready' and readiness_approved_at is not null and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_READINESS_APPROVAL_REQUIRED';end if;select * into d from public.garage_departures where id=c.departure_id;insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes) values(d.id,app.next_trip_leg_sequence(d.id),'maintenance',dest,u,nullif(trim(coalesce(p_notes,'')),'')) returning * into l;if dest='work_site' then insert into public.notifications(user_id,title,body,type,link) values(c.manager_id,'الآلية عائدة من الصيانة إلى العمل','اعتمدت جاهزية الآلية وغادرت الصيانة إلى موقع العمل','success','/manager/vehicle-trips');else insert into public.notifications(user_id,title,body,type,link) values(c.manager_id,'الآلية غادرت الصيانة إلى الكراج','اعتمدت جاهزية الآلية وغادرت الصيانة إلى الكراج','warning','/manager/vehicle-trips');insert into public.notifications(user_id,title,body,type,link) values(d.departed_by,'آلية عائدة من الصيانة إلى الكراج','اعتمدت جاهزية الآلية وغادرت الصيانة إلى الكراج','info','/central-garage/drivers-dispatch');end if;return c;end$$;

create or replace function public.maintenance_case_timeline(p_case_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public,app as $$declare c public.vehicle_maintenance_cases;begin select * into c from public.vehicle_maintenance_cases where id=p_case_id;if not found or not(app.has_role(array['maintenance','central_garage_officer','ops_room','super_admin']) or c.manager_id=auth.uid()) then raise exception 'MAINTENANCE_CASE_FORBIDDEN';end if;return jsonb_build_object('case',to_jsonb(c),'updates',coalesce((select jsonb_agg(to_jsonb(u) order by u.created_at desc) from public.vehicle_maintenance_updates u where u.case_id=c.id),'[]'::jsonb),'parts',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at) from public.vehicle_maintenance_parts p where p.case_id=c.id),'[]'::jsonb),'attachments',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at desc) from public.vehicle_maintenance_attachments a where a.case_id=c.id),'[]'::jsonb),'legs',coalesce((select jsonb_agg(to_jsonb(l) order by l.sequence_no) from public.vehicle_trip_legs l where l.departure_id=c.departure_id),'[]'::jsonb));end$$;

-- إعادة واجهة اليوم لتضمين حقول الاعتماد والفني المرجعي.
drop function public.maintenance_cases_for_day(date);
create function public.maintenance_cases_for_day(p_day date)
returns table(case_id uuid,departure_id uuid,breakdown_id uuid,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text,status text,fault_type text,priority text,reported_at timestamptz,arrived_at timestamptz,diagnosis text,work_notes text,parts_notes text,progress smallint,expected_completion_at timestamptz,ready_at timestamptz,departed_maintenance_at timestamptz,completed_at timestamptz,assigned_technician text,estimated_cost numeric,actual_cost numeric,delay_reason text,assigned_technician_id uuid,ready_declared_by uuid,readiness_approved_at timestamptz,readiness_approved_by uuid,readiness_approval_notes text)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;return query select c.id,c.departure_id,c.breakdown_id,c.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,se.name,d.recipient_manager_name,c.status,c.fault_type,c.priority,c.reported_at,c.arrived_at,c.diagnosis,c.work_notes,c.parts_notes,c.progress,c.expected_completion_at,c.ready_at,c.departed_maintenance_at,c.completed_at,c.assigned_technician,c.estimated_cost,c.actual_cost,c.delay_reason,c.assigned_technician_id,c.ready_declared_by,c.readiness_approved_at,c.readiness_approved_by,c.readiness_approval_notes from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join public.sectors se on se.id=d.sector_id where c.reported_at<p_day+1 and(c.completed_at is null or c.completed_at>=p_day) order by(c.completed_at is null)desc,c.reported_at desc;end$$;

revoke all on function public.maintenance_technicians(),public.maintenance_register_attachment(uuid,text,text,text,bigint,text,text),public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text,uuid),public.maintenance_approve_readiness(uuid,text),public.maintenance_dispatch_vehicle(uuid,text,text),public.maintenance_cases_for_day(date) from public,anon;
grant execute on function public.maintenance_technicians(),public.maintenance_register_attachment(uuid,text,text,text,bigint,text,text),public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text,uuid),public.maintenance_approve_readiness(uuid,text),public.maintenance_dispatch_vehicle(uuid,text,text),public.maintenance_cases_for_day(date) to authenticated;
