-- 00080 · تسليم واستلام الآلية بين الكراج ومسؤول القسم
alter table public.garage_departures
 add column recipient_manager_id uuid references auth.users(id),
 add column recipient_manager_name text,
 add column arrived_at timestamptz,
 add column arrived_by uuid references auth.users(id),
 add column arrival_notes text,
 add column site_departed_at timestamptz,
 add column site_departed_by uuid references auth.users(id),
 add column site_departure_notes text,
 add constraint garage_departure_handover_order check(
   (arrived_at is null and arrived_by is null or arrived_at is not null and arrived_by is not null)
   and (site_departed_at is null and site_departed_by is null or site_departed_at is not null and site_departed_by is not null)
   and (arrived_at is null or arrived_at>=departed_at)
   and (site_departed_at is null or arrived_at is not null and site_departed_at>=arrived_at)
   and (returned_at is null or site_departed_at is null or returned_at>=site_departed_at)
 ),
 add constraint garage_departure_stage_notes check(length(coalesce(arrival_notes,''))<=500 and length(coalesce(site_departure_notes,''))<=500);
create index idx_garage_departures_recipient on public.garage_departures(recipient_manager_id,returned_at,departed_at desc);

drop policy if exists "garage departures read" on public.garage_departures;
create policy "garage departures read" on public.garage_departures for select to authenticated using(
 app.has_role(array['central_garage_officer','super_admin']) or
 (app.has_role(array['department_manager']) and (recipient_manager_id=auth.uid() or recipient_manager_id is null and exists(select 1 from public.manager_profiles mp where mp.user_id=auth.uid() and sector_id=any(mp.sectors) and shift=mp.shift)))
);

create or replace function public.garage_dispatch_recipients(p_vehicle_id uuid)
returns table(user_id uuid,manager_name text,shift text,sectors smallint[]) language plpgsql stable security definer set search_path=public,app as $$
declare v public.garage_vehicles;begin perform app.require_garage_actor();select * into v from public.garage_vehicles where id=p_vehicle_id and archived_at is null;if not found then raise exception 'GARAGE_VEHICLE_NOT_FOUND';end if;return query select mp.user_id,coalesce(nullif(e.full_name,''),u.email,mp.user_id::text),mp.shift,mp.sectors from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where v.sector_id=any(mp.sectors) and mp.shift=v.shift and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager') order by 2;end$$;

drop function if exists public.garage_record_departure(uuid,text);
create or replace function public.garage_record_departure(p_vehicle_id uuid,p_notes text default null,p_recipient_manager_id uuid default null)
returns public.garage_departures language plpgsql volatile security definer set search_path=public,app as $$
declare v_uid uuid:=app.require_garage_actor();v_vehicle public.garage_vehicles;v_assignment public.garage_driver_assignments;v_row public.garage_departures;v_manager_name text;v_count int;begin
 if length(coalesce(p_notes,''))>500 then raise exception 'GARAGE_DEPARTURE_NOTES_TOO_LONG';end if;select * into v_vehicle from public.garage_vehicles where id=p_vehicle_id and archived_at is null for update;if not found then raise exception 'GARAGE_VEHICLE_NOT_FOUND';end if;select * into v_assignment from public.garage_driver_assignments where vehicle_id=p_vehicle_id and ends_at is null;if not found then raise exception 'GARAGE_NO_ACTIVE_ASSIGNMENT';end if;if exists(select 1 from public.garage_departures where vehicle_id=p_vehicle_id and returned_at is null) then raise exception 'GARAGE_DEPARTURE_ALREADY_OPEN';end if;
 if p_recipient_manager_id is not null then select coalesce(nullif(e.full_name,''),u.email,p_recipient_manager_id::text) into v_manager_name from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where mp.user_id=p_recipient_manager_id and v_assignment.sector_id=any(mp.sectors) and mp.shift=v_assignment.shift and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager');if not found then raise exception 'GARAGE_RECIPIENT_MANAGER_INVALID';end if;else select count(*),min(coalesce(nullif(e.full_name,''),u.email,mp.user_id::text)) into v_count,v_manager_name from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where v_assignment.sector_id=any(mp.sectors) and mp.shift=v_assignment.shift and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager');if v_count<>1 then v_manager_name:=null;end if;end if;
 insert into public.garage_departures(vehicle_id,driver_name,shift,sector_id,departed_by,notes,recipient_manager_id,recipient_manager_name) values(p_vehicle_id,v_assignment.driver_name,v_assignment.shift,v_assignment.sector_id,v_uid,nullif(trim(coalesce(p_notes,'')),''),p_recipient_manager_id,v_manager_name) returning * into v_row;
 if p_recipient_manager_id is not null then insert into public.notifications(user_id,title,body,type,link) values(p_recipient_manager_id,'آلية في الطريق إلى موقع العمل',format('%s · DB %s انطلقت من الكراج إلى ورديتك',v_vehicle.vehicle_name,v_vehicle.db_number),'info','/manager/vehicle-trips');else insert into public.notifications(user_id,title,body,type,link) select mp.user_id,'آلية في الطريق إلى موقع العمل',format('%s · DB %s انطلقت من الكراج إلى منطقتك ووردّيتك',v_vehicle.vehicle_name,v_vehicle.db_number),'info','/manager/vehicle-trips' from public.manager_profiles mp where v_assignment.sector_id=any(mp.sectors) and mp.shift=v_assignment.shift and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager');end if;return v_row;
exception when unique_violation then raise exception 'GARAGE_DEPARTURE_ALREADY_OPEN';end$$;

create or replace function public.sector_confirm_vehicle_arrival(p_departure_id uuid,p_notes text default null)
returns public.garage_departures language plpgsql security definer set search_path=public,app as $$
declare u uuid:=auth.uid();d public.garage_departures;nm text;begin if u is null or not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;if length(coalesce(p_notes,''))>500 then raise exception 'GARAGE_STAGE_NOTES_TOO_LONG';end if;select * into d from public.garage_departures where id=p_departure_id and returned_at is null for update;if not found or d.arrived_at is not null or not(d.recipient_manager_id=u or d.recipient_manager_id is null and exists(select 1 from public.manager_profiles mp where mp.user_id=u and d.sector_id=any(mp.sectors) and d.shift=mp.shift)) then raise exception 'GARAGE_ARRIVAL_NOT_ALLOWED';end if;select coalesce(nullif(e.full_name,''),au.email,u::text) into nm from auth.users au left join public.employees e on e.user_id=au.id where au.id=u;update public.garage_departures set recipient_manager_id=u,recipient_manager_name=nm,arrived_at=now(),arrived_by=u,arrival_notes=nullif(trim(coalesce(p_notes,'')),'') where id=d.id returning * into d;insert into public.notifications(user_id,title,body,type,link) values(d.departed_by,'تم تأكيد وصول الآلية',format('أكد مسؤول القسم وصول الآلية DB %s إلى موقع العمل', (select db_number from public.garage_vehicles where id=d.vehicle_id)),'success','/central-garage/drivers-dispatch');return d;end$$;

create or replace function public.sector_send_vehicle_to_garage(p_departure_id uuid,p_notes text default null)
returns public.garage_departures language plpgsql security definer set search_path=public,app as $$
declare u uuid:=auth.uid();d public.garage_departures;begin if u is null or not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;if length(coalesce(p_notes,''))>500 then raise exception 'GARAGE_STAGE_NOTES_TOO_LONG';end if;update public.garage_departures set site_departed_at=now(),site_departed_by=u,site_departure_notes=nullif(trim(coalesce(p_notes,'')),'') where id=p_departure_id and recipient_manager_id=u and arrived_at is not null and site_departed_at is null and returned_at is null returning * into d;if not found then raise exception 'GARAGE_SITE_DEPARTURE_NOT_ALLOWED';end if;insert into public.notifications(user_id,title,body,type,link) values(d.departed_by,'الآلية في طريقها إلى الكراج',format('أنهت الآلية DB %s ورديتها وغادرت موقع العمل باتجاه الكراج',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'warning','/central-garage/drivers-dispatch');return d;end$$;

create or replace function public.garage_record_return(p_departure_id uuid)
returns public.garage_departures language plpgsql volatile security definer set search_path=public,app as $$
declare u uuid:=app.require_garage_actor();d public.garage_departures;begin select * into d from public.garage_departures where id=p_departure_id and returned_at is null for update;if not found then raise exception 'GARAGE_OPEN_DEPARTURE_NOT_FOUND';end if;if d.recipient_manager_id is not null and d.site_departed_at is null then raise exception 'GARAGE_VEHICLE_NOT_SENT_BACK';end if;update public.garage_departures set arrived_at=coalesce(arrived_at,now()),arrived_by=coalesce(arrived_by,u),site_departed_at=coalesce(site_departed_at,now()),site_departed_by=coalesce(site_departed_by,u),returned_at=now(),returned_by=u where id=d.id returning * into d;if d.recipient_manager_id is not null then insert into public.notifications(user_id,title,body,type,link) values(d.recipient_manager_id,'وصلت الآلية إلى الكراج',format('أكد الكراج استلام الآلية DB %s وإغلاق الانطلاقة',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'success','/manager/vehicle-trips');end if;return d;end$$;

create or replace function public.manager_vehicle_trips()
returns table(id uuid,vehicle_id uuid,driver_name text,shift text,sector_id smallint,departed_at timestamptz,arrived_at timestamptz,site_departed_at timestamptz,returned_at timestamptz,recipient_manager_id uuid,recipient_manager_name text,arrival_notes text,site_departure_notes text,vehicle_name text,db_number text,image_path text,area_name text,parent_sector text)
language plpgsql stable security definer set search_path=public,app as $$declare u uuid:=auth.uid();begin if u is null or not app.has_role(array['department_manager']) then raise exception 'SECTOR_MANAGER_FORBIDDEN';end if;return query select d.id,d.vehicle_id,d.driver_name,d.shift,d.sector_id,d.departed_at,d.arrived_at,d.site_departed_at,d.returned_at,d.recipient_manager_id,d.recipient_manager_name,d.arrival_notes,d.site_departure_notes,v.vehicle_name,v.db_number,v.image_path,s.name,s.parent_sector from public.garage_departures d join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where(d.recipient_manager_id=u or d.recipient_manager_id is null and exists(select 1 from public.manager_profiles mp where mp.user_id=u and d.sector_id=any(mp.sectors) and d.shift=mp.shift)) and(d.returned_at is null or (d.returned_at at time zone 'Asia/Baghdad')::date=(now() at time zone 'Asia/Baghdad')::date) order by(d.returned_at is null)desc,d.departed_at desc;end$$;

drop function if exists public.garage_today_departures();
create function public.garage_today_departures()
returns table(id uuid,vehicle_id uuid,driver_name text,shift text,sector_id smallint,departed_at timestamptz,arrived_at timestamptz,site_departed_at timestamptz,returned_at timestamptz,recipient_manager_id uuid,recipient_manager_name text,arrival_notes text,site_departure_notes text,notes text,vehicle_name text,db_number text,image_path text,area_name text,parent_sector text)
language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select d.id,d.vehicle_id,d.driver_name,d.shift,d.sector_id,d.departed_at,d.arrived_at,d.site_departed_at,d.returned_at,d.recipient_manager_id,d.recipient_manager_name,d.arrival_notes,d.site_departure_notes,d.notes,v.vehicle_name,v.db_number,v.image_path,s.name,s.parent_sector from public.garage_departures d join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where d.returned_at is null or(d.departed_at at time zone 'Asia/Baghdad')::date=(now() at time zone 'Asia/Baghdad')::date order by(d.returned_at is null)desc,d.departed_at desc;end$$;

revoke all on function public.garage_record_departure(uuid,text,uuid),public.garage_record_return(uuid),public.garage_today_departures(),public.garage_dispatch_recipients(uuid),public.sector_confirm_vehicle_arrival(uuid,text),public.sector_send_vehicle_to_garage(uuid,text),public.manager_vehicle_trips() from public,anon;
grant execute on function public.garage_record_departure(uuid,text,uuid),public.garage_record_return(uuid),public.garage_today_departures(),public.garage_dispatch_recipients(uuid) to authenticated;
grant execute on function public.sector_confirm_vehicle_arrival(uuid,text),public.sector_send_vehicle_to_garage(uuid,text),public.manager_vehicle_trips() to authenticated;
