-- 00099 · إدارة الزونات ودورة معالجة تنبيهات GPS وسجل الدخول والخروج.

alter table public.gps_operational_alerts
 add column if not exists acknowledged_at timestamptz,
 add column if not exists acknowledged_by uuid references auth.users(id) on delete set null,
 add column if not exists resolved_by uuid references auth.users(id) on delete set null,
 add column if not exists resolution_note text,
 add constraint gps_alert_ack_pair check((acknowledged_at is null and acknowledged_by is null)or(acknowledged_at is not null and acknowledged_by is not null)),
 add constraint gps_alert_resolution_note_length check(resolution_note is null or length(trim(resolution_note))between 3 and 500);

create table public.gps_zone_presence_state(
 device_id uuid not null references public.gps_devices(id)on delete cascade,
 geofence_id uuid not null references public.gps_geofences(id)on delete cascade,
 garage_vehicle_id uuid references public.garage_vehicles(id)on delete cascade,
 is_inside boolean not null,
 observed_at timestamptz not null,
 changed_at timestamptz not null,
 primary key(device_id,geofence_id)
);
create table public.gps_zone_events(
 id bigint generated by default as identity primary key,
 device_id uuid not null references public.gps_devices(id)on delete cascade,
 geofence_id uuid not null references public.gps_geofences(id)on delete cascade,
 garage_vehicle_id uuid references public.garage_vehicles(id)on delete set null,
 departure_id uuid references public.garage_departures(id)on delete set null,
 event_type text not null check(event_type in('enter','exit')),
 occurred_at timestamptz not null,
 latitude float8 not null check(latitude between -90 and 90),
 longitude float8 not null check(longitude between -180 and 180),
 created_at timestamptz not null default now()
);
create index gps_zone_events_vehicle_idx on public.gps_zone_events(garage_vehicle_id,occurred_at desc);
create index gps_zone_events_departure_idx on public.gps_zone_events(departure_id,occurred_at)where departure_id is not null;
create index gps_zone_events_zone_idx on public.gps_zone_events(geofence_id,occurred_at desc);
alter table public.gps_zone_presence_state enable row level security;
alter table public.gps_zone_events enable row level security;
create policy "gps zone state authorized read"on public.gps_zone_presence_state for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "gps zone events authorized read"on public.gps_zone_events for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));

create or replace function app.require_gps_operator()returns uuid language plpgsql stable security definer set search_path=public,app as $$declare u uuid:=auth.uid();begin if u is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;return u;end$$;

create or replace function public.gps_platform_geofence_save(p_id uuid,p_name text,p_polygon jsonb,p_color text default'#06b6d4')returns uuid
language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_gps_operator();gid uuid;pt jsonb;lat float8;lng float8;begin
 if length(trim(coalesce(p_name,'')))not between 2 and 160 then raise exception'GPS_ZONE_NAME_INVALID';end if;
 if jsonb_typeof(p_polygon)<>'array'or jsonb_array_length(p_polygon)<3 or jsonb_array_length(p_polygon)>500 then raise exception'GPS_ZONE_POLYGON_INVALID';end if;
 if coalesce(p_color,'')!~'^#[0-9a-fA-F]{6}$'then raise exception'GPS_ZONE_COLOR_INVALID';end if;
 for pt in select value from jsonb_array_elements(p_polygon)loop begin lat:=coalesce((pt->>'lat')::float8,(pt->>0)::float8);lng:=coalesce((pt->>'lng')::float8,(pt->>1)::float8);exception when others then raise exception'GPS_ZONE_POINT_INVALID';end;if lat not between -90 and 90 or lng not between -180 and 180 then raise exception'GPS_ZONE_POINT_INVALID';end if;end loop;
 if p_id is null then insert into public.gps_geofences(name,source,polygon,color,raw_data)values(trim(p_name),'platform',p_polygon,p_color,jsonb_build_object('created_by',u))returning id into gid;
 else update public.gps_geofences set name=trim(p_name),polygon=p_polygon,color=p_color,is_active=true,updated_at=now(),raw_data=raw_data||jsonb_build_object('updated_by',u)where id=p_id and source='platform' returning id into gid;if gid is null then raise exception'GPS_PLATFORM_ZONE_NOT_FOUND';end if;end if;
 return gid;
end$$;
create or replace function public.gps_platform_geofence_archive(p_id uuid)returns void language plpgsql security definer set search_path=public,app as $$begin perform app.require_gps_operator();update public.gps_geofences set is_active=false,updated_at=now()where id=p_id and source='platform'and is_active;if not found then raise exception'GPS_PLATFORM_ZONE_NOT_FOUND';end if;end$$;

create or replace function public.gps_alert_acknowledge(p_alert_id uuid)returns void language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_gps_operator();begin update public.gps_operational_alerts set acknowledged_at=coalesce(acknowledged_at,now()),acknowledged_by=coalesce(acknowledged_by,u)where id=p_alert_id and resolved_at is null;if not found then raise exception'GPS_ALERT_NOT_OPEN';end if;end$$;
create or replace function public.gps_alert_resolve(p_alert_id uuid,p_note text)returns void language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_gps_operator();begin if length(trim(coalesce(p_note,'')))not between 3 and 500 then raise exception'GPS_ALERT_RESOLUTION_NOTE_REQUIRED';end if;update public.gps_operational_alerts set acknowledged_at=coalesce(acknowledged_at,now()),acknowledged_by=coalesce(acknowledged_by,u),resolved_at=now(),resolved_by=u,resolution_note=trim(p_note)where id=p_alert_id and resolved_at is null;if not found then raise exception'GPS_ALERT_NOT_OPEN';end if;end$$;

drop function if exists public.gps_lvn_open_alerts(integer);
create function public.gps_lvn_open_alerts(p_limit integer default 100)
returns table(id uuid,device_id uuid,device_name text,garage_vehicle_id uuid,vehicle_name text,db_number text,departure_id uuid,alert_type text,severity text,title text,details jsonb,opened_at timestamptz,acknowledged_at timestamptz,acknowledged_by uuid)
language plpgsql stable security definer set search_path=public,app as $$begin
 perform app.require_gps_operator();if p_limit not between 1 and 500 then raise exception'GPS_PAGE_INVALID';end if;
 return query select a.id,a.device_id,d.name,a.garage_vehicle_id,v.vehicle_name,v.db_number,a.departure_id,a.alert_type,a.severity,a.title,a.details,a.opened_at,a.acknowledged_at,a.acknowledged_by
 from public.gps_operational_alerts a join public.gps_devices d on d.id=a.device_id left join public.garage_vehicles v on v.id=a.garage_vehicle_id
 where a.resolved_at is null order by a.acknowledged_at nulls first,case a.severity when'critical'then 1 when'warning'then 2 else 3 end,a.opened_at desc limit p_limit;
end$$;

create or replace function public.gps_zone_events_list(p_from timestamptz,p_to timestamptz,p_vehicle_id uuid default null,p_geofence_id uuid default null,p_limit integer default 200,p_offset integer default 0)
returns table(id bigint,event_type text,occurred_at timestamptz,device_id uuid,device_name text,garage_vehicle_id uuid,vehicle_name text,db_number text,departure_id uuid,geofence_id uuid,geofence_name text,latitude float8,longitude float8,total_count bigint)
language plpgsql stable security definer set search_path=public,app as $$begin
 perform app.require_gps_operator();if p_from is null or p_to is null or p_to<=p_from or p_to-p_from>interval'90 days'then raise exception'GPS_DATE_RANGE_INVALID';end if;if p_limit not between 1 and 500 or p_offset<0 then raise exception'GPS_PAGE_INVALID';end if;
 return query select e.id,e.event_type,e.occurred_at,e.device_id,d.name,e.garage_vehicle_id,v.vehicle_name,v.db_number,e.departure_id,e.geofence_id,g.name,e.latitude,e.longitude,count(*)over()
 from public.gps_zone_events e join public.gps_devices d on d.id=e.device_id join public.gps_geofences g on g.id=e.geofence_id left join public.garage_vehicles v on v.id=e.garage_vehicle_id
 where e.occurred_at between p_from and p_to and(p_vehicle_id is null or e.garage_vehicle_id=p_vehicle_id)and(p_geofence_id is null or e.geofence_id=p_geofence_id)
 order by e.occurred_at desc limit p_limit offset p_offset;
end$$;

create or replace function public.gps_evaluate_zone_transitions()returns integer language plpgsql security definer set search_path=public,app as $$declare n integer:=0;begin
 with current_state as(
  select d.id device_id,b.garage_vehicle_id,g.id geofence_id,p.fix_time observed_at,p.latitude,p.longitude,app.gps_point_in_polygon(p.latitude,p.longitude,g.polygon)is_inside,
   (select dep.id from public.garage_departures dep where dep.vehicle_id=b.garage_vehicle_id and dep.returned_at is null order by dep.departed_at desc limit 1)departure_id
  from public.gps_devices d join public.gps_device_positions p on p.device_id=d.id join public.gps_vehicle_bindings b on b.device_id=d.id join public.gps_vehicle_geofences vg on vg.garage_vehicle_id=b.garage_vehicle_id join public.gps_geofences g on g.id=vg.geofence_id and g.is_active where p.fix_time is not null
 ),changes as(
  select c.* from current_state c join public.gps_zone_presence_state s on s.device_id=c.device_id and s.geofence_id=c.geofence_id where s.is_inside<>c.is_inside and c.observed_at>s.observed_at
 ),ins as(
  insert into public.gps_zone_events(device_id,geofence_id,garage_vehicle_id,departure_id,event_type,occurred_at,latitude,longitude)
  select device_id,geofence_id,garage_vehicle_id,departure_id,case when is_inside then'enter'else'exit'end,observed_at,latitude,longitude from changes returning 1
 )select count(*)into n from ins;
 with current_state as(
  select d.id device_id,b.garage_vehicle_id,g.id geofence_id,p.fix_time observed_at,app.gps_point_in_polygon(p.latitude,p.longitude,g.polygon)is_inside
  from public.gps_devices d join public.gps_device_positions p on p.device_id=d.id join public.gps_vehicle_bindings b on b.device_id=d.id join public.gps_vehicle_geofences vg on vg.garage_vehicle_id=b.garage_vehicle_id join public.gps_geofences g on g.id=vg.geofence_id and g.is_active where p.fix_time is not null
 )insert into public.gps_zone_presence_state(device_id,geofence_id,garage_vehicle_id,is_inside,observed_at,changed_at)
 select device_id,geofence_id,garage_vehicle_id,is_inside,observed_at,observed_at from current_state
 on conflict(device_id,geofence_id)do update set garage_vehicle_id=excluded.garage_vehicle_id,is_inside=excluded.is_inside,observed_at=excluded.observed_at,changed_at=case when gps_zone_presence_state.is_inside<>excluded.is_inside then excluded.observed_at else gps_zone_presence_state.changed_at end where excluded.observed_at>gps_zone_presence_state.observed_at;
 return n;
end$$;

-- تضمين انتقالات الزونات في نفس دورة تقييم التنبيهات الحالية.
create or replace function public.gps_evaluate_operational_alerts()returns void language plpgsql security definer set search_path=public,app as $$begin
 update public.gps_operational_alerts a set resolved_at=now()where a.resolved_at is null and((a.alert_type='gps_offline'and exists(select 1 from public.gps_devices d where d.id=a.device_id and d.online_status='online'))or(a.alert_type='gps_stale'and exists(select 1 from public.gps_device_positions p where p.device_id=a.device_id and p.fix_time>=now()-interval'5 minutes'))or(a.alert_type='outside_zone'and exists(select 1 from public.gps_device_positions p join public.gps_vehicle_bindings b on b.device_id=p.device_id where p.device_id=a.device_id and exists(select 1 from public.gps_vehicle_geofences vg join public.gps_geofences g on g.id=vg.geofence_id and g.is_active where vg.garage_vehicle_id=b.garage_vehicle_id and app.gps_point_in_polygon(p.latitude,p.longitude,g.polygon)))));
 insert into public.gps_operational_alerts(device_id,garage_vehicle_id,departure_id,alert_type,severity,title,details)select d.id,b.garage_vehicle_id,dep.id,'gps_offline','critical','انقطع اتصال GPS أثناء الانطلاقة',jsonb_build_object('last_seen_at',d.last_seen_at)from public.gps_devices d join public.gps_vehicle_bindings b on b.device_id=d.id join public.garage_departures dep on dep.vehicle_id=b.garage_vehicle_id and dep.returned_at is null where d.online_status='offline'and not exists(select 1 from public.gps_operational_alerts a where a.device_id=d.id and a.alert_type='gps_offline'and(a.resolved_at is null or a.resolved_by is not null and a.resolved_at>now()-interval'30 minutes'));
 insert into public.gps_operational_alerts(device_id,garage_vehicle_id,departure_id,alert_type,severity,title,details)select d.id,b.garage_vehicle_id,dep.id,'gps_stale','warning','توقفت قراءات GPS أثناء الانطلاقة',jsonb_build_object('fix_time',p.fix_time)from public.gps_devices d join public.gps_device_positions p on p.device_id=d.id join public.gps_vehicle_bindings b on b.device_id=d.id join public.garage_departures dep on dep.vehicle_id=b.garage_vehicle_id and dep.returned_at is null where p.fix_time<now()-interval'5 minutes'and not exists(select 1 from public.gps_operational_alerts a where a.device_id=d.id and a.alert_type='gps_stale'and(a.resolved_at is null or a.resolved_by is not null and a.resolved_at>now()-interval'30 minutes'));
 insert into public.gps_operational_alerts(device_id,garage_vehicle_id,departure_id,alert_type,severity,title,details)select d.id,b.garage_vehicle_id,dep.id,'outside_zone','warning','الآلية خارج الزون المخصص',jsonb_build_object('latitude',p.latitude,'longitude',p.longitude)from public.gps_devices d join public.gps_device_positions p on p.device_id=d.id join public.gps_vehicle_bindings b on b.device_id=d.id join public.garage_departures dep on dep.vehicle_id=b.garage_vehicle_id and dep.returned_at is null where exists(select 1 from public.gps_vehicle_geofences vg where vg.garage_vehicle_id=b.garage_vehicle_id)and not exists(select 1 from public.gps_vehicle_geofences vg join public.gps_geofences g on g.id=vg.geofence_id and g.is_active where vg.garage_vehicle_id=b.garage_vehicle_id and app.gps_point_in_polygon(p.latitude,p.longitude,g.polygon))and not exists(select 1 from public.gps_operational_alerts a where a.device_id=d.id and a.alert_type='outside_zone'and(a.resolved_at is null or a.resolved_by is not null and a.resolved_at>now()-interval'30 minutes'));
 perform public.gps_evaluate_zone_transitions();
end$$;

revoke all on table public.gps_zone_presence_state,public.gps_zone_events from anon,authenticated;
grant select on table public.gps_zone_presence_state,public.gps_zone_events to authenticated;
revoke all on function app.require_gps_operator(),public.gps_platform_geofence_save(uuid,text,jsonb,text),public.gps_platform_geofence_archive(uuid),public.gps_alert_acknowledge(uuid),public.gps_alert_resolve(uuid,text),public.gps_zone_events_list(timestamptz,timestamptz,uuid,uuid,integer,integer),public.gps_lvn_open_alerts(integer)from public,anon;
grant execute on function public.gps_platform_geofence_save(uuid,text,jsonb,text),public.gps_platform_geofence_archive(uuid),public.gps_alert_acknowledge(uuid),public.gps_alert_resolve(uuid,text),public.gps_zone_events_list(timestamptz,timestamptz,uuid,uuid,integer,integer),public.gps_lvn_open_alerts(integer)to authenticated;
revoke all on function public.gps_evaluate_zone_transitions()from public,anon,authenticated;
grant execute on function public.gps_evaluate_zone_transitions()to service_role;
