-- 00097 · سياسات الإشعارات ودورة تنسيق إرسال الآلية للصيانة
create table public.notification_workflow_policies(
 id uuid primary key default gen_random_uuid(),event_key text not null default'maintenance_dispatch',sector_id smallint references public.sectors(id),vehicle_category text,
 mode text not null default'notify_only',emergency_bypass boolean not null default true,enabled boolean not null default true,
 recipient_roles text[]not null default array['central_garage_officer'],in_app_enabled boolean not null default true,push_enabled boolean not null default true,sound_enabled boolean not null default true,
 escalation_minutes integer not null default 15,notes text,updated_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint workflow_event_check check(event_key in('maintenance_dispatch')),
 constraint workflow_mode_check check(mode in('notify_only','ack_required','approval_required')),
 constraint workflow_vehicle_category_check check(vehicle_category is null or vehicle_category in('compactor_small','compactor_large','truck','shovel','tipper','tanker','sweeper','strat','other')),
 constraint workflow_escalation_check check(escalation_minutes between 1 and 1440),
 constraint workflow_roles_check check(cardinality(recipient_roles)between 1 and 8 and recipient_roles<@array['central_garage_officer','maintenance','ops_room','it_admin','super_admin']::text[]),
 constraint workflow_notes_check check(length(coalesce(notes,''))<=500)
);
create unique index workflow_policy_scope_unique on public.notification_workflow_policies(event_key,coalesce(sector_id,0),coalesce(vehicle_category,'*'));
alter table public.notification_workflow_policies enable row level security;
create policy "workflow policies authorized read" on public.notification_workflow_policies for select to authenticated using(app.has_role(array['it_admin','super_admin','central_garage_officer','ops_room']));
create trigger trg_audit_notification_workflow_policies after insert or update or delete on public.notification_workflow_policies for each row execute function app.audit_trigger();
insert into public.notification_workflow_policies(event_key,mode,emergency_bypass,notes)values('maintenance_dispatch','notify_only',true,'الوضع الافتراضي: إبلاغ الكراج دون تعطيل العمل الميداني');

alter table public.notifications add column in_app_visible boolean not null default true,add column push_allowed boolean not null default true,add column sound_allowed boolean not null default true;
drop function public.notification_center(integer,timestamptz);
create function public.notification_center(p_limit integer default 30,p_before timestamptz default null)
returns table(id uuid,title text,body text,type text,category text,priority text,link text,is_read boolean,read_at timestamptz,created_at timestamptz,entity_type text,entity_id uuid,action_label text,sound_allowed boolean)
language plpgsql stable security definer set search_path=public,app as $$begin if auth.uid()is null then raise exception'NOTIFICATIONS_UNAUTHENTICATED';end if;if p_limit not between 1 and 50 then raise exception'NOTIFICATIONS_LIMIT_INVALID';end if;return query select n.id,n.title,n.body,n.type,n.category,n.priority,n.link,n.is_read,n.read_at,n.created_at,n.entity_type,n.entity_id,n.action_label,n.sound_allowed from public.notifications n where n.user_id=auth.uid()and n.in_app_visible and n.dismissed_at is null and(n.expires_at is null or n.expires_at>now())and(p_before is null or n.created_at<p_before)order by n.created_at desc limit p_limit;end$$;
create or replace function public.notification_unread_count()returns bigint language sql stable security definer set search_path=public as $$select count(*)from public.notifications where user_id=auth.uid()and in_app_visible and not is_read and dismissed_at is null and(expires_at is null or expires_at>now())$$;
create or replace function app.queue_notification_push()returns trigger language plpgsql security definer set search_path=public,app as $$begin insert into public.notification_push_deliveries(notification_id,subscription_id,next_attempt_at)select new.id,s.id,case when new.priority='critical'then now()else app.notification_next_push_time(p.quiet_from,p.quiet_to)end from public.notification_push_subscriptions s join public.notification_preferences p on p.user_id=s.user_id where new.push_allowed and s.user_id=new.user_id and s.is_active and p.push_enabled and(not p.critical_only or new.priority='critical')on conflict(notification_id,subscription_id)do nothing;return new;end$$;
grant execute on function public.notification_center(integer,timestamptz)to authenticated;

alter table public.vehicle_maintenance_cases drop constraint if exists vehicle_maintenance_cases_status_check;
alter table public.vehicle_maintenance_cases
 add constraint vehicle_maintenance_cases_status_check check(status in('to_maintenance','at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready','to_work','to_garage','returned_to_work','closed_at_garage','cancelled')),
 add column dispatch_policy text not null default'notify_only' check(dispatch_policy in('notify_only','ack_required','approval_required')),
 add column garage_decision_status text not null default'not_required' check(garage_decision_status in('not_required','awaiting_ack','acknowledged','awaiting_approval','approved','rejected')),
 add column garage_decided_at timestamptz,
 add column garage_decided_by uuid references auth.users(id),
 add column garage_decision_notes text check(length(coalesce(garage_decision_notes,''))<=500);
create index maintenance_garage_decision_queue on public.vehicle_maintenance_cases(garage_decision_status,reported_at)where garage_decision_status in('awaiting_ack','awaiting_approval');

create or replace function app.effective_notification_policy(p_event text,p_sector smallint,p_category text)returns public.notification_workflow_policies language sql stable security definer set search_path=public as $$select p from public.notification_workflow_policies p where p.event_key=p_event and p.enabled and(p.sector_id is null or p.sector_id=p_sector)and(p.vehicle_category is null or p.vehicle_category=p_category)order by(p.sector_id is not null)::int+(p.vehicle_category is not null)::int desc,p.updated_at desc limit 1$$;

create or replace function public.notification_workflow_policies_list()
returns table(id uuid,event_key text,sector_id smallint,sector_name text,vehicle_category text,mode text,emergency_bypass boolean,enabled boolean,recipient_roles text[],in_app_enabled boolean,push_enabled boolean,sound_enabled boolean,escalation_minutes integer,notes text,updated_at timestamptz)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['it_admin','super_admin'])then raise exception'WORKFLOW_POLICY_FORBIDDEN';end if;return query select p.id,p.event_key,p.sector_id,s.name,p.vehicle_category,p.mode,p.emergency_bypass,p.enabled,p.recipient_roles,p.in_app_enabled,p.push_enabled,p.sound_enabled,p.escalation_minutes,p.notes,p.updated_at from public.notification_workflow_policies p left join public.sectors s on s.id=p.sector_id order by(p.sector_id is null and p.vehicle_category is null)desc,s.name,p.vehicle_category;end$$;
create or replace function public.notification_workflow_policy_save(p_id uuid,p_sector_id smallint,p_vehicle_category text,p_mode text,p_emergency_bypass boolean,p_enabled boolean,p_recipient_roles text[],p_in_app boolean,p_push boolean,p_sound boolean,p_escalation_minutes integer,p_notes text default null)
returns uuid language plpgsql security definer set search_path=public,app as $$declare r uuid;begin if not app.has_role(array['it_admin','super_admin'])then raise exception'WORKFLOW_POLICY_FORBIDDEN';end if;if p_mode not in('notify_only','ack_required','approval_required')or p_escalation_minutes not between 1 and 1440 then raise exception'WORKFLOW_POLICY_INVALID';end if;
 if p_id is null then insert into public.notification_workflow_policies(sector_id,vehicle_category,mode,emergency_bypass,enabled,recipient_roles,in_app_enabled,push_enabled,sound_enabled,escalation_minutes,notes,updated_by)values(p_sector_id,p_vehicle_category,p_mode,p_emergency_bypass,p_enabled,p_recipient_roles,p_in_app,p_push,p_sound,p_escalation_minutes,nullif(trim(coalesce(p_notes,'')),''),auth.uid())returning id into r;
 else update public.notification_workflow_policies set sector_id=p_sector_id,vehicle_category=p_vehicle_category,mode=p_mode,emergency_bypass=p_emergency_bypass,enabled=p_enabled,recipient_roles=p_recipient_roles,in_app_enabled=p_in_app,push_enabled=p_push,sound_enabled=p_sound,escalation_minutes=p_escalation_minutes,notes=nullif(trim(coalesce(p_notes,'')),''),updated_by=auth.uid(),updated_at=now()where id=p_id returning id into r;if r is null then raise exception'WORKFLOW_POLICY_NOT_FOUND';end if;end if;return r;end$$;
create or replace function public.notification_workflow_policy_delete(p_id uuid)returns void language plpgsql security definer set search_path=public,app as $$begin if not app.has_role(array['it_admin','super_admin'])then raise exception'WORKFLOW_POLICY_FORBIDDEN';end if;if exists(select 1 from public.notification_workflow_policies where id=p_id and sector_id is null and vehicle_category is null)then raise exception'WORKFLOW_DEFAULT_POLICY_REQUIRED';end if;delete from public.notification_workflow_policies where id=p_id;if not found then raise exception'WORKFLOW_POLICY_NOT_FOUND';end if;end$$;

-- يعيد بناء الإرسال مع احترام السياسة الفعلية ومنع تجاوز الموافقة على الخادم.
create or replace function public.sector_send_vehicle_to_maintenance(p_departure_id uuid,p_fault_type text,p_priority text default'normal',p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();d public.garage_departures;v public.garage_vehicles;b public.sector_breakdowns;c public.vehicle_maintenance_cases;l public.vehicle_trip_legs;nm text;pol public.notification_workflow_policies;effective_mode text;
begin if not app.has_role(array['department_manager'])then raise exception'SECTOR_MANAGER_FORBIDDEN';end if;if length(trim(coalesce(p_fault_type,'')))<3 or p_priority not in('normal','urgent','critical')then raise exception'MAINTENANCE_INPUT_INVALID';end if;select*into d from public.garage_departures where id=p_departure_id and recipient_manager_id=u and arrived_at is not null and returned_at is null for update;if not found or exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null)then raise exception'TRIP_NOT_AT_MANAGER_SITE';end if;if exists(select 1 from public.vehicle_trip_legs where departure_id=d.id order by sequence_no desc limit 1)and(select destination_type from public.vehicle_trip_legs where departure_id=d.id order by sequence_no desc limit 1)<>'work_site'then raise exception'TRIP_NOT_AT_MANAGER_SITE';end if;if exists(select 1 from public.vehicle_maintenance_cases where departure_id=d.id and completed_at is null)then raise exception'MAINTENANCE_CASE_ALREADY_OPEN';end if;select*into v from public.garage_vehicles where id=d.vehicle_id;pol:=app.effective_notification_policy('maintenance_dispatch',d.sector_id,v.vehicle_category);effective_mode:=coalesce(pol.mode,'notify_only');if p_priority='critical'and coalesce(pol.emergency_bypass,true)then effective_mode:='notify_only';end if;
 select*into b from public.sector_breakdowns where manager_id=u and lower(trim(db_number))=lower(trim(v.db_number))and status='logged'and archived_at is null order by created_at desc limit 1 for update;if found then if b.departure_id is not null and b.departure_id<>d.id then raise exception'BREAKDOWN_ALREADY_OPEN';end if;update public.sector_breakdowns set departure_id=d.id,vehicle_id=v.id,fault_type=trim(p_fault_type),notes=coalesce(nullif(trim(coalesce(p_notes,'')),''),notes)where id=b.id returning*into b;else select coalesce(nullif(trim(e.full_name),''),au.email,u::text)into nm from auth.users au left join public.employees e on e.user_id=au.id where au.id=u;insert into public.sector_breakdowns(manager_id,manager_name,shift,sectors,db_number,fault_type,notes,status,departure_id,vehicle_id)values(u,nm,d.shift,array[d.sector_id]::smallint[],v.db_number,trim(p_fault_type),nullif(trim(coalesce(p_notes,'')),''),'logged',d.id,v.id)returning*into b;end if;
 insert into public.vehicle_maintenance_cases(departure_id,breakdown_id,vehicle_id,manager_id,fault_type,priority,dispatch_policy,garage_decision_status)values(d.id,b.id,v.id,u,trim(p_fault_type),p_priority,effective_mode,case effective_mode when'ack_required'then'awaiting_ack'when'approval_required'then'awaiting_approval'else'not_required'end)returning*into c;
 if effective_mode<>'approval_required'then insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes)values(d.id,app.next_trip_leg_sequence(d.id),'work_site','maintenance',u,nullif(trim(coalesce(p_notes,'')),''))returning*into l;insert into public.notifications(user_id,title,body,type,category,priority,link,entity_type,entity_id,dedupe_key)select ur.user_id,'آلية في الطريق إلى الصيانة',format('الآلية DB %s غادرت موقع العمل إلى الصيانة',v.db_number),'error','maintenance',case when p_priority='critical'then'critical'else'high'end,'/maintenance/vehicle-cases','maintenance_case',c.id,'maintenance_case:'||c.id::text||':maintenance'from public.user_roles ur where ur.role='maintenance'on conflict(user_id,dedupe_key)where dedupe_key is not null do nothing;end if;return c;end$$;

create or replace function app.notify_garage_new_maintenance_case()returns trigger language plpgsql security definer set search_path=public,app as $$declare v public.garage_vehicles;pol public.notification_workflow_policies;begin select*into v from public.garage_vehicles where id=new.vehicle_id;pol:=app.effective_notification_policy('maintenance_dispatch',(select sector_id from public.garage_departures where id=new.departure_id),v.vehicle_category);insert into public.notifications(user_id,title,body,type,category,priority,link,entity_type,entity_id,action_label,dedupe_key,in_app_visible,push_allowed,sound_allowed)select distinct ur.user_id,case new.garage_decision_status when'awaiting_approval'then'طلب موافقة لإرسال آلية إلى الصيانة'when'awaiting_ack'then'آلية إلى الصيانة تحتاج تأكيد الاستلام'else'بلاغ آلية متجهة إلى الصيانة'end,format('%s · DB %s — %s',v.vehicle_name,v.db_number,new.fault_type),case when new.priority='critical'then'error'else'warning'end,'maintenance',case when new.priority='critical'then'critical'when new.priority='urgent'then'high'else'normal'end,'/central-garage/maintenance-coordination','maintenance_case',new.id,case when new.garage_decision_status='awaiting_approval'then'مراجعة الطلب'when new.garage_decision_status='awaiting_ack'then'تأكيد الاستلام'else'فتح التفاصيل'end,'maintenance_case:'||new.id::text||':garage',coalesce(pol.in_app_enabled,true),coalesce(pol.push_enabled,true),coalesce(pol.sound_enabled,true)from public.user_roles ur where ur.role=any(coalesce(pol.recipient_roles,array['central_garage_officer']))on conflict(user_id,dedupe_key)where dedupe_key is not null do nothing;return new;end$$;

create or replace function public.maintenance_vehicle_cases()
returns table(case_id uuid,departure_id uuid,breakdown_id uuid,vehicle_id uuid,vehicle_name text,db_number text,driver_name text,shift text,area_name text,manager_name text,status text,fault_type text,priority text,reported_at timestamptz,arrived_at timestamptz,diagnosis text,work_notes text,parts_notes text,progress smallint,expected_completion_at timestamptz,ready_at timestamptz,departed_maintenance_at timestamptz,completed_at timestamptz)
language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance'])then raise exception'MAINTENANCE_FORBIDDEN';end if;return query select c.id,c.departure_id,c.breakdown_id,c.vehicle_id,v.vehicle_name,v.db_number,d.driver_name,d.shift,s.name,d.recipient_manager_name,c.status,c.fault_type,c.priority,c.reported_at,c.arrived_at,c.diagnosis,c.work_notes,c.parts_notes,c.progress,c.expected_completion_at,c.ready_at,c.departed_maintenance_at,c.completed_at from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join public.sectors s on s.id=d.sector_id where c.garage_decision_status not in('awaiting_approval','rejected')and(c.completed_at is null or(c.completed_at at time zone'Asia/Baghdad')::date>=(now()at time zone'Asia/Baghdad')::date-30)order by(c.completed_at is null)desc,c.reported_at desc;end$$;

create or replace function public.garage_maintenance_coordination()
returns table(case_id uuid,departure_id uuid,vehicle_name text,db_number text,vehicle_category text,driver_name text,sector_name text,manager_name text,fault_type text,priority text,dispatch_policy text,decision_status text,reported_at timestamptz,decision_notes text)
language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select c.id,c.departure_id,v.vehicle_name,v.db_number,v.vehicle_category,d.driver_name,s.name,d.recipient_manager_name,c.fault_type,c.priority,c.dispatch_policy,c.garage_decision_status,c.reported_at,c.garage_decision_notes from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join public.sectors s on s.id=d.sector_id where c.garage_decision_status in('awaiting_ack','awaiting_approval','acknowledged','approved','rejected')and c.reported_at>now()-interval'30 days'order by c.garage_decision_status in('awaiting_ack','awaiting_approval')desc,c.reported_at desc;end$$;
create or replace function public.garage_decide_maintenance_dispatch(p_case_id uuid,p_decision text,p_notes text default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();c public.vehicle_maintenance_cases;d public.garage_departures;v public.garage_vehicles;l public.vehicle_trip_legs;begin if p_decision not in('acknowledge','approve','reject')or length(coalesce(p_notes,''))>500 then raise exception'MAINTENANCE_DECISION_INVALID';end if;select*into c from public.vehicle_maintenance_cases where id=p_case_id for update;if not found then raise exception'MAINTENANCE_CASE_NOT_FOUND';end if;select*into d from public.garage_departures where id=c.departure_id for update;select*into v from public.garage_vehicles where id=c.vehicle_id;
 if p_decision='acknowledge'then if c.garage_decision_status<>'awaiting_ack'then raise exception'MAINTENANCE_ACK_NOT_ALLOWED';end if;update public.vehicle_maintenance_cases set garage_decision_status='acknowledged',garage_decided_at=now(),garage_decided_by=u,garage_decision_notes=nullif(trim(coalesce(p_notes,'')),'')where id=c.id returning*into c;
 elsif p_decision='approve'then if c.garage_decision_status<>'awaiting_approval'or exists(select 1 from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null)then raise exception'MAINTENANCE_APPROVAL_NOT_ALLOWED';end if;insert into public.vehicle_trip_legs(departure_id,sequence_no,origin_type,destination_type,departed_by,departure_notes)values(d.id,app.next_trip_leg_sequence(d.id),'work_site','maintenance',u,'اعتمد الكراج المركزي حركة الصيانة')returning*into l;update public.vehicle_maintenance_cases set garage_decision_status='approved',garage_decided_at=now(),garage_decided_by=u,garage_decision_notes=nullif(trim(coalesce(p_notes,'')),'')where id=c.id returning*into c;insert into public.notifications(user_id,title,body,type,category,priority,link,entity_type,entity_id,dedupe_key)select ur.user_id,'اعتمد الكراج إرسال الآلية إلى الصيانة',format('الآلية DB %s أصبحت في الطريق إلى الصيانة',v.db_number),'success','maintenance','high','/maintenance/vehicle-cases','maintenance_case',c.id,'maintenance_case:'||c.id::text||':approved-maintenance'from public.user_roles ur where ur.role='maintenance'on conflict(user_id,dedupe_key)where dedupe_key is not null do nothing;
 else if c.garage_decision_status<>'awaiting_approval'then raise exception'MAINTENANCE_REJECTION_NOT_ALLOWED';end if;if length(trim(coalesce(p_notes,'')))<3 then raise exception'MAINTENANCE_REJECTION_REASON_REQUIRED';end if;update public.vehicle_maintenance_cases set garage_decision_status='rejected',garage_decided_at=now(),garage_decided_by=u,garage_decision_notes=trim(p_notes),status='cancelled',completed_at=now(),updated_at=now()where id=c.id returning*into c;end if;
 insert into public.notifications(user_id,title,body,type,category,priority,link,entity_type,entity_id,dedupe_key)values(c.manager_id,case p_decision when'acknowledge'then'استلم الكراج بلاغ الصيانة'when'approve'then'وافق الكراج على حركة الصيانة'else'لم يعتمد الكراج حركة الصيانة'end,case when p_decision='reject'then coalesce(c.garage_decision_notes,'راجع الكراج المركزي')else format('الآلية DB %s — تم تحديث التنسيق مع الكراج',v.db_number)end,case when p_decision='reject'then'error'else'success'end,'maintenance',case when p_decision='reject'then'high'else'normal'end,'/manager/vehicle-trips','maintenance_case',c.id,'maintenance_case:'||c.id::text||':decision');return c;end$$;
create or replace function public.sector_trip_maintenance_state(p_departure_id uuid)returns jsonb language plpgsql stable security definer set search_path=public,app as $$declare d public.garage_departures;r jsonb;begin select*into d from public.garage_departures where id=p_departure_id;if not found or not(d.recipient_manager_id=auth.uid()or app.has_role(array['central_garage_officer','ops_room','super_admin']))then raise exception'MAINTENANCE_STATE_FORBIDDEN';end if;select to_jsonb(x)into r from(select c.id case_id,c.dispatch_policy,c.garage_decision_status decision_status,c.garage_decision_notes,c.reported_at from public.vehicle_maintenance_cases c where c.departure_id=d.id order by c.reported_at desc limit 1)x;return coalesce(r,'{}');end$$;

create or replace function public.notification_evaluate_workflow_escalations()returns integer language plpgsql security definer set search_path=public,app as $$declare n integer;begin if coalesce(auth.jwt()->>'role','')<>'service_role'then raise exception'WORKFLOW_SERVICE_ONLY';end if;insert into public.notifications(user_id,title,body,type,category,priority,link,entity_type,entity_id,dedupe_key)select ur.user_id,'تأخر إجراء الكراج على طلب صيانة',format('طلب DB %s ما زال %s منذ %s دقيقة',v.db_number,case c.garage_decision_status when'awaiting_ack'then'دون تأكيد استلام'else'بانتظار الموافقة'end,floor(extract(epoch from(now()-c.reported_at))/60)), 'error','maintenance','critical','/central-garage/maintenance-coordination','maintenance_case',c.id,'maintenance_case:'||c.id::text||':escalation'from public.vehicle_maintenance_cases c join public.garage_departures d on d.id=c.departure_id join public.garage_vehicles v on v.id=c.vehicle_id join lateral(select p.escalation_minutes from public.notification_workflow_policies p where p.event_key='maintenance_dispatch'and p.enabled and(p.sector_id is null or p.sector_id=d.sector_id)and(p.vehicle_category is null or p.vehicle_category=v.vehicle_category)order by(p.sector_id is not null)::int+(p.vehicle_category is not null)::int desc limit 1)p on true join public.user_roles ur on ur.role in('it_admin','super_admin')where c.garage_decision_status in('awaiting_ack','awaiting_approval')and now()-c.reported_at>make_interval(mins=>p.escalation_minutes)on conflict(user_id,dedupe_key)where dedupe_key is not null do nothing;get diagnostics n=row_count;return n;end$$;

revoke all on function app.effective_notification_policy(text,smallint,text)from public,anon,authenticated;
revoke all on function public.notification_workflow_policies_list(),public.notification_workflow_policy_save(uuid,smallint,text,text,boolean,boolean,text[],boolean,boolean,boolean,integer,text),public.notification_workflow_policy_delete(uuid),public.garage_maintenance_coordination(),public.garage_decide_maintenance_dispatch(uuid,text,text),public.sector_trip_maintenance_state(uuid)from public,anon;
grant execute on function public.notification_workflow_policies_list(),public.notification_workflow_policy_save(uuid,smallint,text,text,boolean,boolean,text[],boolean,boolean,boolean,integer,text),public.notification_workflow_policy_delete(uuid),public.garage_maintenance_coordination(),public.garage_decide_maintenance_dispatch(uuid,text,text),public.sector_trip_maintenance_state(uuid)to authenticated;
revoke all on function public.notification_evaluate_workflow_escalations()from public,anon,authenticated;grant execute on function public.notification_evaluate_workflow_escalations()to service_role;
