-- 00092 · مركز بيانات LVN GPS لغرفة العمليات (دون خرائط)
-- الأسرار لا تحفظ في PostgreSQL؛ تبقى في Edge Function secrets فقط.

alter table public.gps_providers add column if not exists base_url text;
alter table public.gps_providers add column if not exists sync_cursor text;
alter table public.gps_providers add column if not exists last_full_sync_at timestamptz;
alter table public.gps_providers add column if not exists last_incremental_sync_at timestamptz;
alter table public.gps_providers add column if not exists last_success_at timestamptz;
alter table public.gps_providers add column if not exists last_error_at timestamptz;
alter table public.gps_providers add column if not exists last_error_code text;
alter table public.gps_providers add column if not exists api_version text;

insert into public.gps_providers(name,type,base_url,is_active)
select 'LVN GPS','vendor_api','https://track.gpslvn.iq/api',true
where not exists(select 1 from public.gps_providers where type='vendor_api' and base_url='https://track.gpslvn.iq/api');

create table public.gps_devices(
 id uuid primary key default gen_random_uuid(),
 provider_id uuid not null references public.gps_providers(id) on delete cascade,
 external_id text not null,
 name text not null,
 imei text,
 sim_number text,
 msisdn text,
 vin text,
 plate_number text,
 registration_number text,
 object_owner text,
 device_model text,
 group_id text,
 driver_name text,
 protocol text,
 online_status text not null default 'unknown' check(online_status in('online','offline','unknown')),
 alarm text,
 is_active boolean not null default true,
 vendor_updated_at timestamptz,
 last_seen_at timestamptz,
 sensors jsonb not null default '[]',
 services jsonb not null default '[]',
 raw_data jsonb not null default '{}',
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(provider_id,external_id)
);
create table public.gps_device_positions(
 device_id uuid primary key references public.gps_devices(id) on delete cascade,
 latitude double precision,
 longitude double precision,
 speed double precision,
 speed_unit text,
 course double precision,
 altitude double precision,
 power text,
 address text,
 fix_time timestamptz,
 received_at timestamptz not null default now(),
 raw_data jsonb not null default '{}',
 check(latitude is null or latitude between -90 and 90),check(longitude is null or longitude between -180 and 180),check(speed is null or speed>=0),check(course is null or course between 0 and 360)
);
create table public.gps_device_position_history(
 id bigint generated by default as identity primary key,
 device_id uuid not null references public.gps_devices(id) on delete cascade,
 latitude double precision,
 longitude double precision,
 speed double precision,
 speed_unit text,
 course double precision,
 altitude double precision,
 power text,
 address text,
 fix_time timestamptz not null,
 received_at timestamptz not null default now(),
 raw_data jsonb not null default '{}',
 unique(device_id,fix_time),
 check(latitude is null or latitude between -90 and 90),check(longitude is null or longitude between -180 and 180),check(speed is null or speed>=0)
);
create table public.gps_vehicle_bindings(
 id uuid primary key default gen_random_uuid(),device_id uuid not null unique references public.gps_devices(id) on delete cascade,
 garage_vehicle_id uuid not null unique references public.garage_vehicles(id) on delete cascade,
 match_method text not null check(match_method in('vin','plate','registration','manual')),
 confidence numeric(5,2) not null default 100 check(confidence between 0 and 100),
 bound_by uuid references auth.users(id) on delete set null,bound_at timestamptz not null default now(),notes text check(length(notes)<=500)
);
create table public.gps_sync_runs(
 id uuid primary key default gen_random_uuid(),provider_id uuid not null references public.gps_providers(id) on delete cascade,
 sync_type text not null check(sync_type in('connection_test','full','incremental')),
 status text not null default 'running' check(status in('running','success','partial','failed')),
 started_at timestamptz not null default now(),finished_at timestamptz,pages_count integer not null default 0,
 received_count integer not null default 0,inserted_count integer not null default 0,updated_count integer not null default 0,
 error_code text,error_message text,requested_by uuid references auth.users(id) on delete set null,
 check(error_message is null or length(error_message)<=1000)
);
create table public.gps_vendor_events(
 id bigint generated by default as identity primary key,provider_id uuid not null references public.gps_providers(id) on delete cascade,
 device_id uuid references public.gps_devices(id) on delete cascade,external_event_id text,event_type text not null default 'vendor_event',
 occurred_at timestamptz not null default now(),payload jsonb not null default '{}',created_at timestamptz not null default now(),
 unique(provider_id,external_event_id)
);

create index gps_devices_filter_idx on public.gps_devices(provider_id,online_status,is_active);
create index gps_devices_identity_idx on public.gps_devices(plate_number,vin,registration_number);
create index gps_devices_seen_idx on public.gps_devices(last_seen_at desc);
create index gps_position_history_device_idx on public.gps_device_position_history(device_id,fix_time desc);
create index gps_sync_runs_provider_idx on public.gps_sync_runs(provider_id,started_at desc);
create unique index gps_sync_runs_one_running_idx on public.gps_sync_runs(provider_id)where status='running';

alter table public.gps_devices enable row level security;alter table public.gps_device_positions enable row level security;alter table public.gps_device_position_history enable row level security;alter table public.gps_vehicle_bindings enable row level security;alter table public.gps_sync_runs enable row level security;alter table public.gps_vendor_events enable row level security;
create policy "lvn devices read authorized" on public.gps_devices for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "lvn positions read authorized" on public.gps_device_positions for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "lvn history read authorized" on public.gps_device_position_history for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "lvn bindings read authorized" on public.gps_vehicle_bindings for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "lvn sync read authorized" on public.gps_sync_runs for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));
create policy "lvn events read authorized" on public.gps_vendor_events for select to authenticated using(app.has_role(array['ops_room','it_admin','super_admin']));

create or replace function app.lvn_num(v text)returns double precision language sql immutable as $$select case when trim(coalesce(v,''))~'^[-+]?[0-9]+([.][0-9]+)?$' then v::double precision else null end$$;
create or replace function app.lvn_json_array(v jsonb)returns jsonb language plpgsql immutable as $$declare x jsonb;begin if v is null then return'[]'::jsonb;end if;if jsonb_typeof(v)='array'then return v;end if;if jsonb_typeof(v)='string'then begin x:=(v#>>'{}')::jsonb;return case when jsonb_typeof(x)='array'then x else'[]'::jsonb end;exception when others then return'[]'::jsonb;end;end if;return'[]'::jsonb;end$$;

create or replace function public.lvn_apply_devices(p_provider_id uuid,p_items jsonb,p_cursor text default null,p_api_version text default null,p_sync_type text default'incremental')returns table(received_count integer,inserted_count integer,updated_count integer)
language plpgsql security definer set search_path=public,app as $$
declare item jsonb;did uuid;was_new boolean;received integer:=0;inserted integer:=0;updated integer:=0;fix timestamptz;lat double precision;lng double precision;spd double precision;crs double precision;alt double precision;ext text;dd jsonb;
begin
 if p_sync_type not in('full','incremental')then raise exception'LVN_SYNC_TYPE_INVALID';end if;
 if not exists(select 1 from public.gps_providers where id=p_provider_id and type='vendor_api' and is_active)then raise exception'LVN_PROVIDER_INVALID';end if;
 if jsonb_typeof(coalesce(p_items,'[]'))<>'array'then raise exception'LVN_ITEMS_INVALID';end if;
 for item in select value from jsonb_array_elements(coalesce(p_items,'[]'))loop
  ext:=nullif(item->>'id','');if ext is null then continue;end if;received:=received+1;dd:=coalesce(item->'device_data','{}');
  fix:=case when app.lvn_num(item->>'timestamp')is not null and app.lvn_num(item->>'timestamp')>0 then to_timestamp(app.lvn_num(item->>'timestamp'))else null end;
  lat:=app.lvn_num(item->>'lat');lng:=app.lvn_num(item->>'lng');spd:=app.lvn_num(item->>'speed');crs:=app.lvn_num(item->>'course');alt:=app.lvn_num(item->>'altitude');
  if lat is not null and not(lat between-90 and 90)then lat:=null;end if;if lng is not null and not(lng between-180 and 180)then lng:=null;end if;if spd is not null and spd<0 then spd:=null;end if;if crs is not null and not(crs between 0 and 360)then crs:=null;end if;
  select not exists(select 1 from public.gps_devices where provider_id=p_provider_id and external_id=ext)into was_new;
  insert into public.gps_devices(provider_id,external_id,name,imei,sim_number,msisdn,vin,plate_number,registration_number,object_owner,device_model,group_id,driver_name,protocol,online_status,alarm,is_active,vendor_updated_at,last_seen_at,sensors,services,raw_data)
  values(p_provider_id,ext,coalesce(nullif(item->>'name',''),'جهاز '||ext),nullif(dd->>'imei',''),nullif(dd->>'sim_number',''),nullif(dd->>'msisdn',''),nullif(dd->>'vin',''),nullif(dd->>'plate_number',''),nullif(dd->>'registration_number',''),nullif(dd->>'object_owner',''),nullif(dd->>'device_model',''),nullif(coalesce(dd->>'group_id',item->>'group_id'),''),nullif(item->>'driver',''),nullif(item->>'protocol',''),case when lower(item->>'online')='online'then'online'when lower(item->>'online')='offline'then'offline'else'unknown'end,nullif(item->>'alarm',''),coalesce(dd->>'active','1')<>'0',fix,fix,app.lvn_json_array(item->'sensors'),app.lvn_json_array(item->'services'),item)
  on conflict(provider_id,external_id)do update set name=excluded.name,imei=coalesce(excluded.imei,gps_devices.imei),sim_number=coalesce(excluded.sim_number,gps_devices.sim_number),msisdn=coalesce(excluded.msisdn,gps_devices.msisdn),vin=coalesce(excluded.vin,gps_devices.vin),plate_number=coalesce(excluded.plate_number,gps_devices.plate_number),registration_number=coalesce(excluded.registration_number,gps_devices.registration_number),object_owner=coalesce(excluded.object_owner,gps_devices.object_owner),device_model=coalesce(excluded.device_model,gps_devices.device_model),group_id=coalesce(excluded.group_id,gps_devices.group_id),driver_name=excluded.driver_name,protocol=coalesce(excluded.protocol,gps_devices.protocol),online_status=excluded.online_status,alarm=excluded.alarm,is_active=excluded.is_active,vendor_updated_at=greatest(gps_devices.vendor_updated_at,excluded.vendor_updated_at),last_seen_at=greatest(gps_devices.last_seen_at,excluded.last_seen_at),sensors=case when item?'sensors'then excluded.sensors else gps_devices.sensors end,services=case when item?'services'then excluded.services else gps_devices.services end,raw_data=excluded.raw_data,updated_at=now() returning id into did;
  if was_new then inserted:=inserted+1;else updated:=updated+1;end if;
  if fix is not null then
   insert into public.gps_device_position_history(device_id,latitude,longitude,speed,speed_unit,course,altitude,power,address,fix_time,raw_data)values(did,lat,lng,spd,nullif(item->>'distance_unit_hour',''),crs,alt,nullif(item->>'power','-'),nullif(item->>'address','-'),fix,item)on conflict(device_id,fix_time)do nothing;
   insert into public.gps_device_positions(device_id,latitude,longitude,speed,speed_unit,course,altitude,power,address,fix_time,raw_data)values(did,lat,lng,spd,nullif(item->>'distance_unit_hour',''),crs,alt,nullif(item->>'power','-'),nullif(item->>'address','-'),fix,item)on conflict(device_id)do update set latitude=excluded.latitude,longitude=excluded.longitude,speed=excluded.speed,speed_unit=excluded.speed_unit,course=excluded.course,altitude=excluded.altitude,power=excluded.power,address=excluded.address,fix_time=excluded.fix_time,received_at=now(),raw_data=excluded.raw_data where gps_device_positions.fix_time is null or excluded.fix_time>=gps_device_positions.fix_time;
  end if;
 end loop;
 update public.gps_providers set sync_cursor=coalesce(p_cursor,sync_cursor),api_version=coalesce(p_api_version,api_version),last_success_at=now(),last_full_sync_at=case when p_sync_type='full'then now()else last_full_sync_at end,last_incremental_sync_at=case when p_sync_type='incremental'then now()else last_incremental_sync_at end,last_error_code=null where id=p_provider_id;
 return query select received,inserted,updated;
end$$;

create or replace function public.gps_lvn_dashboard()returns jsonb language plpgsql stable security definer set search_path=public,app as $$declare u uuid:=auth.uid();r jsonb;begin if u is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;select jsonb_build_object('total',count(*),'online',count(*)filter(where d.online_status='online'),'offline',count(*)filter(where d.online_status='offline'),'moving',count(*)filter(where coalesce(p.speed,0)>0),'stopped',count(*)filter(where coalesce(p.speed,0)=0),'bound',count(*)filter(where b.id is not null),'unbound',count(*)filter(where b.id is null),'stale',count(*)filter(where p.fix_time is null or p.fix_time<now()-interval'30 minutes'),'alarms',count(*)filter(where d.alarm is not null))into r from public.gps_devices d left join public.gps_device_positions p on p.device_id=d.id left join public.gps_vehicle_bindings b on b.device_id=d.id where d.is_active;select coalesce(r,'{}')||jsonb_build_object('last_success_at',gp.last_success_at,'last_full_sync_at',gp.last_full_sync_at,'last_incremental_sync_at',gp.last_incremental_sync_at,'last_error_code',gp.last_error_code,'api_version',gp.api_version)into r from public.gps_providers gp where gp.type='vendor_api'and gp.is_active order by gp.created_at limit 1;return coalesce(r,jsonb_build_object('total',0,'online',0,'offline',0,'moving',0,'stopped',0,'bound',0,'unbound',0,'stale',0,'alarms',0));end$$;

create or replace function public.gps_lvn_devices(p_search text default null,p_online text default null,p_motion text default null,p_binding text default null,p_freshness text default null,p_owner text default null,p_model text default null,p_limit integer default 50,p_offset integer default 0)
returns table(id uuid,external_id text,device_name text,imei text,vin text,plate_number text,registration_number text,object_owner text,device_model text,driver_name text,online_status text,alarm text,last_seen_at timestamptz,latitude double precision,longitude double precision,speed double precision,speed_unit text,course double precision,power text,address text,fix_time timestamptz,garage_vehicle_id uuid,garage_vehicle_name text,garage_db_number text,total_count bigint)
language plpgsql stable security definer set search_path=public,app as $$declare u uuid:=auth.uid();q text:='%'||lower(trim(coalesce(p_search,'')))||'%';begin if u is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;if p_limit not between 1 and 100 or p_offset<0 then raise exception'GPS_PAGE_INVALID';end if;if coalesce(p_online,'')not in('','online','offline','unknown')or coalesce(p_motion,'')not in('','moving','stopped')or coalesce(p_binding,'')not in('','bound','unbound')or coalesce(p_freshness,'')not in('','fresh','stale')then raise exception'GPS_FILTER_INVALID';end if;
 return query select d.id,d.external_id,d.name,d.imei,d.vin,d.plate_number,d.registration_number,d.object_owner,d.device_model,d.driver_name,d.online_status,d.alarm,d.last_seen_at,p.latitude,p.longitude,p.speed,p.speed_unit,p.course,p.power,p.address,p.fix_time,b.garage_vehicle_id,v.vehicle_name,v.db_number,count(*)over()from public.gps_devices d left join public.gps_device_positions p on p.device_id=d.id left join public.gps_vehicle_bindings b on b.device_id=d.id left join public.garage_vehicles v on v.id=b.garage_vehicle_id where d.is_active and(coalesce(p_search,'')=''or lower(concat_ws(' ',d.name,d.external_id,d.imei,d.vin,d.plate_number,d.registration_number,d.object_owner,d.device_model,d.driver_name,v.vehicle_name,v.db_number))like q)and(coalesce(p_online,'')=''or d.online_status=p_online)and(coalesce(p_motion,'')=''or(p_motion='moving'and coalesce(p.speed,0)>0)or(p_motion='stopped'and coalesce(p.speed,0)=0))and(coalesce(p_binding,'')=''or(p_binding='bound'and b.id is not null)or(p_binding='unbound'and b.id is null))and(coalesce(p_freshness,'')=''or(p_freshness='fresh'and p.fix_time>=now()-interval'30 minutes')or(p_freshness='stale'and(p.fix_time is null or p.fix_time<now()-interval'30 minutes')))and(coalesce(p_owner,'')=''or d.object_owner=p_owner)and(coalesce(p_model,'')=''or d.device_model=p_model)order by d.online_status='online'desc,p.fix_time desc nulls last,d.name limit p_limit offset p_offset;
end$$;

create or replace function public.gps_lvn_filter_options()returns jsonb language plpgsql stable security definer set search_path=public,app as $$begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;return jsonb_build_object('owners',coalesce((select jsonb_agg(x order by x)from(select distinct object_owner x from public.gps_devices where nullif(object_owner,'')is not null)s),'[]'),'models',coalesce((select jsonb_agg(x order by x)from(select distinct device_model x from public.gps_devices where nullif(device_model,'')is not null)s),'[]'),'drivers',coalesce((select jsonb_agg(x order by x)from(select distinct driver_name x from public.gps_devices where nullif(driver_name,'')is not null)s),'[]'));end$$;

create or replace function public.gps_lvn_sync_runs(p_limit integer default 20)returns table(id uuid,sync_type text,status text,started_at timestamptz,finished_at timestamptz,pages_count integer,received_count integer,inserted_count integer,updated_count integer,error_code text,error_message text)language plpgsql stable security definer set search_path=public,app as $$begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;if p_limit not between 1 and 100 then raise exception'GPS_PAGE_INVALID';end if;return query select r.id,r.sync_type,r.status,r.started_at,r.finished_at,r.pages_count,r.received_count,r.inserted_count,r.updated_count,r.error_code,r.error_message from public.gps_sync_runs r order by r.started_at desc limit p_limit;end$$;

create or replace function public.gps_lvn_device_detail(p_device_id uuid)returns jsonb language plpgsql stable security definer set search_path=public,app as $$declare r jsonb;begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;select to_jsonb(x)into r from(select d.id,d.external_id,d.name,d.imei,d.sim_number,d.msisdn,d.vin,d.plate_number,d.registration_number,d.object_owner,d.device_model,d.group_id,d.driver_name,d.protocol,d.online_status,d.alarm,d.is_active,d.vendor_updated_at,d.last_seen_at,d.sensors,d.services,p.latitude,p.longitude,p.speed,p.speed_unit,p.course,p.altitude,p.power,p.address,p.fix_time,b.garage_vehicle_id,v.vehicle_name garage_vehicle_name,v.db_number garage_db_number,v.plate_number garage_plate_number from public.gps_devices d left join public.gps_device_positions p on p.device_id=d.id left join public.gps_vehicle_bindings b on b.device_id=d.id left join public.garage_vehicles v on v.id=b.garage_vehicle_id where d.id=p_device_id)x;if r is null then raise exception'GPS_DEVICE_NOT_FOUND';end if;return r;end$$;
create or replace function public.gps_lvn_binding_candidates(p_search text default null)returns table(id uuid,vehicle_name text,db_number text,plate_number text,chassis_number text,current_device_id uuid)language plpgsql stable security definer set search_path=public,app as $$declare q text:='%'||lower(trim(coalesce(p_search,'')))||'%';begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;return query select v.id,v.vehicle_name,v.db_number,v.plate_number,v.chassis_number,b.device_id from public.garage_vehicles v left join public.gps_vehicle_bindings b on b.garage_vehicle_id=v.id where v.archived_at is null and(coalesce(p_search,'')=''or lower(concat_ws(' ',v.vehicle_name,v.db_number,v.plate_number,v.chassis_number))like q)order by b.id is null desc,v.db_number limit 50;end$$;

create or replace function public.gps_lvn_bind_vehicle(p_device_id uuid,p_garage_vehicle_id uuid,p_notes text default null)returns void language plpgsql security definer set search_path=public,app as $$begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;if length(coalesce(p_notes,''))>500 then raise exception'GPS_NOTES_TOO_LONG';end if;if not exists(select 1 from public.gps_devices where id=p_device_id and is_active)or not exists(select 1 from public.garage_vehicles where id=p_garage_vehicle_id and archived_at is null)then raise exception'GPS_BINDING_TARGET_INVALID';end if;insert into public.gps_vehicle_bindings(device_id,garage_vehicle_id,match_method,confidence,bound_by,notes)values(p_device_id,p_garage_vehicle_id,'manual',100,auth.uid(),nullif(trim(coalesce(p_notes,'')),''))on conflict(device_id)do update set garage_vehicle_id=excluded.garage_vehicle_id,match_method='manual',confidence=100,bound_by=auth.uid(),bound_at=now(),notes=excluded.notes;end$$;
create or replace function public.gps_lvn_unbind_vehicle(p_device_id uuid)returns void language plpgsql security definer set search_path=public,app as $$begin if auth.uid()is null or not app.has_role(array['ops_room','it_admin','super_admin'])then raise exception'GPS_FORBIDDEN';end if;delete from public.gps_vehicle_bindings where device_id=p_device_id;end$$;

revoke all on function app.lvn_num(text),app.lvn_json_array(jsonb)from public,anon,authenticated;
revoke all on function public.lvn_apply_devices(uuid,jsonb,text,text,text)from public,anon,authenticated;
revoke all on function public.gps_lvn_dashboard(),public.gps_lvn_devices(text,text,text,text,text,text,text,integer,integer),public.gps_lvn_filter_options(),public.gps_lvn_sync_runs(integer),public.gps_lvn_device_detail(uuid),public.gps_lvn_binding_candidates(text),public.gps_lvn_bind_vehicle(uuid,uuid,text),public.gps_lvn_unbind_vehicle(uuid)from public,anon;
grant execute on function public.gps_lvn_dashboard(),public.gps_lvn_devices(text,text,text,text,text,text,text,integer,integer),public.gps_lvn_filter_options(),public.gps_lvn_sync_runs(integer),public.gps_lvn_device_detail(uuid),public.gps_lvn_binding_candidates(text),public.gps_lvn_bind_vehicle(uuid,uuid,text),public.gps_lvn_unbind_vehicle(uuid)to authenticated;
grant execute on function public.lvn_apply_devices(uuid,jsonb,text,text,text)to service_role;
