-- 00090 · مخزون قطع الصيانة والاستلام والصرف والتركيب والكلفة الفعلية

create table public.maintenance_inventory_items(
 id uuid primary key default gen_random_uuid(),sku text not null unique,item_name text not null,unit text not null default 'قطعة',current_quantity numeric(14,3) not null default 0 check(current_quantity>=0),average_unit_cost numeric(14,2) not null default 0 check(average_unit_cost>=0),low_stock_threshold numeric(14,3) not null default 0 check(low_stock_threshold>=0),is_active boolean not null default true,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),constraint maintenance_inventory_text_check check(length(trim(sku)) between 1 and 50 and length(trim(item_name)) between 2 and 200));
create table public.maintenance_inventory_movements(
 id uuid primary key default gen_random_uuid(),item_id uuid not null references public.maintenance_inventory_items(id),case_id uuid references public.vehicle_maintenance_cases(id),movement_type text not null check(movement_type in('receipt','issue','return')),quantity numeric(14,3) not null check(quantity>0),unit_cost numeric(14,2) not null check(unit_cost>=0),balance_after numeric(14,3) not null check(balance_after>=0),notes text,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id));
create index maintenance_inventory_movements_item_time on public.maintenance_inventory_movements(item_id,created_at desc);
create index maintenance_inventory_movements_case on public.maintenance_inventory_movements(case_id)where case_id is not null;
alter table public.maintenance_inventory_items enable row level security;alter table public.maintenance_inventory_movements enable row level security;
create policy "maintenance inventory authorized read" on public.maintenance_inventory_items for select to authenticated using(app.has_role(array['maintenance','ops_room','super_admin']));
create policy "maintenance inventory movements authorized read" on public.maintenance_inventory_movements for select to authenticated using(app.has_role(array['maintenance','ops_room','super_admin']));
create trigger trg_audit_maintenance_inventory_items after insert or update or delete on public.maintenance_inventory_items for each row execute function app.audit_trigger();
create trigger trg_audit_maintenance_inventory_movements after insert or update or delete on public.maintenance_inventory_movements for each row execute function app.audit_trigger();

alter table public.vehicle_maintenance_cases add column service_cost numeric(14,2) not null default 0 check(service_cost>=0),add column parts_actual_cost numeric(14,2) not null default 0 check(parts_actual_cost>=0);
update public.vehicle_maintenance_cases set service_cost=greatest(coalesce(actual_cost,0)-coalesce((select sum(p.quantity*coalesce(p.unit_cost,0)) from public.vehicle_maintenance_parts p where p.case_id=vehicle_maintenance_cases.id),0),0),parts_actual_cost=coalesce((select sum(p.quantity*coalesce(p.unit_cost,0)) from public.vehicle_maintenance_parts p where p.case_id=vehicle_maintenance_cases.id),0),actual_cost=greatest(coalesce(actual_cost,0),coalesce((select sum(p.quantity*coalesce(p.unit_cost,0)) from public.vehicle_maintenance_parts p where p.case_id=vehicle_maintenance_cases.id),0));
alter table public.vehicle_maintenance_parts add column inventory_item_id uuid references public.maintenance_inventory_items(id),add column issue_movement_id uuid references public.maintenance_inventory_movements(id),add column part_status text not null default 'installed' check(part_status in('issued','installed','returned')),add column installed_at timestamptz,add column installed_by uuid references auth.users(id),add column returned_at timestamptz,add column returned_by uuid references auth.users(id);
update public.vehicle_maintenance_parts set installed_at=created_at,installed_by=created_by where part_status='installed';

create or replace function public.maintenance_inventory_list(p_search text default null)
returns setof public.maintenance_inventory_items language plpgsql stable security definer set search_path=public,app as $$begin if not app.has_role(array['maintenance','ops_room','super_admin']) then raise exception 'MAINTENANCE_INVENTORY_FORBIDDEN';end if;return query select * from public.maintenance_inventory_items i where i.is_active and(p_search is null or trim(p_search)='' or i.sku ilike '%'||trim(p_search)||'%' or i.item_name ilike '%'||trim(p_search)||'%')order by(i.current_quantity<=i.low_stock_threshold)desc,i.item_name;end$$;
create or replace function public.maintenance_inventory_create(p_sku text,p_item_name text,p_unit text default 'قطعة',p_low_stock_threshold numeric default 0)
returns public.maintenance_inventory_items language plpgsql security definer set search_path=public,app as $$declare r public.maintenance_inventory_items;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if length(trim(coalesce(p_sku,'')))<1 or length(trim(coalesce(p_item_name,'')))<2 or p_low_stock_threshold<0 then raise exception 'MAINTENANCE_INVENTORY_INPUT_INVALID';end if;insert into public.maintenance_inventory_items(sku,item_name,unit,low_stock_threshold,created_by)values(upper(trim(p_sku)),trim(p_item_name),coalesce(nullif(trim(p_unit),''),'قطعة'),p_low_stock_threshold,auth.uid())returning * into r;return r;end$$;
create or replace function public.maintenance_inventory_receive(p_item_id uuid,p_quantity numeric,p_unit_cost numeric,p_notes text default null)
returns public.maintenance_inventory_movements language plpgsql security definer set search_path=public,app as $$declare i public.maintenance_inventory_items;m public.maintenance_inventory_movements;new_qty numeric;new_cost numeric;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_quantity<=0 or p_unit_cost<0 then raise exception 'MAINTENANCE_RECEIPT_INVALID';end if;select * into i from public.maintenance_inventory_items where id=p_item_id and is_active for update;if not found then raise exception 'MAINTENANCE_ITEM_NOT_FOUND';end if;new_qty:=i.current_quantity+p_quantity;new_cost:=case when new_qty=0 then 0 else round(((i.current_quantity*i.average_unit_cost)+(p_quantity*p_unit_cost))/new_qty,2)end;update public.maintenance_inventory_items set current_quantity=new_qty,average_unit_cost=new_cost,updated_at=now()where id=i.id;insert into public.maintenance_inventory_movements(item_id,movement_type,quantity,unit_cost,balance_after,notes,created_by)values(i.id,'receipt',p_quantity,p_unit_cost,new_qty,nullif(trim(coalesce(p_notes,'')),''),auth.uid())returning * into m;return m;end$$;

create or replace function public.maintenance_issue_inventory(p_case_id uuid,p_item_id uuid,p_quantity numeric,p_notes text default null)
returns public.vehicle_maintenance_parts language plpgsql security definer set search_path=public,app as $$declare i public.maintenance_inventory_items;m public.maintenance_inventory_movements;p public.vehicle_maintenance_parts;new_balance numeric;parts_total numeric;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_quantity<=0 then raise exception 'MAINTENANCE_ISSUE_INVALID';end if;if not exists(select 1 from public.vehicle_maintenance_cases where id=p_case_id and arrived_at is not null and completed_at is null)then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;select * into i from public.maintenance_inventory_items where id=p_item_id and is_active for update;if not found then raise exception 'MAINTENANCE_ITEM_NOT_FOUND';end if;if i.current_quantity<p_quantity then raise exception 'MAINTENANCE_INVENTORY_INSUFFICIENT';end if;new_balance:=i.current_quantity-p_quantity;update public.maintenance_inventory_items set current_quantity=new_balance,updated_at=now()where id=i.id;insert into public.maintenance_inventory_movements(item_id,case_id,movement_type,quantity,unit_cost,balance_after,notes,created_by)values(i.id,p_case_id,'issue',p_quantity,i.average_unit_cost,new_balance,nullif(trim(coalesce(p_notes,'')),''),auth.uid())returning * into m;insert into public.vehicle_maintenance_parts(case_id,part_name,quantity,unit,unit_cost,notes,created_by,inventory_item_id,issue_movement_id,part_status)values(p_case_id,i.item_name,p_quantity,i.unit,i.average_unit_cost,nullif(trim(coalesce(p_notes,'')),''),auth.uid(),i.id,m.id,'issued')returning * into p;select coalesce(sum(quantity*coalesce(unit_cost,0))filter(where part_status in('issued','installed')),0)into parts_total from public.vehicle_maintenance_parts where case_id=p_case_id;update public.vehicle_maintenance_cases set parts_actual_cost=parts_total,actual_cost=service_cost+parts_total,updated_at=now()where id=p_case_id;return p;end$$;

create or replace function public.maintenance_install_issued_part(p_part_id uuid)
returns public.vehicle_maintenance_parts language plpgsql security definer set search_path=public,app as $$declare p public.vehicle_maintenance_parts;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;update public.vehicle_maintenance_parts set part_status='installed',installed_at=now(),installed_by=auth.uid()where id=p_part_id and inventory_item_id is not null and issue_movement_id is not null and part_status='issued' returning * into p;if not found then raise exception 'MAINTENANCE_PART_NOT_ISSUED';end if;return p;end$$;
create or replace function public.maintenance_return_issued_part(p_part_id uuid,p_notes text default null)
returns public.vehicle_maintenance_parts language plpgsql security definer set search_path=public,app as $$declare p public.vehicle_maintenance_parts;i public.maintenance_inventory_items;m public.maintenance_inventory_movements;parts_total numeric;begin if not app.has_role(array['maintenance']) then raise exception 'MAINTENANCE_FORBIDDEN';end if;select * into p from public.vehicle_maintenance_parts where id=p_part_id and inventory_item_id is not null and part_status='issued' for update;if not found then raise exception 'MAINTENANCE_PART_NOT_RETURNABLE';end if;select * into i from public.maintenance_inventory_items where id=p.inventory_item_id for update;update public.maintenance_inventory_items set current_quantity=current_quantity+p.quantity,updated_at=now()where id=i.id returning * into i;insert into public.maintenance_inventory_movements(item_id,case_id,movement_type,quantity,unit_cost,balance_after,notes,created_by)values(i.id,p.case_id,'return',p.quantity,coalesce(p.unit_cost,0),i.current_quantity,nullif(trim(coalesce(p_notes,'')),''),auth.uid())returning * into m;update public.vehicle_maintenance_parts set part_status='returned',returned_at=now(),returned_by=auth.uid()where id=p.id returning * into p;select coalesce(sum(quantity*coalesce(unit_cost,0))filter(where part_status in('issued','installed')),0)into parts_total from public.vehicle_maintenance_parts where case_id=p.case_id;update public.vehicle_maintenance_cases set parts_actual_cost=parts_total,actual_cost=service_cost+parts_total,updated_at=now()where id=p.case_id;return p;end$$;

-- القطع اليدوية لم تعد مساراً صالحاً؛ كل قطعة جديدة يجب أن تصرف من المخزون.
revoke execute on function public.maintenance_add_part(uuid,text,numeric,text,numeric,text) from authenticated;

-- تحديث الكلفة: المدخل اليدوي هو كلفة الخدمة، والإجمالي يجمعها مع القطع المصروفة.
drop function public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text,uuid);
create function public.maintenance_update_case(p_case_id uuid,p_status text,p_progress integer,p_diagnosis text default null,p_work_notes text default null,p_parts_notes text default null,p_expected_completion_at timestamptz default null,p_assigned_technician text default null,p_estimated_cost numeric default null,p_actual_cost numeric default null,p_delay_reason text default null,p_assigned_technician_id uuid default null)
returns public.vehicle_maintenance_cases language plpgsql security definer set search_path=public,app as $$declare u uuid:=auth.uid();c public.vehicle_maintenance_cases;tech_name text;begin if not app.has_role(array['maintenance'])then raise exception 'MAINTENANCE_FORBIDDEN';end if;if p_status not in('at_maintenance','diagnosing','waiting_parts','in_repair','paused','ready')or p_progress not between 0 and 100 then raise exception 'MAINTENANCE_UPDATE_INVALID';end if;if p_status='ready'and(p_progress<>100 or exists(select 1 from public.vehicle_maintenance_parts where case_id=p_case_id and part_status='issued'))then raise exception 'MAINTENANCE_READY_REQUIRES_INSTALLED_PARTS';end if;if p_actual_cost<0 or p_estimated_cost<0 then raise exception 'MAINTENANCE_COST_INVALID';end if;if p_assigned_technician_id is not null then select coalesce(nullif(trim(e.full_name),''),au.email,p_assigned_technician_id::text)into tech_name from auth.users au left join public.employees e on e.user_id=au.id where au.id=p_assigned_technician_id and exists(select 1 from public.user_roles ur where ur.user_id=au.id and ur.role='maintenance');if not found then raise exception 'MAINTENANCE_TECHNICIAN_INVALID';end if;else tech_name:=nullif(trim(coalesce(p_assigned_technician,'')),'');end if;update public.vehicle_maintenance_cases set status=p_status,progress=p_progress,diagnosis=nullif(trim(coalesce(p_diagnosis,'')),''),work_notes=nullif(trim(coalesce(p_work_notes,'')),''),parts_notes=nullif(trim(coalesce(p_parts_notes,'')),''),expected_completion_at=p_expected_completion_at,assigned_technician=coalesce(tech_name,assigned_technician),assigned_technician_id=coalesce(p_assigned_technician_id,assigned_technician_id),estimated_cost=p_estimated_cost,service_cost=coalesce(p_actual_cost,service_cost),actual_cost=coalesce(p_actual_cost,service_cost)+parts_actual_cost,delay_reason=nullif(trim(coalesce(p_delay_reason,'')),''),ready_at=case when p_status='ready'then coalesce(ready_at,now())else ready_at end,ready_declared_by=case when p_status='ready'then u else ready_declared_by end,readiness_approved_at=case when p_status='ready'then null else readiness_approved_at end,readiness_approved_by=case when p_status='ready'then null else readiness_approved_by end,readiness_approval_notes=case when p_status='ready'then null else readiness_approval_notes end,updated_at=now()where id=p_case_id and arrived_at is not null and completed_at is null returning * into c;if not found then raise exception 'MAINTENANCE_CASE_NOT_OPEN';end if;insert into public.vehicle_maintenance_updates(case_id,status,progress,diagnosis,work_notes,parts_notes,assigned_technician,assigned_technician_id,estimated_cost,actual_cost,delay_reason,expected_completion_at,created_by)values(c.id,c.status,c.progress,c.diagnosis,c.work_notes,c.parts_notes,c.assigned_technician,c.assigned_technician_id,c.estimated_cost,c.actual_cost,c.delay_reason,c.expected_completion_at,u);return c;end$$;

grant execute on function public.maintenance_inventory_list(text),public.maintenance_inventory_create(text,text,text,numeric),public.maintenance_inventory_receive(uuid,numeric,numeric,text),public.maintenance_issue_inventory(uuid,uuid,numeric,text),public.maintenance_install_issued_part(uuid),public.maintenance_return_issued_part(uuid,text),public.maintenance_update_case(uuid,text,integer,text,text,text,timestamptz,text,numeric,numeric,text,uuid) to authenticated;
revoke all on function public.maintenance_inventory_list(text),public.maintenance_inventory_create(text,text,text,numeric),public.maintenance_inventory_receive(uuid,numeric,numeric,text),public.maintenance_issue_inventory(uuid,uuid,numeric,text),public.maintenance_install_issued_part(uuid),public.maintenance_return_issued_part(uuid,text) from public,anon;
