-- 00117 · غرفة العمليات مالكة قاعدة الآليات، وكل حساب كراج مقيد بقاطع واحد.

create table public.garage_user_profiles(
 user_id uuid primary key references auth.users(id)on delete cascade,
 parent_sector text not null check(parent_sector in('karrada','zaafaraniya')),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
alter table public.garage_user_profiles enable row level security;
create policy "garage profile self or admin read"on public.garage_user_profiles for select to authenticated using(user_id=auth.uid()or app.has_role(array['it_admin','super_admin']));
create policy "garage profile admin manage"on public.garage_user_profiles for all to authenticated using(app.has_role(array['it_admin','super_admin']))with check(app.has_role(array['it_admin','super_admin']));
create trigger trg_garage_user_profiles_updated before update on public.garage_user_profiles for each row execute function app.set_updated_at();

create or replace function app.require_fleet_master_actor()returns uuid language plpgsql stable security definer set search_path=public,app as $$declare u uuid:=auth.uid();begin if u is null or not app.has_role(array['ops_room','super_admin'])then raise exception'OPS_FLEET_MASTER_FORBIDDEN';end if;return u;end$$;
create or replace function app.current_garage_parent_sector()returns text language sql stable security definer set search_path=public,app as $$select parent_sector from public.garage_user_profiles where user_id=auth.uid()$$;
create or replace function app.garage_vehicle_allowed(p_vehicle_id uuid)returns boolean language sql stable security definer set search_path=public,app as $$select case when app.has_role(array['ops_room','super_admin'])then true when app.has_role(array['central_garage_officer'])then exists(select 1 from public.garage_vehicles v join public.sectors s on s.id=v.sector_id join public.garage_user_profiles gp on gp.user_id=auth.uid() where v.id=p_vehicle_id and s.parent_sector=gp.parent_sector)else false end$$;
revoke all on function app.require_fleet_master_actor(),app.current_garage_parent_sector(),app.garage_vehicle_allowed(uuid)from public,anon;
grant execute on function app.garage_vehicle_allowed(uuid)to authenticated;

drop policy if exists "garage vehicles read"on public.garage_vehicles;
create policy "garage vehicles scoped read"on public.garage_vehicles for select to authenticated using(app.garage_vehicle_allowed(id));
drop policy if exists "garage assignments read"on public.garage_driver_assignments;
create policy "garage assignments scoped read"on public.garage_driver_assignments for select to authenticated using(app.garage_vehicle_allowed(vehicle_id));
drop policy if exists "garage shift assignment read"on public.garage_vehicle_shift_assignments;
create policy "garage shift assignment scoped read"on public.garage_vehicle_shift_assignments for select to authenticated using(app.garage_vehicle_allowed(vehicle_id));
drop policy if exists "garage departures read"on public.garage_departures;
create policy "garage departures scoped read"on public.garage_departures for select to authenticated using(app.garage_vehicle_allowed(vehicle_id)or recipient_manager_id=auth.uid());

drop policy if exists "garage vehicle images read"on storage.objects;
create policy "garage vehicle images authorized read"on storage.objects for select to authenticated using(bucket_id='garage-vehicles'and app.has_role(array['central_garage_officer','ops_room','super_admin']));
drop policy if exists "garage vehicle images upload"on storage.objects;
create policy "ops vehicle images upload"on storage.objects for insert to authenticated with check(bucket_id='garage-vehicles'and app.has_role(array['ops_room','super_admin'])and auth.uid()::text=(storage.foldername(name))[1]);

create or replace function public.garage_visible_areas()returns table(id smallint,name text,parent_sector text,sort smallint)
language plpgsql stable security definer set search_path=public,app as $$declare p text:=app.current_garage_parent_sector();begin if not app.has_role(array['central_garage_officer','ops_room','super_admin'])then raise exception'GARAGE_FORBIDDEN';end if;if app.has_role(array['central_garage_officer'])and not app.has_role(array['ops_room','super_admin'])and p is null then raise exception'GARAGE_PROFILE_NOT_CONFIGURED';end if;return query select s.id,s.name,s.parent_sector,s.sort from public.sectors s where p is null or app.has_role(array['ops_room','super_admin'])or s.parent_sector=p order by s.sort;end$$;
create or replace function public.garage_profile_for_user(p_user_id uuid)returns text language plpgsql stable security definer set search_path=public,app as $$begin if p_user_id<>auth.uid()and not app.has_role(array['it_admin','super_admin'])then raise exception'GARAGE_PROFILE_FORBIDDEN';end if;return(select parent_sector from public.garage_user_profiles where user_id=p_user_id);end$$;
create or replace function public.garage_profile_save(p_user_id uuid,p_parent_sector text)returns void language plpgsql security definer set search_path=public,app as $$begin if not app.has_role(array['it_admin','super_admin'])then raise exception'GARAGE_PROFILE_FORBIDDEN';end if;if p_parent_sector not in('karrada','zaafaraniya')then raise exception'GARAGE_PARENT_SECTOR_INVALID';end if;if not exists(select 1 from public.user_roles where user_id=p_user_id and role='central_garage_officer')then raise exception'GARAGE_ROLE_REQUIRED';end if;insert into public.garage_user_profiles(user_id,parent_sector)values(p_user_id,p_parent_sector)on conflict(user_id)do update set parent_sector=excluded.parent_sector,updated_at=now();end$$;

create or replace function public.garage_search_vehicles(p_search text default null,p_sector_id smallint default null,p_shift text default null,p_limit integer default 48,p_offset integer default 0,p_archived boolean default false)
returns table(id uuid,vehicle_name text,db_number text,plate_number text,chassis_number text,image_path text,vehicle_category text,ownership_type text,lessor_name text,rental_contract_no text,rental_start_date date,rental_end_date date,model_year smallint,vehicle_color text,specifications text,shift text,driver_name text,sector_id smallint,area_name text,parent_sector text,created_at timestamptz,updated_at timestamptz,archived_at timestamptz,archived_by uuid,archive_reason text,total_count bigint)
language plpgsql stable security definer set search_path=public,app as $$declare q text:=trim(coalesce(p_search,''));garage_parent text:=app.current_garage_parent_sector();begin if auth.uid()is null or not app.has_role(array['central_garage_officer','ops_room','super_admin'])then raise exception'GARAGE_FORBIDDEN';end if;if app.has_role(array['central_garage_officer'])and not app.has_role(array['ops_room','super_admin'])and garage_parent is null then raise exception'GARAGE_PROFILE_NOT_CONFIGURED';end if;if p_shift is not null and p_shift not in('morning','evening','night')then raise exception'GARAGE_SHIFT_INVALID';end if;if p_limit<1 or p_limit>100 or p_offset<0 then raise exception'GARAGE_PAGINATION_INVALID';end if;return query select v.id,v.vehicle_name,v.db_number,v.plate_number,v.chassis_number,v.image_path,v.vehicle_category,v.ownership_type,v.lessor_name,v.rental_contract_no,v.rental_start_date,v.rental_end_date,v.model_year,v.vehicle_color,v.specifications,v.shift,v.driver_name,v.sector_id,s.name,s.parent_sector,v.created_at,v.updated_at,v.archived_at,v.archived_by,v.archive_reason,count(*)over()from public.garage_vehicles v join public.sectors s on s.id=v.sector_id where(case when p_archived then v.archived_at is not null else v.archived_at is null end)and(garage_parent is null or app.has_role(array['ops_room','super_admin'])or s.parent_sector=garage_parent)and(p_sector_id is null or v.sector_id=p_sector_id)and(p_shift is null or v.shift=p_shift)and(q=''or v.db_number ilike'%'||q||'%'or v.vehicle_name ilike'%'||q||'%'or v.driver_name ilike'%'||q||'%'or v.plate_number ilike'%'||q||'%'or v.chassis_number ilike'%'||q||'%'or v.lessor_name ilike'%'||q||'%')order by case when p_archived then v.archived_at else v.created_at end desc limit p_limit offset p_offset;end$$;

create or replace function public.garage_add_vehicle(p_vehicle_name text,p_db_number text,p_plate_number text,p_chassis_number text,p_image_path text,p_shift text,p_driver_name text,p_sector_id smallint,p_vehicle_category text default'other',p_ownership_type text default'owned',p_lessor_name text default null,p_rental_contract_no text default null,p_rental_start_date date default null,p_rental_end_date date default null,p_model_year smallint default null,p_vehicle_color text default null,p_specifications text default null)
returns public.garage_vehicles language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();r public.garage_vehicles;begin if p_shift not in('morning','evening','night')then raise exception'GARAGE_SHIFT_INVALID';end if;if p_vehicle_category not in('compactor_small','compactor_large','truck','shovel','tipper','tanker','sweeper','strat','other')then raise exception'GARAGE_VEHICLE_CATEGORY_INVALID';end if;if p_ownership_type not in('owned','rented')then raise exception'GARAGE_OWNERSHIP_TYPE_INVALID';end if;if p_ownership_type='rented'and length(trim(coalesce(p_lessor_name,'')))<2 then raise exception'GARAGE_LESSOR_REQUIRED';end if;if p_rental_end_date is not null and(p_rental_start_date is null or p_rental_end_date<p_rental_start_date)then raise exception'GARAGE_RENTAL_DATES_INVALID';end if;if not exists(select 1 from public.sectors where id=p_sector_id)then raise exception'GARAGE_AREA_INVALID';end if;if length(trim(coalesce(p_vehicle_name,'')))<2 or length(trim(coalesce(p_db_number,'')))<1 or length(trim(coalesce(p_plate_number,'')))<1 or length(trim(coalesce(p_chassis_number,'')))<3 or length(trim(coalesce(p_driver_name,'')))<2 then raise exception'GARAGE_VEHICLE_FIELDS_REQUIRED';end if;if p_image_path is null or p_image_path not like u::text||'/%'then raise exception'GARAGE_IMAGE_PATH_INVALID';end if;insert into public.garage_vehicles(vehicle_name,db_number,plate_number,chassis_number,image_path,shift,driver_name,sector_id,created_by,vehicle_category,ownership_type,lessor_name,rental_contract_no,rental_start_date,rental_end_date,model_year,vehicle_color,specifications)values(trim(p_vehicle_name),trim(p_db_number),trim(p_plate_number),trim(p_chassis_number),trim(p_image_path),p_shift,trim(p_driver_name),p_sector_id,u,p_vehicle_category,p_ownership_type,case when p_ownership_type='rented'then nullif(trim(coalesce(p_lessor_name,'')),'')end,case when p_ownership_type='rented'then nullif(trim(coalesce(p_rental_contract_no,'')),'')end,case when p_ownership_type='rented'then p_rental_start_date end,case when p_ownership_type='rented'then p_rental_end_date end,p_model_year,nullif(trim(coalesce(p_vehicle_color,'')),''),nullif(trim(coalesce(p_specifications,'')),''))returning*into r;insert into public.garage_driver_assignments(vehicle_id,driver_name,shift,sector_id,assigned_by,change_reason)values(r.id,r.driver_name,r.shift,r.sector_id,u,'الإسناد الأول من غرفة العمليات');return r;exception when unique_violation then raise exception'GARAGE_VEHICLE_IDENTIFIER_DUPLICATE';end$$;

create or replace function public.garage_update_vehicle(p_vehicle_id uuid,p_vehicle_name text,p_db_number text,p_plate_number text,p_chassis_number text,p_image_path text default null,p_vehicle_category text default'other',p_ownership_type text default'owned',p_lessor_name text default null,p_rental_contract_no text default null,p_rental_start_date date default null,p_rental_end_date date default null,p_model_year smallint default null,p_vehicle_color text default null,p_specifications text default null)
returns public.garage_vehicles language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();r public.garage_vehicles;begin if p_vehicle_category not in('compactor_small','compactor_large','truck','shovel','tipper','tanker','sweeper','strat','other')or p_ownership_type not in('owned','rented')then raise exception'GARAGE_VEHICLE_FIELDS_INVALID';end if;if p_ownership_type='rented'and length(trim(coalesce(p_lessor_name,'')))<2 then raise exception'GARAGE_LESSOR_REQUIRED';end if;if length(trim(coalesce(p_vehicle_name,'')))<2 or length(trim(coalesce(p_db_number,'')))<1 or length(trim(coalesce(p_plate_number,'')))<1 or length(trim(coalesce(p_chassis_number,'')))<3 then raise exception'GARAGE_VEHICLE_FIELDS_REQUIRED';end if;if p_image_path is not null and p_image_path not like u::text||'/%'then raise exception'GARAGE_IMAGE_PATH_INVALID';end if;update public.garage_vehicles set vehicle_name=trim(p_vehicle_name),db_number=trim(p_db_number),plate_number=trim(p_plate_number),chassis_number=trim(p_chassis_number),image_path=coalesce(nullif(trim(coalesce(p_image_path,'')),''),image_path),vehicle_category=p_vehicle_category,ownership_type=p_ownership_type,lessor_name=case when p_ownership_type='rented'then nullif(trim(coalesce(p_lessor_name,'')),'')end,rental_contract_no=case when p_ownership_type='rented'then nullif(trim(coalesce(p_rental_contract_no,'')),'')end,rental_start_date=case when p_ownership_type='rented'then p_rental_start_date end,rental_end_date=case when p_ownership_type='rented'then p_rental_end_date end,model_year=p_model_year,vehicle_color=nullif(trim(coalesce(p_vehicle_color,'')),''),specifications=nullif(trim(coalesce(p_specifications,'')),'')where id=p_vehicle_id and archived_at is null returning*into r;if not found then raise exception'GARAGE_VEHICLE_NOT_FOUND';end if;return r;exception when unique_violation then raise exception'GARAGE_VEHICLE_IDENTIFIER_DUPLICATE';end$$;

create or replace function public.garage_assign_driver(p_vehicle_id uuid,p_driver_name text,p_shift text,p_sector_id smallint,p_reason text default null)
returns public.garage_driver_assignments language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();r public.garage_driver_assignments;begin if length(trim(coalesce(p_driver_name,'')))<2 or p_shift not in('morning','evening','night')or not exists(select 1 from public.sectors where id=p_sector_id)then raise exception'GARAGE_ASSIGNMENT_INVALID';end if;if exists(select 1 from public.garage_departures where vehicle_id=p_vehicle_id and returned_at is null)then raise exception'GARAGE_VEHICLE_IN_FIELD';end if;update public.garage_driver_assignments set ends_at=now(),change_reason=coalesce(nullif(trim(coalesce(p_reason,'')),''),change_reason)where vehicle_id=p_vehicle_id and ends_at is null;insert into public.garage_driver_assignments(vehicle_id,driver_name,shift,sector_id,assigned_by,change_reason)values(p_vehicle_id,trim(p_driver_name),p_shift,p_sector_id,u,nullif(trim(coalesce(p_reason,'')),''))returning*into r;update public.garage_vehicles set driver_name=r.driver_name,shift=r.shift,sector_id=r.sector_id where id=p_vehicle_id and archived_at is null;if not found then raise exception'GARAGE_VEHICLE_NOT_FOUND';end if;return r;end$$;

create or replace function public.garage_set_vehicle_shift_assignment(p_vehicle_id uuid,p_shift text,p_driver_name text,p_sector_id smallint,p_reason text)
returns public.garage_vehicle_shift_assignments language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();r public.garage_vehicle_shift_assignments;begin if p_shift not in('morning','evening','night')or length(trim(coalesce(p_driver_name,'')))<2 or length(trim(coalesce(p_reason,'')))<3 then raise exception'GARAGE_SHIFT_ASSIGNMENT_INVALID';end if;if not exists(select 1 from public.garage_vehicles where id=p_vehicle_id and archived_at is null)then raise exception'GARAGE_VEHICLE_NOT_FOUND';end if;if not exists(select 1 from public.sectors where id=p_sector_id)then raise exception'GARAGE_AREA_INVALID';end if;perform pg_advisory_xact_lock(hashtextextended(p_vehicle_id::text||p_shift,0));if exists(select 1 from public.garage_departures where vehicle_id=p_vehicle_id and shift=p_shift and returned_at is null)then raise exception'GARAGE_SHIFT_IN_FIELD';end if;update public.garage_vehicle_shift_assignments set ends_at=now(),change_reason=trim(p_reason)where vehicle_id=p_vehicle_id and shift=p_shift and ends_at is null;insert into public.garage_vehicle_shift_assignments(vehicle_id,shift,driver_name,sector_id,change_reason,created_by)values(p_vehicle_id,p_shift,trim(p_driver_name),p_sector_id,trim(p_reason),u)returning*into r;update public.garage_vehicles set driver_name=r.driver_name,shift=r.shift,sector_id=r.sector_id where id=p_vehicle_id;return r;end$$;

create or replace function public.garage_archive_vehicle(p_vehicle_id uuid,p_reason text)returns void language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();begin if length(trim(coalesce(p_reason,'')))<5 then raise exception'GARAGE_ARCHIVE_REASON_REQUIRED';end if;if exists(select 1 from public.garage_departures where vehicle_id=p_vehicle_id and returned_at is null)then raise exception'GARAGE_VEHICLE_IN_FIELD';end if;update public.garage_vehicles set archived_at=now(),archived_by=u,archive_reason=trim(p_reason)where id=p_vehicle_id and archived_at is null;if not found then raise exception'GARAGE_VEHICLE_NOT_FOUND';end if;update public.garage_driver_assignments set ends_at=now(),change_reason=coalesce(change_reason,'أرشفة الآلية')where vehicle_id=p_vehicle_id and ends_at is null;update public.garage_vehicle_shift_assignments set ends_at=now(),change_reason=coalesce(change_reason,'أرشفة الآلية')where vehicle_id=p_vehicle_id and ends_at is null;end$$;
create or replace function public.garage_restore_vehicle(p_vehicle_id uuid,p_reason text)returns public.garage_vehicles language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_fleet_master_actor();r public.garage_vehicles;begin if length(trim(coalesce(p_reason,'')))<5 then raise exception'GARAGE_RESTORE_REASON_REQUIRED';end if;update public.garage_vehicles set archived_at=null,archived_by=null,archive_reason=null where id=p_vehicle_id and archived_at is not null returning*into r;if not found then raise exception'GARAGE_ARCHIVED_VEHICLE_NOT_FOUND';end if;insert into public.garage_driver_assignments(vehicle_id,driver_name,shift,sector_id,assigned_by,change_reason)values(r.id,r.driver_name,r.shift,r.sector_id,u,'استعادة الآلية: من غرفة العمليات');return r;end$$;

create or replace function public.garage_vehicle_shift_assignments_list(p_vehicle_id uuid)returns table(id uuid,vehicle_id uuid,shift text,driver_name text,sector_id smallint,area_name text,parent_sector text,starts_at timestamptz,ends_at timestamptz,change_reason text)language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();if not app.garage_vehicle_allowed(p_vehicle_id)then raise exception'GARAGE_VEHICLE_SCOPE_FORBIDDEN';end if;return query select a.id,a.vehicle_id,a.shift,a.driver_name,a.sector_id,s.name,s.parent_sector,a.starts_at,a.ends_at,a.change_reason from public.garage_vehicle_shift_assignments a join public.sectors s on s.id=a.sector_id where a.vehicle_id=p_vehicle_id order by(a.ends_at is null)desc,a.starts_at desc;end$$;

create or replace function public.garage_record_shift_departure(p_vehicle_id uuid,p_shift text,p_notes text default null)returns public.garage_departures language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();v public.garage_vehicles;a public.garage_vehicle_shift_assignments;d public.garage_departures;mid uuid;mn text;begin if not app.garage_vehicle_allowed(p_vehicle_id)then raise exception'GARAGE_VEHICLE_SCOPE_FORBIDDEN';end if;if p_shift not in('morning','evening','night')then raise exception'GARAGE_SHIFT_INVALID';end if;select*into v from public.garage_vehicles where id=p_vehicle_id and archived_at is null for update;if not found then raise exception'GARAGE_VEHICLE_NOT_FOUND';end if;if exists(select 1 from public.vehicle_maintenance_cases where vehicle_id=v.id and completed_at is null)then raise exception'GARAGE_VEHICLE_IN_MAINTENANCE';end if;if exists(select 1 from public.garage_departures where vehicle_id=v.id and returned_at is null)then raise exception'GARAGE_DEPARTURE_ALREADY_OPEN';end if;select*into a from public.garage_vehicle_shift_assignments where vehicle_id=v.id and shift=p_shift and ends_at is null;if not found then raise exception'GARAGE_SHIFT_ASSIGNMENT_NOT_FOUND';end if;select user_id,manager_name into mid,mn from app.resolve_sector_shift_manager(a.sector_id,p_shift);insert into public.garage_departures(vehicle_id,driver_name,shift,sector_id,departed_by,notes,recipient_manager_id,recipient_manager_name)values(v.id,a.driver_name,p_shift,a.sector_id,u,nullif(trim(coalesce(p_notes,'')),''),mid,mn)returning*into d;insert into public.notifications(user_id,title,body,type,link,category,entity_type,entity_id,dedupe_key)values(mid,'آلية في الطريق إلى موقع العمل',format('%s · DB %s انطلقت تلقائياً إلى منطقتك في الشفت %s',v.vehicle_name,v.db_number,p_shift),'info','/manager/vehicle-trips','departure','garage_departure',d.id,'departure:auto-manager:'||d.id::text)on conflict(user_id,dedupe_key)where dedupe_key is not null do nothing;return d;end$$;

create or replace function public.garage_record_return(p_departure_id uuid)returns public.garage_departures language plpgsql security definer set search_path=public,app as $$declare u uuid:=app.require_garage_actor();d public.garage_departures;l public.vehicle_trip_legs;c public.vehicle_maintenance_cases;begin select*into d from public.garage_departures where id=p_departure_id and returned_at is null for update;if not found then raise exception'GARAGE_OPEN_DEPARTURE_NOT_FOUND';end if;if not app.garage_vehicle_allowed(d.vehicle_id)then raise exception'GARAGE_VEHICLE_SCOPE_FORBIDDEN';end if;select*into l from public.vehicle_trip_legs where departure_id=d.id and arrived_at is null for update;if found then if l.destination_type<>'garage'then raise exception'GARAGE_VEHICLE_NOT_SENT_BACK';end if;update public.vehicle_trip_legs set arrived_at=now(),arrived_by=u,arrival_notes='أكد الكراج الوصول'where id=l.id;elsif d.recipient_manager_id is not null and d.site_departed_at is null then raise exception'GARAGE_VEHICLE_NOT_SENT_BACK';end if;update public.garage_departures set arrived_at=coalesce(arrived_at,now()),arrived_by=coalesce(arrived_by,u),site_departed_at=coalesce(site_departed_at,now()),site_departed_by=coalesce(site_departed_by,u),returned_at=now(),returned_by=u where id=d.id returning*into d;update public.vehicle_maintenance_cases set status='closed_at_garage',completed_at=now(),updated_at=now()where departure_id=d.id and status='to_garage'and completed_at is null returning*into c;if found then update public.sector_breakdowns set status='resolved',resolved_at=now(),resolved_by=u,resolution_notes='أغلقت الحالة بعد وصول الآلية من الصيانة إلى الكراج'where id=c.breakdown_id;end if;if d.recipient_manager_id is not null then insert into public.notifications(user_id,title,body,type,link)values(d.recipient_manager_id,'وصلت الآلية إلى الكراج',format('أكد الكراج استلام الآلية DB %s وإغلاق الانطلاقة',(select db_number from public.garage_vehicles where id=d.vehicle_id)),'success','/manager/vehicle-trips');end if;return d;end$$;

create or replace function public.garage_today_departures()
returns table(id uuid,vehicle_id uuid,driver_name text,shift text,sector_id smallint,departed_at timestamptz,arrived_at timestamptz,site_departed_at timestamptz,returned_at timestamptz,recipient_manager_id uuid,recipient_manager_name text,arrival_notes text,site_departure_notes text,notes text,vehicle_name text,db_number text,image_path text,area_name text,parent_sector text)language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select d.id,d.vehicle_id,d.driver_name,d.shift,d.sector_id,d.departed_at,d.arrived_at,d.site_departed_at,d.returned_at,d.recipient_manager_id,d.recipient_manager_name,d.arrival_notes,d.site_departure_notes,d.notes,v.vehicle_name,v.db_number,v.image_path,s.name,s.parent_sector from public.garage_departures d join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where app.garage_vehicle_allowed(d.vehicle_id)and(d.returned_at is null or(d.departed_at at time zone'Asia/Baghdad')::date=(now()at time zone'Asia/Baghdad')::date)order by(d.returned_at is null)desc,d.departed_at desc;end$$;

create or replace function public.garage_shift_dispatch_recipients(p_vehicle_id uuid,p_shift text)returns table(user_id uuid,manager_name text,shift text,sectors smallint[])language plpgsql stable security definer set search_path=public,app as $$declare sid smallint;begin perform app.require_garage_actor();if not app.garage_vehicle_allowed(p_vehicle_id)then raise exception'GARAGE_VEHICLE_SCOPE_FORBIDDEN';end if;select sector_id into sid from public.garage_vehicle_shift_assignments where vehicle_id=p_vehicle_id and shift=p_shift and ends_at is null;if sid is null then return;end if;return query select mp.user_id,coalesce(nullif(e.full_name,''),u.email,mp.user_id::text),mp.shift,mp.sectors from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where sid=any(mp.sectors)and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager')order by 2;end$$;
create or replace function public.garage_dispatch_recipients(p_vehicle_id uuid)returns table(user_id uuid,manager_name text,shift text,sectors smallint[])language plpgsql stable security definer set search_path=public,app as $$declare sid smallint;begin perform app.require_garage_actor();if not app.garage_vehicle_allowed(p_vehicle_id)then raise exception'GARAGE_VEHICLE_SCOPE_FORBIDDEN';end if;select sector_id into sid from public.garage_vehicles where id=p_vehicle_id and archived_at is null;if sid is null then return;end if;return query select mp.user_id,coalesce(nullif(e.full_name,''),u.email,mp.user_id::text),mp.shift,mp.sectors from public.manager_profiles mp left join public.employees e on e.user_id=mp.user_id left join auth.users u on u.id=mp.user_id where sid=any(mp.sectors)and exists(select 1 from public.user_roles ur where ur.user_id=mp.user_id and ur.role='department_manager')order by 2;end$$;

create or replace function public.garage_departure_days(p_limit integer default 60,p_offset integer default 0)returns table(trip_day date,total_count bigint,open_count bigint,first_departure_at timestamptz,last_activity_at timestamptz)language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select(d.departed_at at time zone'Asia/Baghdad')::date,count(*),count(*)filter(where d.returned_at is null),min(d.departed_at),max(coalesce(d.returned_at,d.site_departed_at,d.arrived_at,d.departed_at))from public.garage_departures d where app.garage_vehicle_allowed(d.vehicle_id)group by 1 order by 1 desc limit p_limit offset p_offset;end$$;
create or replace function public.garage_departures_for_day(p_day date)returns table(id uuid,vehicle_id uuid,driver_name text,shift text,sector_id smallint,departed_at timestamptz,arrived_at timestamptz,site_departed_at timestamptz,returned_at timestamptz,recipient_manager_id uuid,recipient_manager_name text,arrival_notes text,site_departure_notes text,notes text,vehicle_name text,db_number text,image_path text,area_name text,parent_sector text)language plpgsql stable security definer set search_path=public,app as $$begin perform app.require_garage_actor();return query select d.id,d.vehicle_id,d.driver_name,d.shift,d.sector_id,d.departed_at,d.arrived_at,d.site_departed_at,d.returned_at,d.recipient_manager_id,d.recipient_manager_name,d.arrival_notes,d.site_departure_notes,d.notes,v.vehicle_name,v.db_number,v.image_path,s.name,s.parent_sector from public.garage_departures d join public.garage_vehicles v on v.id=d.vehicle_id join public.sectors s on s.id=d.sector_id where app.garage_vehicle_allowed(d.vehicle_id)and(d.departed_at at time zone'Asia/Baghdad')::date=p_day order by d.departed_at desc;end$$;

revoke all on function public.garage_visible_areas(),public.garage_profile_for_user(uuid),public.garage_profile_save(uuid,text)from public,anon;
grant execute on function public.garage_visible_areas(),public.garage_profile_for_user(uuid),public.garage_profile_save(uuid,text)to authenticated;
